### DISCUSSION TITLE
Response headers

### DISCUSSION THREAD

**Discussion by mohit61** [apollographql/router#1902] [General]
Hi, the router is stripping the request and response header. The request headers were fixed by the following config:
```
headers:
  all:
    request:
      - propagate:
          matching: .*
```

however I do not see the config for response headers, how to allow  router to return all the response headers?
