### DISCUSSION TITLE
Trace ID configuration experimental feature

### DISCUSSION THREAD

**Discussion by bnjjj** [apollographql/router#2147] [Experimental]
This is the discussion related to the experimental feature introduced [here](https://github.com/apollographql/router/pull/2131).

It's all about how to configure the way we can import and export the trace id.
As it's an experimental feature this discussion is opened to gather feedback from the community. Feel free to give your opinions.

Current configuration:

```yaml
telemetry:
  tracing:
    experimental_response_trace_id:
      enabled: true # default: false
      header_name: "my-trace-id" # default: "apollo-trace-id"
    propagation:
      from_request_header: "x-request-id"
      jaeger: true
```
