### DISCUSSION TITLE
Need some help with tracing. The router is not generating any trace id, and i am not able to publish traces to jaeger either.

### DISCUSSION THREAD

**Discussion by vamshiaruru-virgodesigns** [apollographql/router#2222] [Q&A] [answered]
Hi all, really need some help with tracing. I am moving from federation to router, and in federation Instrumentation took care of generating trace ids and propagating them. But in the router, I am not able to see any trace ids or publish traces to jaeger. Here's my config

```yaml
supergraph:
  listen: 0.0.0.0:4006
  path: /graphql
  introspection: true

csrf:
  unsafe_disabled: true

sandbox:
  enabled: true

homepage:
  enabled: false

cors:
  match_origins:
    - ".*"
  allow_credentials: true

headers:
  all:
    request:
      - propagate:
          matching: .*

include_subgraph_errors:
  all: true # Propagate errors from all subraphs

traffic_shaping:
  deduplicate_variables: true
  router:
    timeout: 180s
  all:
    deduplicate_query: true
    timeout: 180s

plugins:
  ameyam.logger:
  ameyam.authentication:

telemetry:
  tracing:
    propagation:
      trace_context: true
    trace_config:
      service_name: ameyam_graphql_gateway
      sampler: always_on
    otlp:
      endpoint: default
    jaeger:
      collector:
        endpoint: http://localhost:14268

```
I have  `jaeger-all-in-one` docker container up. I made a bunch of requests, and I couldn't see any traces in the jaeger UI.

I also inspected the headers that were being sent to my subgraphs, and I couldn't see open telemetry related headers anywhere.  This is a big blocker for me to shift to router. We use trace ID to associate request in different subgraphs together (our subgraphs can read trace id from headers and append them to logs). Am I doing something wrong here? Any help is really appreciated! Thanks.

**Comment by vamshiaruru-virgodesigns** [comment, marked as answer]
I have tried inspecting trace ID using 
```
                let trace = TraceId::maybe_new().map(|t| t.to_string());
```
But the trace is None :(

**Reply by bnjjj** [reply]
Few questions, which version of the router do you use ? Where did you write this line `let trace = TraceId::maybe_new().map(|t| t.to_string());` ? I see in your configuration you're using `trace_context` propagation, is it the specs you're using to propagate spans to your subgraph ? No the `jaeger` one ?
Also could you use the jaeger `agent` configuration instead of `collector` ?
Example
```yaml
jaeger:
  agent:
    endpoint: "default"
```

**Reply by vamshiaruru-virgodesigns** [reply]
Thanks for the response. I have a plugin like this:
```rust
fn subgraph_service(&self, _name: &str, service: subgraph::BoxService) -> subgraph::BoxService {
        ServiceBuilder::new()
            .map_request(|req: subgraph::Request| {
                let headers = req.subgraph_request.headers();
                info!("Headers being sent from gateway: {headers:?}");
                let trace = TraceId::maybe_new().map(|t| t.to_string());
                info!("Trace ID: {trace:?} ***********"); // Here in subgraph service
                req
            })
            .service(service)
            .boxed()
    }

    fn supergraph_service(&self, service: supergraph::BoxService) -> supergraph::BoxService {
        ServiceBuilder::new()
            .map_request(|mut req: supergraph::Request| {
                let body = req.supergraph_request.body();
                if body.operation_name == Some("IntrospectionQuery".to_string()) {
                    return req;
                }
                let print = get_graphql_fingerprint(body);
                let trace = TraceId::maybe_new().map(|t| t.to_string());
                info!("Trace ID: {trace:?} ***********"); // Here in  supergraph
                info!("Processing request: {body:?}, Graphql Fingerprint: {print}");
                req.context
                    .insert("start_time", get_time_millis())
                    .unwrap_or_default();
                req.context
                    .insert("fingerprint", print.clone())
                    .unwrap_or_default();
                req.supergraph_request
                    .headers_mut()
                    .insert("X-Graphql-Fingerprint", print.parse().unwrap());
                req
            })
            .map_response(|res: supergraph::Response| {
                if let Ok(Some(start_time)) = res.context.get::<_, i64>("start_time") {
                    let fingerprint = res
                        .context
                        .get::<_, String>("fingerprint")
                        .unwrap_or_else(|_| Some("UNKNOWN".to_string()))
                        .unwrap_or_default();
                    tracing::info!(
                        "Processed request with fingerprint: {} in {} milli seconds",
                        fingerprint,
                        get_time_millis() - start_time
                    );
                }
                res
            })
            .service(service)
            .boxed()
    }
```
So I am printing trace id in supergraph and subgraph services. In both the places it comes as None.
I have tried using jaeger agent default as well, no luck with the traces there either. 
I am using the latest apollo router version of 1.5.0, here it is in my Cargo.toml
```
apollo-router = "1.5.0"
```
I was on 1.4.0 before, upgraded just today to check if tracing works with the new version.

```
 I see in your configuration you're using trace_context propagation, is it the specs you're using to propagate spans to your subgraph ?
```
I thought using propagate trace context would propagate trace id to the subgraphs, but I am not completely sure what it does. I am more concerned about propagating otel related headers to my subgraphs more than pushing traces to jaeger at the moment because that is a blocker for us, so I was messing with all possible combinations. 

In the latest version, I have tried using this as well
```
    experimental_response_trace_id:
      enabled: true
      header_name: "apollo-trace-id"
 ```
 But I could not see the header in response.
 Thanks for the help :)

**Reply by bnjjj** [reply]
Ok then FYI if you look here in our docs about tracing propagation https://www.apollographql.com/docs/router/configuration/tracing#propagation you'll see we put some comments above each different fields, because it's explaining the specs for trace propagation, there is multiple ones. Do you know what kind of headers your subgraphs expect ? 

When you're saying `But I could not see the header in response.`.
Which response are you talking ? The router response ? Subgraph response ?

Because if you want to expose the trace_id in the router response it is in fact the right configuration with `experimental_response_trace_id`.

Other question, when you're doing a `docker ps` are you able to see you're exposing the ports also on your host ? For example here is the result for me

```
c48f6bf68531   jaegertracing/all-in-one:latest   "/go/bin/all-in-one-…"   6 weeks ago   Up 2 hours   5778/tcp, 0.0.0.0:14268->14268/tcp, :::14268->14268/tcp, 5775/udp, 14250/tcp, 0.0.0.0:6831-6832->6831-6832/udp, :::6831-6832->6831-6832/udp, 0.0.0.0:16686->16686/tcp, :::16686->16686/tcp   router-jaeger-1
```

**Reply by vamshiaruru-virgodesigns** [reply]
Here's my docker ps response:
```
CONTAINER ID   IMAGE                           COMMAND                  CREATED        STATUS        PORTS                                                                                                                                                                                                                    NAMES
d4ca4c188bd2   jaegertracing/all-in-one:1.39   "/go/bin/all-in-one-…"   30 hours ago   Up 30 hours   0.0.0.0:4317-4318->4317-4318/tcp, 0.0.0.0:5778->5778/tcp, 0.0.0.0:9411->9411/tcp, 0.0.0.0:14250->14250/tcp, 0.0.0.0:14268-14269->14268-14269/tcp, 0.0.0.0:16686->16686/tcp, 5775/udp, 0.0.0.0:6831-6832->6831-6832/udp   jaeger
```
So ports are exposed I think. 

I read the documentation, but I missed the comment above each of the propagator fields. So, some of our subgraphs expect `uber-trace-id` used by Jeager, and some expect the opentelemetry trace id headers like `otelparent` etc. For reference, here are the headers the federated gateway used to send:
```
{
'apollo-federation-include-trace': 'ftv1', 
'uber-trace-id': '811fc3346fc84c563c8acba49e1c2b9a:cb2d3412707be04b:0:01', 
'traceparent': '00-811fc3346fc84c563c8acba49e1c2b9a-cb2d3412707be04b-01'
}
```
So to not break the existing logging tools we have, it would be great if router can send the same headers as well.  (For the sake of experimentation, I set `true` for all the propagate keys. I still don't see any of the above headers being sent from the router :( )

```
Which response are you talking ? The router response ? Subgraph response ?
```
The router response, yes. I just wanted to see if the router was generating any trace ID at all.

**Reply by bnjjj** [reply]
Hmm I suspect something weird happens because of these 2 empty sections in your yaml file:
```yaml
plugins:
  ameyam.logger:
  ameyam.authentication:
```

Could you delete them (the entire `plugins` section) for now and retry ? I suspect it does weird things
