### DISCUSSION TITLE
Retry for subgraph requests

### DISCUSSION THREAD

**Discussion by bnjjj** [apollographql/router#2241] [Experimental]
Related to https://github.com/apollographql/router/issues/338 and https://github.com/apollographql/router/pull/2006 .

I implements the retry on subgraph requests. Here is an example of configuration:

```yaml
traffic_shaping:
  all:
    experimental_retry:
      min_per_sec: 10
      ttl: 10s
      retry_percent: 0.2
  subgraphs:
    accounts:
      experimental_retry:
        min_per_sec: 20
``` 

Still as an experimental feature because we don't know if it's the right configuration shape. Feel free to give your opinions in this discussion.
