### DISCUSSION TITLE
can apollo router can be configured with server certificates and terminate ssl ?

### DISCUSSION THREAD

**Discussion by arunarivarasan** [apollographql/router#2314] [General]
can apollo router be configured with server certificates and terminate ssl. i want to expose the federated endpoint in https.

**Comment by Geal** [comment]
it is not possible right now, you need to add a reverse proxy in front of the router for TLS

**Comment by oleshkooo** [comment]
I switched the router from `http` to `https` as follows:

1. Generated a self-signed certificate using openssl.

2. Changed the configuration of the router:
```yaml
tls:
  supergraph:
    # The path to the certificate: ./ssl/certificate.pem. Do not remove the extra dot before
    certificate: &certificate ${file../ssl/certificate.pem}
    certificate_chain: *certificate
    key: ${file../ssl/key.pem}
```

Link to the Apollo Router documentation: https://www.apollographql.com/docs/router/configuration/overview/#tls
