### DISCUSSION TITLE
sending access token on NextAuth cookie

### DISCUSSION THREAD

**Discussion by killjoy2013** [apollographql/router#2686] [Q&A]
My router.yaml is;

```yaml
authentication:
  experimental:
    jwt:
      jwks_urls:
        - http://localhost:3100/.well-known/jwks.json
      header_name: Authorization
      header_value_prefix: Bearer
      cooldown: 15s
```

However, NextAuth keeps the access token in a cookie with the name `next-auth.session-token`.
Is it possible to configure router.yaml to support both Authorization header & cookie?

Would it be possible to use Rhai scripts to get access token from the cookie and add it as the Bearer token to authorization header?
What would be the most suitable approach in this case?
