### DISCUSSION TITLE
Do 4xx errors not log to Apollo Router by default?

### DISCUSSION THREAD

**Discussion by osamra-rbi** [apollographql/router#2877] [General]
Hi there!

Just wondering, do 4xx errors not log to Apollo Router by default when the log level is set to info? For example an INVALID_GRAPHQL_REQUEST, would this be in the console/logs?

**Comment by bnjjj** [comment]
No but you can enable it by reading [this documentation](https://www.apollographql.com/docs/router/configuration/logging#basic-configuration)

**Reply by osamra-rbi** [reply]
Wouldn't this be for request headers though? I'm looking to log errors with a status code of 400, this seems to mean I need a request header, unless I am misunderstanding.

I was under the impression based on [this issue](https://github.com/apollographql/router/issues/2687), that these type of errors would log (not subgraph 200 errors but actual 4xx 5xx etc error responses)

**Reply by bnjjj** [reply]
By default no, for now the only option we have to enable logging for subgraph is by using the configuration I sent. And this configuration lets you enable logging for subgraph requests and responses but not only errors, it's everything. But we will improve this behavior regarding the feedback we received [there](https://github.com/apollographql/router/discussions/1961).

Here is the configuration I'm using when I want to debug and see logs on every requests:
```
telemetry:
  experimental_logging:
    format: pretty
    display_filename: true
    display_line_number: true
    when_header:
      - name: "origin"
        match: ".*"
        headers: true
        body: true
```
