### DISCUSSION TITLE
GraphOS Enterprise: operation limits preview feature

### DISCUSSION THREAD

**Discussion by lrlna** [apollographql/router#3040] [Preview]
You can define **operation limits** in your router's configuration to reject potentially malicious requests. An operation that exceeds _any_ specified limit is rejected (unless you run in `warn_only` mode). 

This feature is in preview, and we welcome your feedback.

To use operation limits, you must run v1.17 or later of the Apollo Router.

You define operation limits in your router's YAML config file, like so:

```yaml title="router.yaml"
preview_operation_limits:
  max_depth: 100
  max_height: 200
  max_aliases: 30
  max_root_fields: 20
    
  # Uncomment to enable warn_only mode
  # warn_only: true
```

[Docs](https://www.apollographql.com/docs/router/configuration/operation-limits) | [Changelog](https://github.com/apollographql/router/releases/tag/v1.17.0)
