### DISCUSSION TITLE
How to forward headers & request to subgraph and to another subgraph

### DISCUSSION THREAD

**Discussion by iSreekanth** [apollographql/router#3179] [Q&A]
Hello Everyone,

We are new to GraphQL language and currently implementing a middleware layer with apollo studio.

Currently, we have two subgraphs (Cart & Product) and one supergraph (router gateway).

And the use case is,

To get the user cart, the front-end team must pass the token in the authorization header along with some request parameters (ex: locale, Currency code). So that the cart subgraph can use them to get his/her basket and then get the product entity from Product Subgraph.

in cart.graphql, we have added Product Entity

`extend type Product @key(fields: "id") {
  id: ID! @external
}`

And our config.yaml file is

```
cors:
  origins:
    - http://localhost:3000 # Allows any locally-running client to run against your Router
    - https://studio.apollographql.com # Allows Apollo Studio to still run queries against your Router
federation_version: =2.3.2
subgraphs:
  cart:
    routing_url: http://localhost:4002
    schema:
      file: ../subgraph-cart/cart.graphql
  products:
    routing_url: http://localhost:4001
    schema:
      file: ../subgraph-products/products.graphql
headers:
  subgraphs:
    cart:
      request:
        - propagate:
            matching: ".*"
```

But we are facing two issues here,

- Not getting the authorization header value to the cart subgraph. We are calling cart query from the Router server (http://127.0.0.1:4000/)
- Request is not getting forwarded to Product Subgraph. This means we are not getting either the authorization header or request parameters.

Could you please suggest to us?

Thanks,
Sreekanth

**Comment by garypen** [comment]
I'm not sure why your headers aren't being propagated to the cart subgraph. It may be because you have quoted your matching pattern. I don't think that is valid syntax.

Your request may not result in a fetch from products, but if it does, then it won't receive any forwarded headers, because you have only configured forwarding to your `cart` subgraph. If you want all headers to be forwarded to all subgraphs, use the `all` syntax in your configuration.

We have a number of [examples of how to configure this](https://www.apollographql.com/docs/router/configuration/header-propagation/).

Here's how to propagate all headers to all subgraphs:
```
headers:
  all: # Header rules for all subgraphs
    request:
      - propagate:
          matching: .*
```

**Comment by iSreekanth** [comment]
Thanks for your reply.

We have even tried with `all` and removing the quotes from the matching pattern too. But still, the headers are not getting forwarded.

```
headers:
  all: # Header rules for all subgraphs
    request:
      - propagate:
          matching: .*
```

I mean, from router, the request is only coming to the `cart` subgraph but not getting forwarded to the `product` subgraph.

Here is our folder structure,

![Image 30-05-2023 at 14 55](https://github.com/apollographql/router/assets/95233740/aedbfe0f-1cf5-434f-bb0c-187e634def3b)


And we are using the below commands to start the router server

```
rover supergraph compose --config ./config.yaml --output supergraph.graphql
./router --dev --supergraph supergraph.graphql
```

And, another query, do we need to execute these two commands every time we change config.yaml file?

Thanks,
Sreekanth
