### DISCUSSION TITLE
Config yaml: where we're heading

### DISCUSSION THREAD

**Discussion by BrynCooke** [apollographql/router#405] [Implementation]
The tower branch currently has the following YAML format:

```yaml
server:
  listen: 1.2.3.4:5
  cors:
    origins: [foo, bar, baz]
    methods: [foo, bar]

subgraphs:
  example:
    layers: 
    - kind: header_propagation # There can be multiple instances of a layer
      header_name: "foo"

plugins:
  opentelemetry: # There can be only one instance of a plugin of a particular name
    some_config: "foo"
 ```

The restriction around plugin instance is only in the config format. The plugin registry allows for any number of instances to be created, but should we allow this?

Some things to discuss:
* What does WASM/Deno config look like?
* How can we support multiple service implementations/configuration? e.g. Rest

**Comment by BrynCooke** [comment]
Proposed format with WASM plugin/layers:

```yaml
subgraphs:
  example:
    layers: 
       - kind: wasm # There can be multiple instances of a layer. But users should be encouraged to use this layer only once if possible.
         files:
          - "layer_1.js"
          - "layer_2.js"         

plugins:
  wasm: # There can be only one instance of a plugin of a particular name
    files:
    - "plugin_1.js"
    - "plugin_2.js"
```
In this format we don't allow embedding of code in the config because:
1. Although embedding code in the config seems nice it will quickly become unwieldy.
2. Having a single plugin/layer that delegates to multiple WASM files prevents us from having to cross the Rust->WASM boundary many times. 


There is no escaping that if the user has a WASM plugin and a WASM layer then the cost of crossing from Rust to WASM will be incurred twice. There may be other layers that are non-wasm between the plugin and layer so this is unavoidable without making the ordering of layer execution opaque to the user.

**Comment by BrynCooke** [comment]
Proposed format with custom service:
```yaml
subgraphs:
  example:
    service:
      kind: rest
      mapping: "foo"
```

Basically the same as our current layer stuff.
Defaults to `remote_http` is no subgraph service is defined.

**Comment by BrynCooke** [comment]
Proposed format header manipulation layer:
```yaml
subgraphs:
  example:
    layers: 
       - kind: headers # There can be multiple instances of a layer. But users should be encouraged to use this layer only once if possible.
         delete: "foo"
         forward: 
            from: "foo"
            to: "bar"
            default: "bif"
         insert:
            name: "foo"
            value: "bar"
```

This would change the demonstration propagate headers layer to accept multiple operations and would reduce but not eliminate the need to box as the user will only be using one layer.
