### DISCUSSION TITLE
Can Router works with local routing_url?

### DISCUSSION THREAD

**Discussion by michaeldouglasdev** [apollographql/router#4863] [General]
Is it possible to use local routing_url with Apollo Router instead of Apollo Gateway?

In my project I have some local subgraphs (local schema and resolvers)

ex:

```
supergraph.yaml:

federation_version: =2.6.0
subgraphs:
  users:
    routing_url: http://users
    schema:
      file: ./src/subgraph-users/schema.graphql
```

```
const gateway = new ApolloGateway({
    supergraphSdl: readFileSync("./supergraph.graphql", "utf8"),
    buildService: ({ url }) => {
      if (url === 'http://users') {
        return new LocalGraphQLDataSource(usersSubgraph);
      }
      else {
        return new RemoteGraphQLDataSource({url})
      }
    }
  })
```
