### DISCUSSION TITLE
Query planner pool

### DISCUSSION THREAD

**Discussion by o0Ignition0o** [apollographql/router#4917] [Experimental]
This is the place to discuss the experimental query planner pool feature [seen in the documentation here](https://www.apollographql.com/docs/router/configuration/overview/#query-planner-pools), added in #4897.

Here we will be able to compare benchmarks, tuning, and listen to feedback.

You can configure query planner pools with the `supergraph.query_planner.experimental_available_parallelism` option:

```yaml
supergraph:
  query_planner:
    experimental_available_parallelism: auto # number of available cpus
```

Its value is the number of query planners that run in parallel, and its default value is `1`. You can set it to the special value `auto` to automatically set it equal to the number of available CPUs.
