### DISCUSSION TITLE
How to terminate TLS to subgraphs

### DISCUSSION THREAD

**Discussion by sathishece170** [apollographql/router#5338] [Q&A]
Hello,

Is there a way to terminate the TLS at router to all subgraphs? I see a documentation about enabling/configuring them but nothing about termination.

Can we configure something like this?

```
tls:    
   subgraph:    
       all:    
          enabled: false
```
