### ISSUE TITLE
Jaeger agent endpoint should be a URL, not a SocketAddr

### ISSUE THREAD

**Issue by Geal** [apollographql/router#1016]
if I try to run the router and jaeger in containers, and use the jaeger container's name in endpoint configuration as follows:

```yaml
server:
  listen: 0.0.0.0:4000
  cors:
    origins:
      - https://studio.apollographql.com/

telemetry:
  tracing:
    trace_config:
      service_name: router
    jaeger:
      agent:
        endpoint: jaeger:14268
    propagation:
      jaeger: true
```

The router will fail to start with those messages:
```json
 {"timestamp":"2022-05-11T12:53:43.969404Z","level":"INFO","fields":{"message":"starting Apollo Router"},"target":"apollo_router"}
 {"timestamp":"2022-05-11T12:53:43.970147Z","level":"ERROR","fields":{"message":"plugin apollo.telemetry could not be configured: data did not match any variant of untagged enum AgentEndpoint"},"target":"apollo_router::router_factory"}
 {"timestamp":"2022-05-11T12:53:43.970180Z","level":"ERROR","fields":{"message":"cannot create the router: plugin apollo.telemetry could not be configured: data did not match any variant of untagged enum AgentEndpoint"},"target":"apollo_router::state_machine"}
 {"timestamp":"2022-05-11T12:53:43.970200Z","level":"INFO","fields":{"message":"stopped with error"},"target":"apollo_router"}
 {"timestamp":"2022-05-11T12:53:43.970214Z","level":"ERROR","fields":{"message":"could not create the HTTP pipeline: plugin apollo.telemetry could not be configured: data did not match any variant of untagged enum AgentEndpoint"},"target":"apollo_router::executable"}
"could not create the HTTP pipeline: plugin apollo.telemetry could not be configured: data did not match any variant of untagged enum AgentEndpoint"
```

relevant code: https://github.com/apollographql/router/blob/41302216de95cb006fc5ab73df1c4702cd5e8c0c/apollo-router/src/plugins/telemetry/tracing/jaeger.rs#L50-L73

We should update it to accept either "default", a URL or a `host:port` string, as is done with Datadog:

https://github.com/apollographql/router/blob/41302216de95cb006fc5ab73df1c4702cd5e8c0c/apollo-router/src/plugins/telemetry/tracing/datadog.rs#L10-L48
