### ISSUE TITLE
How to disable Apollo Sandbox in production environment?

### ISSUE THREAD

**Issue by gordancso** [apollographql/router#1022]
Is there a configuration option to disable the Apollo sandbox in PROD environment? As I know there are options for landing page and introspection available in the config file.

**Comment by Geal** [comment]
You can use those options yes:

```yaml
server:
  introspection: false
  landing: false
```
