### ISSUE TITLE
Customisable prometheus metrics

### ISSUE THREAD

**Issue by as-nikolaym** [apollographql/router#1112]
**Is your feature request related to a problem? Please describe.**
- The currently exposed prometheus metrics do not have all the info I need.
  - This concerns the following metrics:
    - `http_request_duration_seconds` histogram
    - `http_requests_total` counter
    - `http_requests_error_total` counter
  - Most importantly, I wish to have _operation name_ included in them.
  - I wish to be able to inject additional values as labels to the metrics. These could be static values or ones coming from headers. For example our FE client may report its version to router via an HTTP header, and that version could be included in the metrics. On the other hand, I may also want to inject a value that outsiders cannot modify in any way (such as, by passing headers).
- The `http_request_duration_seconds` histogram does not have as much precision as I need.
  - Looks like anything taking more than 1s is classified as `+Inf`.
  - Looks like there are only 4 buckets: `0.5`, `0.9`, `0.99`, `+Inf`.

**Describe the solution you'd like**
- The [prometheus configuration](https://www.apollographql.com/docs/router/configuration/metrics/#using-prometheus) of router could have an additional option `include_operation_names`, defaulting to `false` (perhaps not everyone needs operation name in their metrics).
  - Setting it to `true` would automatically include the GQL operation names to the `http_request_duration_seconds`, `http_requests_total`, and `http_requests_error_total` metrics.
- The prometheus configuration would have additional options of including static values or HTTP header values as metric labels. Example syntax:
```
telemetry:
  metrics:
    prometheus:
      enabled: true
      additional_metric_labels:
        # this is similar to header propagation syntax https://www.apollographql.com/docs/router/configuration/header-propagation/#propagate
        - propagate_header:
            # header name
            named: "x-user-id"
            # optional default value if header is not set
            default: "abc123"
            # optional name of the metric label. If not specified, it could be the header name itself (may need some sanitization/transformation)
            rename: "account-id"
        # this is similar to header insert syntax https://www.apollographql.com/docs/router/configuration/header-propagation/#insert
        # but it does not deal with headers in this case
        - insert:
            name: "sent-from-our-apollo-router"
            value: "indeed"
```

- The `http_request_duration_seconds` histogram could be made configurable, example syntax:
```
telemetry:
  metrics:
    prometheus:
      enabled: true
      http_request_duration_seconds:
        # defaults to 4 (probably)
        buckets: 10
        # value in seconds, could be float. Defaults to 1 (probably)
        tolerated_request_duration_seconds: 5
```

**Describe alternatives you've considered**
These could perhaps be handled with additional native Rust plugins or Rhai scripts, instead of directly configuring router. If that path is chosen, it would be good to get ready examples of how to achieve the needed results.

**Additional context**
N/A
