### ISSUE TITLE
Datadog namespace not set

### ISSUE THREAD

**Issue by krisztian-sala** [apollographql/router#1162]
I have set the Datadog namespace both with the DD_ENV environment variable (which works for other services) and also from the router configuration like so:
```yaml
...
      tracing:
        trace_config:
          service_name: "${DD_SERVICE:apollo-router}"
          service_namespace: "${DD_ENV:my-namespace}"
```
But the namespace is still set as `none`

How can I set it correctly?

**Comment by krisztian-sala** [comment]
I think I explained it wrong. So I don't actually know what the `service_namespace` variable's value is, I'm using the v0.9.2 version, so no custom build.
The router is running in Kubernetes and what I'm trying to achieve is to set the Kubernetes namespace that the router is part of as the `env` variable in Datadog.

Currently, whatever I do, the `env` is `none`
![image](https://user-images.githubusercontent.com/88720831/170501424-bc31578b-f88c-496c-9f58-89fe2237edcd.png)

I thought that the `service_namespace` sets that value. But I also tried by setting a custom trace attribute like so:
```yaml
telemetry:
  tracing:
    trace_config:
      service_name: "${DD_SERVICE:apollo-router}"
      service_namespace: "${DD_ENV:my-namespace}"
      sampler: 1
      attributes: 
        env: "${DD_ENV:my-namespace}"
```

**Comment by bnjjj** [comment]
Apparently we're using `service_namespace` and pass it to attributes named with `service.namespace` (https://github.com/apollographql/router/blob/main/apollo-router/src/plugins/telemetry/config.rs#L224) . Therefore on your traces you should have an attribute named `service.namespace` with the value you're looking for. Let me know if it helps

**Comment by krisztian-sala** [comment]
Unfortunately I don't see that attribute or any other that I set in `telemetry.tracing.trace_config.attributes` appear in my trace. The only attributes that show up in Datadog are these:

![Screenshot 2022-05-30 at 11-51-17 APM Traces Datadog](https://user-images.githubusercontent.com/88720831/170956219-b91b802e-c1d7-448d-9720-f31b4b793700.png)

**Comment by krisztian-sala** [comment]
Any news about this? Not having proper monitoring is a blocker for us to go to production with the router.

It doesn't send any custom attribute to Datadog. But the most important would be the `env`, which is currently `none` in all cases.

**Comment by BrynCooke** [comment]
We've settled on the following which should be consistent with the rest of our config:

```yaml
telemetry:
  tracing: 
    common:
      resource:      
      attributes:
        router:
          static:
            - name: "version"
              value: "v1.0.0"
          request:
            - header:
                named: "content-type"
                rename: "payload_type"
                default: "application/json"
            - header:
                named: "x-custom-header-to-add"
          response:
            - body:
                path: errors.extensions.status
                name: extended_status
                default: optional_default_value
          context:
            - named: "foo"
          
        subgraph:
          all:
            static:
              - name: "version"
                value: "v1.0.0"
              request:
                - header:
                    named: "content-type"
                    rename: "payload_type"
                    default: "application/json"
                - header:
                    named: "x-custom-header-to-add"
              response:
                - body:
                    path: errors.extensions.status
                    name: extended_status
                    default: optional_default_value
              context:
                - named: "foo"
          subgraphs:
            products:
              static:
                - name: "version"
                  value: "v1.0.0"
                request:
                  - header:
                      named: "content-type"
                      rename: "payload_type"
                      default: "application/json"
                  - header:
                      named: "x-custom-header-to-add"
                response:
                  - body:
                      path: errors.extensions.status
                      name: extended_status
                      default: optional_default_value
                context:
                  - named: "foo"
```
