### ISSUE TITLE
Router doesn't accept IP in telemetry.tracing.otlp.endpoint

### ISSUE THREAD

**Issue by Mithras** [apollographql/router#1339]
**Describe the bug**
```
telemetry:
  tracing:
    otlp:
      endpoint: 127.0.0.1:4317
```
result in `ERROR apollo_router::executable: could not create the HTTP pipeline: plugin apollo.telemetry could not be configured: relative URL without a base  
could not create the HTTP pipeline: plugin apollo.telemetry could not be configured: relative URL without a base`
