### ISSUE TITLE
show exact error when subgraphs files

### ISSUE THREAD

**Issue by oerhahon** [apollographql/router#1382]
**Describe the bug**
When the subgraph returns a text type instead of JSON because of an error, the error returned from the router looks like this:

```
{
  "message": "HTTP fetch failed from 'simulations': HTTP fetch failed from 'simulations': subgraph didn't return JSON (expected content-type: application/json or content-type: application/graphql+json; found content-type: \"text/html; charset=utf-8\")",
  "locations": [],
  "path": [],
  "extensions": {
    "type": "SubrequestHttpError",
    "service": "simulations",
    "reason": "HTTP fetch failed from 'simulations': subgraph didn't return JSON (expected content-type: application/json or content-type: application/graphql+json; found content-type: \"text/html; charset=utf-8\")"
  }
}
```

This doesn't show the error that occurred in the subgraph. After debugging the subgraph, I realized this was the actual error:

`Error: http://localhost:3000 not permitted by CORS policy. at origin (/usr/src/app/dist/app/graphql/server.js:96:30)` 

However, it looks like this issue was addressed here: [#1183](https://github.com/apollographql/router/issues/1183), is there something missing in my configuration?

router configuration:

```
server:
  # The socket address and port to listen on
  listen: 0.0.0.0:4000
  introspection: false
  landing_page: false
  cors:
    origins: 
      - http://localhost:3000
      - https://studio.apollographql.com
    allow_credentials: true

headers:
  all:
  - propagate:
      matching: .*

traffic_shaping:
  variables_deduplication: true
  all:
    query_deduplication: true
    compression: gzip

plugins:
  experimental.include_subgraph_errors:
    all: true 
```
the is the CORS configuration in the subgraph:

```
server.applyMiddleware({
    app,
    cors: {
      credentials: true,
      origin: function (origin, callback) {
        if (!origin || global.configuration.ALLOWED_CORS.includes(origin)) {
          callback(null, true)
        } else {
          callback(new Error(`${origin} not permitted by CORS policy.`))
        }
      }
    },
    path: '/graphql'
  })
```
