### ISSUE TITLE
Requesting non-nullable array field twice returns nothing

### ISSUE THREAD

**Issue by KennethWussmann** [apollographql/router#1406]
**Describe the bug**
Requesting an `[Enum!]!` field twice in the same query will return nothing.

**To Reproduce**
1. Setup service providing schema:
```GraphQL
type Query {
	users: [User!]!
}
enum Role {
	ADMIN
	USER
}
type User {
	id: ID!
	roles: [Role!]!
}
```
2. Submit request:
```GraphQL
{
	users {
		roles
		roles
	}
}
```
4. Returns
```JSON
{
	"data": null
}
```
No error messages in the logs.

What works:
```GraphQL
{
	users {
		id
		id
	}
}
```
Which will return the `id` at least once.

**Expected behavior**
Whether or not this makes sense remains to be seen, but the two cases should at least behave in the same way. I'd expect to `roles` return from the API once, this is how the Node federation-gateway worked before as well.

This came to our attention, because a field was included via another fragment and the root query. But it's not an issue exclusive to fragments.

**Desktop:**
 - OS: Debian Bullseye
 - Version: 0.11.0
 - Federation v2

**Comment by o0Ignition0o** [comment]
Hi, thanks for raising this issue!

Are you running the router with [query and/or variable deduplication](https://www.apollographql.com/docs/router/configuration/traffic-shaping#configuration) ?

I’ll try to reproduce it

**Comment by KennethWussmann** [comment]
Thank you for looking further into this issue.

> Are you running the router with [query and/or variable deduplication](https://www.apollographql.com/docs/router/configuration/traffic-shaping#configuration) ?

Actually we weren't aware of these settings. Hence we have not configured anything custom in that direction. Here is our entire config:

```YAML
headers:
  all:
    - propagate:
        named: 'authorization'
telemetry:
  metrics:
    prometheus:
      enabled: true
server:
  endpoint: /graphql
  listen: 0.0.0.0:4000
  cors:
    allow_any_origin: true
plugins:
  experimental.include_subgraph_errors:
    all: true
```
