### ISSUE TITLE
Add error section in custom attributes configuration

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#1434]
What is missing in our implementation for custom attributes and could be useful is to add an `error` subsection to reflect the same behavior we have in our plugin hooks. For example instead of having:

```yaml
telemetry:
  metrics:
    prometheus:
      enabled: true
    common:
      attributes:
        subgraph:
          all:
            response:
              body:
              - path: .errors[0].extensions.type
                name: subgraph_error_extended_type
```

we could have :

```yaml
telemetry:
  metrics:
    prometheus:
      enabled: true
    common:
      attributes:
        subgraph:
          all:
            errors: # Only works if it's a valid GraphQL error
              include_messages: true # Will include the error message in a message attribute
              include_locations: true
              include_paths: true
              extensions: # Include extension data
                - name: subgraph_error_extended_type # Name of the attribute
                  path: .type # JSON query path to fetch data from extensions
```

_Originally posted by @bnjjj in https://github.com/apollographql/router/issues/1198#issuecomment-1194067624_

**Comment by BrynCooke** [comment]
Q: Will the user be able to specify more than one error section? If not then `error`->`errors`.

Is there a possibility that users will want to filter only on certain paths of error. Not saying that this is a requirement, just posing the question.

**Comment by bnjjj** [comment]
No only one error. It's already written `error` BTW. About the filtering on specific path we could provide a path `/here/is/my/path` instead of just provide a `bool`. That could be a feature

**Comment by BrynCooke** [comment]
So if there's only one `error` section, then it should be called `errors` as it applies to many errors.
`include_message` and `include_path` should also be plural.

**Comment by bnjjj** [comment]
Updated ! Thanks :)

**Comment by BrynCooke** [comment]
just checking: extensions is an array? If so the example yaml needs a dash.

**Comment by bnjjj** [comment]
Ok after some investigations we don't fill the path and locations field when we have an error in the subgraph http request. So for now I will omit these fields and do not add the ability to include them.
Final version:

```yaml
telemetry:
  metrics:
    prometheus:
      enabled: true
    common:
      attributes:
        subgraph:
          all:
            errors: # Only works if it's a valid GraphQL error
              include_messages: true # Will include the error message in a message attribute
              extensions: # Include extension data
                - name: subgraph_error_extended_type # Name of the attribute
                  path: .type # JSON query path to fetch data from extensions
```
