### ISSUE TITLE
router.yaml origins not working

### ISSUE THREAD

**Issue by stumpykilo** [apollographql/router#1448]
We are looking to migrate from Apollo Gateway to Apollo Router but are running into an issue with the accepted origins setting in our `router.yaml`. We have copied this yaml from your documentation from this page (https://www.apollographql.com/docs/router/configuration/cors) and set the `allow_any_origin` to false:
```
server:
  cors:

    # Set to true to allow any origin
    # (Defaults to false)
    allow_any_origin: false

    # List of accepted origins
    # (Ignored if allow_any_origin is true)
    # (Defaults to the Apollo Studio url: `https://studio.apollographql.com`)
    origins:
      - https://www.your-app.example.com/
      - https://studio.apollographql.com/ # Keep this so Apollo Studio can run queries against your router
```

We are not able to run any queries against our router (http://localhost:4000) from `https://studio.apollographql.com/` unless we turn the `allow_any_origin` to `true`. We get a response like this:
![image](https://user-images.githubusercontent.com/10451161/181854030-77b9c6ae-a37c-43bf-a507-7eb2d02479d9.png)

Please help us resolve this issue because it is blocking us from moving forward with our migration.
