### ISSUE TITLE
CORS issues again

### ISSUE THREAD

**Issue by krisztian-sala** [apollographql/router#1460]
Upgrading to version v0.14.0 caused us CORS issues with the following config:
```yaml
      cors:
        allow_any_origin: true
        methods: [ GET, POST, OPTIONS, PUT, DELETE ]
```
Version v0.11.0 works well, so it could be related to the new CORS changes.

**Comment by o0Ignition0o** [comment]
Hey!

Thanks for opening the issue,

Can you please show me a request / response with the headers you expect and the headers you actually get?
I'm particularly interested in the kind of [access-control-request-headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers) you are sending, and if they match the default headers that are being set.

Looking at the configuration you just provided, I would try to run the router with this:

```yaml
      cors:
        allow_any_origin: true
        methods: [ GET, POST, OPTIONS, PUT, DELETE ]
        allow_any_header: true
```
