### ISSUE TITLE
Not working within proxy configuration

### ISSUE THREAD

**Issue by stumpykilo** [apollographql/router#1477]
**Describe the bug**
We have an issue when we use Apollo Router with webpack devserver's [proxy](https://webpack.js.org/configuration/dev-server/#devserverproxy) setting specifically when using it inside a [NX monorepo](https://nx.dev/react-tutorial/06-proxy). It seems to work just fine using Apollo Gateway as the proxy `target` but not with Apollo Router. When using Apollo Router the proxy call returns a `404 Not Found` error.

**To Reproduce**
1. Setup `router.yaml` like this (4200 is the url of app using the proxied `/api` to hit the router):
```
server:
  cors:

    # Set to true to allow any origin
    # (Defaults to false)
    allow_any_origin: false

    # List of accepted origins
    # (Ignored if allow_any_origin is true)
    # (Defaults to the Apollo Studio url: `https://studio.apollographql.com`)
    origins:
      - http://localhost:4200
      - https://studio.apollographql.com # Keep this so Apollo Studio can run queries against your router
```
2. Setup `proxy.conf.json` in an NX app like this:
```
{
  "/api": {
    "target": "http://localhost:4000",
    "secure": false
  }
}
```
3. See error when making a call to `/api`:
```
Request URL: http://localhost:4200/api
Request Method: POST
Status Code: 404 Not Found
Remote Address: 127.0.0.1:4200
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-origin: http://localhost:4200
connection: keep-alive
content-length: 0
date: Mon, 08 Aug 2022 15:26:11 GMT
vary: origin, access-control-request-method, access-control-request-headers
X-Powered-By: Express
accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 983
content-type: application/json
Host: localhost:4200
Origin: http://localhost:4200
Pragma: no-cache
Referer: http://localhost:4200/scenario/4848528/asset-register/editor
sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
```

**Expected behavior**
We expect the call to `/api` to work like it does when using Apollo Gateway as the proxy `target` like this:
```
Request URL: http://localhost:4200/api
Request Method: POST
Status Code: 200 OK
Remote Address: 127.0.0.1:4200
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-origin: *
connection: close
content-length: 45
content-type: application/json; charset=utf-8
date: Mon, 08 Aug 2022 15:29:07 GMT
etag: W/"2d-+Mgz7+PvVjWjwepY76x2e3CRy2o"
X-Powered-By: Express
accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 983
content-type: application/json
Host: localhost:4200
Origin: http://localhost:4200
Pragma: no-cache
Referer: http://localhost:4200/scenario/4848528/asset-register/editor
sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
```

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Gateway Version: ^2.0.5
 - Router Version: 14

**Additional context**
Our Apollo Gateway is running without any special parameters like this:
```
import { ApolloServer } from 'apollo-server';
import { ApolloGateway } from '@apollo/gateway';

const gateway = new ApolloGateway();

(async () => {
  const server = new ApolloServer({ gateway });

  server.listen().then(({ url }) => {
    console.log(`🚀 Server ready at ${url}`);
  });
})();
```
