### ISSUE TITLE
Create custom binary via Github has unclear/broken dependencies

### ISSUE THREAD

**Issue by i-mann** [apollographql/router#1489]
**Describe the bug**
When running a Github action to build a custom router binary, the job fails with a 404/missing dependency.

I've built a custom plugin to deploy with the router that simply authenticates a bearer token; this compiles successfully locally, and `cargo build --release --target x86_64-unknown-linux-gnu` successfully builds a release binary for the target architecture.

**To Reproduce**
* Using Router 0.14.0 (just saw 0.15.0 has been released; this has the same issue)
* Using GitHub action config
```
jobs:
  build-only:
      name: Build only
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: checkout
          uses: actions/checkout@v3
  
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            profile: minimal
            toolchain: 1.61.0
            target: x86_64-unknown-linux-gnu
            override: true
            components: rustfmt
        
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 16
  
        - name: Cache Cargo
          uses: actions/cache@v3
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
  
        - name: Build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --target x86_64-unknown-linux-gnu

```
See error/output below

**Expected behavior**
It builds :sweat_smile: 

**Output**
```
|    Compiling apollo-spaceport v0.14.0 (https://github.com/apollographql/router.git?tag=v0.14.0#9c0864ca)
| The following warnings were emitted during compilation:
| 
| warning: Updating router-bridge
| warning: running `npm ci`
| 
| error: failed to run custom build command for `router-bridge v0.1.0 (https://github.com/apollographql/federation-rs.git?branch=geal/defer#4cdcd574)`
| 
| Caused by:
|   process didn't exit successfully: `/home/imann/code/graphql/target/release/build/router-bridge-5d43838979a9e279/build-script-build` (exit status: 101)
|   --- stdout
|   cargo:rerun-if-changed=js-src
|   cargo:warning=Updating router-bridge
|   cargo:warning=running `npm ci`
| 
|   --- stderr
|   npm ERR! code E404
|   npm ERR! 404 Not Found - GET https://pkg.csb.dev/apollographql/federation/commit/278029dd/@apollo/federation-internals
|   npm ERR! 404 
|   npm ERR! 404  '@apollo/federation-internals@https://pkg.csb.dev/apollographql/federation/commit/278029dd/@apollo/federation-internals' is not in this registry.
|   npm ERR! 404 
|   npm ERR! 404 Note that you can also install from a
|   npm ERR! 404 tarball, folder, http url, or git url.
| 
|   npm ERR! A complete log of this run can be found in:
|   npm ERR!     /root/.npm/_logs/2022-08-09T04_51_31_557Z-debug-0.log
|   thread 'main' panicked at 'assertion failed: Command::new(&npm).current_dir(&current_dir).args(&[\"ci\"]).status().unwrap().success()', /root/.cargo/git/checkouts/federation-rs-edb4f8c0f5624a5c/4cdcd57/federation-2/router-bridge/build.rs:41:9
|   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
| warning: build failed, waiting for other jobs to finish...
```

**Desktop (please complete the following information):**
 - OS: Ubuntu-latest as per Github config

**Additional context**
I suspect this dependency issue is on [this branch in federation-rs](https://github.com/apollographql/federation-rs/tree/geal/defer) is causing the issue; whether it's because it doesn't build, or as an active branch it can't be referred to, I'm not sure.
