### ISSUE TITLE
OTLP: Metrics: provide a way to specify service_name

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#1490]
The telemetry service_name's key, located in metrics -> common -> resources is "service.name".

However "service.name" cannot be represented in yml (dots in keys aren't allowed)

There is thus no way to override the OTLP service name in the router.

**Comment by SimonSapin** [comment]
Can the key be quoted?

This also applies to `register_plugin!("foo", "bar", MyPlugin);` which takes configuration in a `foo.bar` key

**Comment by abernix** [comment]
Hmm, maybe I'm misunderstanding something, but I suspect there must be more to this than just merely dots not being allowed in keys because having dots in keys is a common pattern in Kubernetes YAML.  For example:

```yaml
metadata:
  name: media
  namespace: default
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"443": "media"}}'
```

We also _used_ to have dots in our keys for plugins before we dropped the `com.apollographql` prefix from plugin names, right?
