### ISSUE TITLE
Reconsider the organization of configuration sections

### ISSUE THREAD

**Issue by SimonSapin** [apollographql/router#1500]
Let's have a look before 1.0 at how we want to split configuration keys into sections

**Comment by Geal** [comment]
so, the point I was raising there is that the configuration schema is too influenced by the plugins structure, and not enough by what would make sense from the usage point of view.

As an example, let's say we had a configuration file using URL override, header manipulation and rate limiting:

```yaml
server:
  listen: 0.0.0.0:4000

override_subgraph_url:
  accounts: http://localhost:8080

headers:
  subgraphs:
    accounts:
      - propagate:
        named: "Authorization"
    products:
      - insert:
          name: "InsertSubgraph"
          value: "Value"

traffic_shaping:
  router:
    rate_limit:.
      capacity: 10
      interval: 5s
    timeout: 50sec
  subgraphs:
    products:
      rate_limit:
      timeout: 50sec
```

Here we see router level and subgraph level configuration in 3 different sections, because each one has its own configuration. This is still a manageable example, but it is bound to become more complex as more subgraphs are added and more plugins are developed.

What I would like to see is something of that shape:

```yaml
server:
  listen: 0.0.0.0:4000
  traffic_shaping:
    rate_limit:.
      capacity: 10
      interval: 5s
    timeout: 50sec

subgraphs:
  accounts:
    override_url: http://localhost:8080
    headers:
      - propagate:
        named: "Authorization"
  products:
    headers:
      - insert:
        name: "InsertSubgraph"
        value: "Value"
    traffic_shaping:
      rate_limit:
      timeout: 50sec
```

Router level configuration is clearly separated, and each subgraph has its own configuration. Note that this is still the same configuration shape though, because each subsection still has the plugin name. I would like at some point that configuration be completely decorrelated from plugin name (example: by flattening the traffic_shaping options directly under the router or subgraph section), but that would be too much work for now.

What I am proposing would amount to extracting the global and subgraph level sections of a plugin from the configuration, and assembling it in a coherent configuration object for that plugin, which is much more doable than a complete configuration overhaul
