### ISSUE TITLE
Ability to include header as part of various log levels

### ISSUE THREAD

**Issue by vishvajeet-patil** [apollographql/router#1513]
**Is your feature request related to a problem? Please describe.**
In our existing NodeJS gateway we have customised logger to include some non-sensitive headers as part of logs for various levels. Similar feature does not exist in Rust Gateway. This is very useful thing to have while debugging issues in production.

**Describe the solution you'd like**
Inject headers based on separate logging header whitelisting config for given levels. For example

```
log:
 levels:
   all:
      headers:
          - propagate:
               matching: (?i)(some-header|some-other-header)
```
**Describe alternatives you've considered**
Rely on logging in subgraphs only instead of gateway. Needs to drill one level deeper to figure out issues.
