### ISSUE TITLE
Unable to send `Env` tag through configuration for Datadog

### ISSUE THREAD

**Issue by vasquez-csdisco** [apollographql/router#1520]
**Describe the bug**
Hi everybody, is there a way we can pass an `env` tag to datadog through the integrated telemetry framework?
Currently, all my traces are stepping into the none environment and I couldn't find a way to attach a tag through the configuration.

<img width="188" alt="image" src="https://user-images.githubusercontent.com/79875862/184978240-2e46a8c5-6f67-4a18-8c2e-e3fcbe041256.png">

This is my current configuration for telemetry:

```
telemetry:
  tracing:
    trace_config:
      service_name: ${SERVICE_NAME}
    datadog:
      endpoint: default
    propagation:
      datadog: true
```
Before by using `dd-trace` in Apollo Gateway, I was able to set the `DD_ENV` environment and send the environment tag automatically, but I couldn't find their counterpart in Apollo Router

I have also tried this but with no luck
```
  tracing:
    trace_config:
      service_name: my-service-name
      attributes:
        env: my-env
        env.dd_env: my-env
        env:dd_env: my-env
        dd_env: my-env
        tags: ["env:my-env"]
    datadog:
      endpoint: http://my-remote-datadog-agent:8126
    propagation:
      datadog: true
```

**Comment by bnjjj** [comment]
I think this one is related to #2066

**Comment by garypen** [comment]
Should have been re-opened when we backed out otel 0.19.0. Re-opening now.

**Comment by maschwenk** [comment]
So what is the correct way to get this configured then?

```
telemetry:
  tracing:
    trace_config:
      service_name: ${SERVICE_NAME}
    datadog:
      endpoint: default
    propagation:
      datadog: true
```
and then just setting `DD_ENV` on the container?
