### ISSUE TITLE
`__typename` of the root type is not returned if a fragment is deferred

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/router#1677]
Given the below query:

```graphql
{
  __typename
  fast
  ...deferedFragment @defer
}

fragment deferedFragment on Query {
  slow
}
```

The `__typename` is not included in the initial payload:

```
$ curl --request POST \
    --header 'Accept: multipart/mixed; deferSpec=20220824;' \
    --header 'content-type: application/json' \
    --url 'http://0.0.0.0:4040/' \
    --data '{"query":"{\n  __typename\n  fast\n  ...deferedFragment @defer\n}\n\nfragment deferedFragment on Query {\n  slow\n}","variables":{}}'

--graphql
content-type: application/json

{"data":{"fast":0},"hasNext":true}
```

## more info

**config.yaml**

```yaml
server:
  experimental_defer_support: true
  listen: 0.0.0.0:4040
cors:
  origins:
    - https://studio.apollographql.com
plugins:
  experimental.include_subgraph_errors:
    all: true
```

**supergraph.graphqls**

```graphql
type Query
  @join__type(graph: PANDAS)
{
  slow: Int @join__field(graph: PANDAS)
  fast: Int @join__field(graph: PANDAS)
}
```

**router:** `6b83a74b3c3df08a7e1360e03462164fa2d71532`

Still happengin at `055183276dffc6eaa9477b2abd3fa612482ad8b6`
