### ISSUE TITLE
OTLP Tracing Endpoint Expects http:// Prefix

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#1754]
**Describe the bug**
As title; the OTLP tracing endpoint expects the `http://` prefix even if using gRPC.

**To Reproduce**
A non-working config: 

```yml
server:
  listen: 0.0.0.0:80
telemetry:
  tracing:
    otlp: 
      endpoint: collector.monitoring:4317
      protocol: grpc
    trace_config:
      service_name: "router"
      service_namespace: "router"
  metrics:
    prometheus:
      enabled: true
plugins:
  experimental.include_subgraph_errors:
    all: true
```

Returns either timeout errors or generic gRPC errors; example: `OpenTelemetry trace error occurred: Exporter otlp encountered the following error(s): the grpc server returns error (Unknown error): , detailed error message: transport error`

Working configuration: 

```yml
server:
  listen: 0.0.0.0:80
telemetry:
  tracing:
    otlp: 
      endpoint: http://collector.monitoring:4317
      protocol: grpc
    trace_config:
      service_name: "router"
      service_namespace: "router"
  metrics:
    prometheus:
      enabled: true
plugins:
  experimental.include_subgraph_errors:
    all: true
```

**Expected behavior**
Either: 

* Documented format for the URL 
* Accepting either format (prefixed and non-prefixed)
