### ISSUE TITLE
dynamic header injection

### ISSUE THREAD

**Issue by deweyjose** [apollographql/router#1755]
**Is your feature request related to a problem? Please describe.**

Passing contextual information about the request from Router to downstream subgraphs as http request headers requires a custom plugin or non feasible approach or static configuration. 

We'd like to pass the subgraph name  as a header that is passed to subgraphs, there are too many on our end to manage statically in router.yaml.

We also want to pass the originating request's operationName to subgraphs, today we need to use rhai or a custom native plugin. The same or similar rules for governing metrics tags could be used for downstream http headers.

**Describe the solution you'd like**

```yaml
headers:
  all: 
  - insert:
      name: subgraph-name
      value: "${context.subgraph_name}"
  - insert:
      name: source-operation-name
      body:
        - path: .operationName
```
