### ISSUE TITLE
multiple levels of cache depending on the branch

### ISSUE THREAD

**Issue by Geal** [apollographql/router#178]
Right now, when restoring the cache, we first look for a cache matching the Cargo.lock file, or any valid cache for that platform:

https://github.com/apollographql/router/blob/3f282070d350b1ec1ca0c7f10334f03d98a273e9/.circleci/config.yml#L270-L273

The issue here is that it will take the same cache as the last time Cargo.lock changed, while the PR's code could change significantly compared to main, so we'll rebuild things often.

There's a small improvement I tested in a PR:
https://github.com/apollographql/router/blob/43d8a5cbaf67bb06410fd6419f17be94105111bb/.circleci/config.yml#L53-L57

The idea is that when e start the PR, we take the last known cache for main, then we build the PR, and save the cache for the PR's branch. That way, for all future builds of that branch, we start from the branch specific cache and have less work to do

cc @o0Ignition0o

**Comment by o0Ignition0o** [comment]
this is a great idea. two suggestions:

- add cargo.toml checksum so that we can have a close enough hit
- remove the wider variant so we don't end up with a huge `~/.cargo` folder, that never gets cleared.

In pseudo code this would look like:

```yml
 - restore_cache: 
     keys: 
       - rust-target-v1-macos-{{ checksum "Cargo.toml" }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
       - rust-target-v1-macos-{{ checksum "Cargo.toml" }}-{{ .Branch }}
       - rust-target-v1-macos-{{ checksum "Cargo.toml" }}
```

how does this sound? tis would be a a small t-shirt size imo
