### ISSUE TITLE
Embedded Sandbox default connection endpoint of http://0.0.0.0:4000/ results in query errors

### ISSUE THREAD

**Issue by prasek** [apollographql/router#1785]
**Describe the bug**
Embedded Sandbox at http://locahost:4000 defaults to connection endpoint of http://0.0.0.0:4000/ resulting in query errors

**To Reproduce**

1. Console window 1:
```
git clone https://github.com/apollographql/supergraph-demo-fed2.git
cd supergraph-demo-fed2
make run-router-main
```

Note this runs with `acme_router --dev -c router.yaml` (using router as a lib)
```
cors:
  allow_any_origin: true
supergraph:
  listen: 0.0.0.0:4000
  introspection: true
sandbox: # temporary workaround until RC1 is released
  listen: 0.0.0.0:4000
include_subgraph_errors:
  all: true # Propagate errors from all subraphs
telemetry:
  apollo:
    # The percentage of requests will include HTTP request and response headers in traces sent to Apollo Studio.
    # This is expensive and should be left at a low value.
    # This cannot be higher than tracing->trace_config->sampler
    field_level_instrumentation_sampler: 1 # (default)
  tracing:
    trace_config:
      sampler: 1 # The percentage of requests that will generate traces (a rate or `always_on` or `always_off`)
include_subgraph_errors:
  all: true # Propagate errors from all subraphs
```

2. Verify router has started

3: Console window 2:
```
make smoke
```

4. verify smoke tests pass

5. open http://localhost:4000 to load the Embedded Sandbox using Chrome
6. see the Sandbox connection endpoint is set to `http://0.0.0.0:4000/`
7. Run the following query in Sandbox
```
fragment MyFragment on Product {
    variation { name }
  }
}
query Dimensions {
  allProducts {
    ...MyFragment @defer
    sku
    id
  }
}
```

8. See the following error
```
{
  "error": {
    "message": "Failed to fetch",
    "stack": "TypeError: Failed to fetch\n    at <anonymous>:1:876\n    at handleRequest.s.includeCookies (https://embeddable-sandbox.cdn.apollographql.com/_latest/embeddable-sandbox.umd.production.min.js:1:52074)\n    at https://embeddable-sandbox.cdn.apollographql.com/_latest/embeddable-sandbox.umd.production.min.js:1:54762\n    at l (https://embeddable-sandbox.cdn.apollographql.com/_latest/embeddable-sandbox.umd.production.min.js:1:60081)"
  }
}
```

9. Adjust the Sandbox connection endpoint to: `http://localhost:4000/`

10. See the query execute successfully

**Expected behavior**
Embedded Sandbox connection endpoint should default to a host/IP where the router can be queried.

Where possible Sandbox should default to the browser window URL, but regardless when accessing Sandbox at http://localhost:4000 the queries should just work without having to adjust the Sandbox connection endpoint.

**Output**
See above

**Desktop (please complete the following information):**
Apollo Router v1.0.0-rc.0
OS: Mac OS 12.5.1 [64-bit]
Shell: /bin/zsh

**Additional context**
