### ISSUE TITLE
Improve logging experience

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#1840]
When you need to debug the router or find why you received an error from the router it's often a pain and can take time to discover what's going on. For example if you have to debug an error reported by the router and just wants to know what was the request sent and raw response received by a subgraph, for now it needs to add logs directly in the router codebase. 

Another example, sometimes we throw an error in the graphql errors array with less context and cannot find the equivalent error with more context in our logs. 

What I would like is to have a simple mechanism to find related logs to a GraphQL error just by grepping our logs. We could add a unique identifier generated for a specific error and provide this ID in `extensions`

Example:

```json
{
  "errors": [
    {
      "message": "HTTP fetch failed from 'inventory': service 'inventory' response was malformed: service 'inventory' response was malformed: invalid type: string \"/\", expected a sequence",
      "path": [
        "allProducts",
        "@"
      ],
      "extensions": {
        "error_id": "123e4567-e89b-12d3-a456-426614174000", // This error code can be used to grep into our logs
        "type": "SubrequestHttpError",
        "service": "inventory",
        "reason": "service 'inventory' response was malformed: service 'inventory' response was malformed: invalid type: string \"/\", expected a sequence"
      }
    }
  ]
}
```

```logs
2022-09-20T09:11:22.481856Z ERROR an error occured due to ... error_id="123e4567-e89b-12d3-a456-426614174000"
``` 

in logs `error_id="123e4567-e89b-12d3-a456-426614174000"`

Also we could add a `logging` section in `telemetry` to configure if we want to log requests and raw responses from subgraphs, if we want to add some redacting to not leak any sensible information.

```yaml
telemetry:
  logging:
    format: pretty # Could be json or pretty
    on_graphql_error: true # Display a log when we return a GraphQL error
    on_http_error: true # Display a log if status code >200
    every_requests: false # If enabled we log every requests
    subgraphs:
      all:
        request: 
          enabled: true # Log all requests for subgraphs
          redact: # Redact some part of the log
          - match: secret*
            to: REDACTED
        response: 
          enabled: true # Log all responses from subgraphs
          redact: # Redact some part of the log
          - match: secret*
            to: REDACTED
        
      my_subgraph:
        request: 
          enabled: true # Log all requests for subgraphs
          redact: # Redact some part of the log
          - match: secret*
            to: REDACTED
        response:
          enabled: true # Log all requests for subgraphs
```

Sub tasks:

- [x] Request id #1981 
- [ ] Support same kind of [`formatResponse` from the gateway](https://www.apollographql.com/docs/apollo-server/data/errors/#masking-and-logging-errors)
- [x] Enable/disable specific logs (cf example of yaml file) #1998 
- [ ] Would love to have a log format feature [like this](https://nginx.org/en/docs/http/ngx_http_log_module.html#log_format)
