### ISSUE TITLE
DNS resolution error, may be related to Reqwest

### ISSUE THREAD

**Issue by hugo-marello** [apollographql/router#1899]
**Describe the bug**
While running a docker-compose instance of the router on my mac, I get an error while trying to fetch supergraph from uplink. It looks like a dns resolution problem.
May be related to this issue of [Reqwest](https://github.com/seanmonstar/reqwest/issues/435).
The issue seems to be fixed on a version router is not using (router v1.0.0 uses reqwest 0.11.11, fix looks like to be on 0.11.12)

Am I doing something wrong or this make sense?

**To Reproduce**
1. Run a docker-compose on macOS with m1
```
version: '3.1'

services:
  apollo-router:
    image: 'ghcr.io/apollographql/router:v1.0.0-debug'
    restart: always
    ports:
      - 4000:4000
      - 8088:8088
    volumes:
      - ./router.yaml:/dist/config/router.yaml
 ```

2. See error

**Expected behavior**
Resolve DNS and fetch graph from uplink.

**Output**
Error message:
```{"timestamp":"2022-09-27T22:08:56.865907Z","level":"ERROR","fields":{"message":"error downloading the schema from Uplink: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"aws.uplink.api.apollographql.com\")), port: None, path: \"/\", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError(\"dns error\", Custom { kind: Uncategorized, error: \"failed to lookup address information: Temporary failure in name resolution\" })) })"},"target":"apollo_router::router"}```

**Desktop:**
 - OS: macOS Monterey 12.6
 - Version router v1.0.0

**Additional context**
