### ISSUE TITLE
incorporate helm chart validation in CI

### ISSUE THREAD

**Issue by garypen** [apollographql/router#1914]
As suggested by @damienpontifex but splitting out from  #1908 PR here.

```

  xtask_check_helm:
    parameters:
      os:
        type: string
    steps:
      - run:
          name: Validate helm manifests
          command: |
            TODAY=$(date +"%Y-%m-%d")
            CURRENT_KUBE_VERSIONS=$(curl -L https://raw.githubusercontent.com/kubernetes/website/main/data/releases/schedule.yaml \
              | yq -o json '.' \
              | jq --raw-output '.schedules[] | select((now | strftime("%Y-%m-%dT00:00:00Z")) as $date | .releaseDate < $date and .endOfLifeDate > $date) | .previousPatches[0].release')
            TEMPLATE_DIR=$(mktemp -d)
            echo "${CURRENT_KUBE_VERSIONS}" | while read kube_version; do
              helm template --kube-version "${kube_version}" router helm/chart/router --set autoscaling.enabled=true > "${TEMPLATE_DIR}/router-${kube_version}.yaml"
              kubeval "${TEMPLATE_DIR}/router-${kube_version}.yaml" \
                --kubernetes-version "${kube_version}" \
                --strict \
                --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master
            done
  xtask_check_compliance:
    parameters:
      os:
	@@ -284,6 +308,22 @@ jobs:
            - linux_install_baseline
            - xtask_lint:
                os: linux
  check_helm:
    environment:
      <<: *common_job_environment
    parameters:
      platform:
        type: executor
    executor: << parameters.platform >>
    steps:
      - checkout
      - when:
          condition:
            equal: [*rust_linux_executor, << parameters.platform >>]
          steps:
            - linux_install_baseline
            - xtask_check_helm:
                os: linux
  check_compliance:
    environment:
      <<: *common_job_environment
	@@ -516,6 +556,11 @@ workflows:
            parameters:
              platform: [rust_linux]

      - check_helm:
          matrix:
            parameters:
              platform: [rust_linux]

      # check-compliance is disabled for now because it is flaky
      # `cargo about` seems to be non-deterministic and sometimes
      # produces a different licenses.html file even though dependencies haven’t changed.
```
