### ISSUE TITLE
Disabling telemetry

### ISSUE THREAD

**Issue by viktorvoltaire** [apollographql/router#2038]
Maybe im missing something, but is there a way to totally disable opentelemetry?

**Comment by bnjjj** [comment]
You can disable tracing by changing the sampling on traces using this configuration for example:

```yaml
telemetry:
  tracing:
    trace_config:
      # Optional. Either a float between 0 and 1 or 'always_on' or 'always_off'
      sampler: always_off

```
