### ISSUE TITLE
datadog exporter ignores attributes

### ISSUE THREAD

**Issue by deweyjose** [apollographql/router#2066]
**Describe the bug**
The Datadog exporter does not apply attributes configured in Router.yaml to spans. Our team needs to set the `version` tag at the root of all traces exported to Datadog for Deployment tracking.

**To Reproduce**

```
  tracing:
    trace_config:
      service_name: "${env.DD_SERVICE:-rusty-router}"
      attributes:
        version: "${env.DD_VERSION:-test}"
    propagation:
      datadog: true
```

**Expected behavior**
We expect to all traces to include a version tag at the root of each span named version.

**Output**
If applicable, add output to help explain your problem.
We do not see the version tag.

**Desktop (please complete the following information):**

**Additional context**

As a workaround we added a supergraph plugin that adds a span explicitly for this purpose, but it seems wasteful. It also does not help when Router receives invalid gql request that cause 400s as those short circuit any plugins we right - our version spans will not be applied.
