### ISSUE TITLE
Unable to run router with helm chart and a local supergraph path

### ISSUE THREAD

**Issue by sgsharma** [apollographql/router#2068]
**Describe the bug**
I am trying to run the router using the helm chart and the example supergraph schema from the Quickstart docs [here](https://www.apollographql.com/docs/router/quickstart#2-download-the-example-supergraph-schema). However, despite using volume and volume mounts that look like they're working to mount the config map into the pod, I'm getting an error at router startup 

`⚠️  The Apollo Router requires a composed supergraph schema at startup. ⚠️`

**To Reproduce**

```
$ curl -sSL https://supergraph.demo.starstuff.dev/ > supergraph-schema.graphql
$ helm pull oci://ghcr.io/apollographql/helm-charts/router --version 1.0.0-rc.6
$ helm upgrade --install router-test oci://ghcr.io/apollographql/helm-charts/router --version 1.0.0-rc.6 --values values.yaml

```

Values.yaml:
```
# Default values for router.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# -- See https://www.apollographql.com/docs/router/configuration/overview#configuration-file for yaml structure
router:
  configuration:
    supergraph:
      listen: 0.0.0.0:4000
      preview_defer_support: false
      introspection: true
    health-check:
      listen: 0.0.0.0:8088
    telemetry:
      tracing:
        trace_config:
          service_name: "router"
          service_namespace: "apollo"
          sampler: 1
        otlp:
          endpoint: 0.0.0.0:4317
          # Optional protocol (Defaults to grpc)
          protocol: grpc
      metrics:
        prometheus:
          enabled: true
          listen: 0.0.0.0:9090
          path: "/metrics"

  args:
  - --hot-reload

managedFederation:
  # -- If using managed federation, the graph API key to identify router to Studio
  apiKey:
  # -- If using managed federation, use existing Secret which stores the graph API key instead of creating a new one.
  # If set along `managedFederation.apiKey`, a secret with the graph API key will be created using this parameter as name 
  existingSecret:
  # -- If using managed federation, the variant of which graph to use
  graphRef: ""

# An array of extra environmental variables
# Example:
extraEnvVars:
  - name: APOLLO_ROUTER_SUPERGRAPH_PATH
    value: /etc/supergraph-schema.graphql
  - name: APOLLO_ROUTER_LOG
    value: debug
#
extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''

# An array of extra VolumeMounts
# Example:
extraVolumeMounts:
  - name: supergraph-schema
    mountPath: /etc
    readOnly: true
extraVolumeMounts: []

# An array of extra Volumes
# Example:
extraVolumes:
  - name: supergraph-schema
    configMap:
      name: apollo-router-supergraph
      items:
        - key: supergraph-schema.graphql
          path: supergraph-schema.graphql
# extraVolumes: []

image:
  repository: ghcr.io/apollographql/router
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPorts:
  # -- If you override the port in `router.configuration.server.listen` then make sure to match the listen port here
  http: 80
  # -- For exposing the metrics port when running a serviceMonitor for example
  metrics: 9090
  # -- For exposing the healthcheck endpoint
  health: 8088

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  annotations: {}

serviceMonitor:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# set to true to enable istio's virtualservice
virtualservice:
  enabled: false
  # namespace: ""
  # gatewayName: ""
  # http:
  #   main:
  #     # set enabled to true to add
  #     # the default matcher of `exact: "/" or prefix: "/graphql"`
  #     # with the <$fullName>.<.Release.Namespace>.svc.cluster.local destination
  #     enabled: true
  #   # use additionals to provide your custom virtualservice rules
  #   additionals: []
  #   - name: "default-nginx-routes"
  #       match:
  #         - uri:
  #             prefix: "/foo"
  #       rewrite:
  #         uri: /
  #       route:
  #         - destination:
  #             host: my.custom.backend.svc.cluster.local
  #             port:
  #               number: 80

# set to true and provide configuration details if you want to make external https calls through istio's virtualservice
serviceentry:
  enabled: false
  # hosts:
  # a list of external hosts you want to be able to make https calls to
  #   - api.example.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
```
**Expected behavior**
Router starts up successfully with the supergraph specified

**Output**
CrashLoopBackoff with error `⚠️  The Apollo Router requires a composed supergraph schema at startup. ⚠️`

```
Volumes:                                                                                                               │
│   router-configuration:                                                                                                │
│     Type:      ConfigMap (a volume populated by a ConfigMap)                                                           │
│     Name:      router-test                                                                                             │
│     Optional:  false                                                                                                   │
│   supergraph-schema:                                                                                                   │
│     Type:      ConfigMap (a volume populated by a ConfigMap)                                                           │
│     Name:      apollo-router-supergraph                                                                                │
│     Optional:  false
```

**Desktop (please complete the following information):**
Apple M1 Pro macOS Monterey Version 12.5
Running Kubernetes within Docker Desktop

**Comment by garypen** [comment]
The helm chart is fine, but I did find issues with your values.yaml:

1. You specify `extraEnvVars` and `extraVolumeMounts` and then reset them both back to empty arrays.
```
extraEnvVars:
  - name: APOLLO_ROUTER_SUPERGRAPH_PATH
    value: /etc/supergraph-schema.graphql
  - name: APOLLO_ROUTER_LOG
    value: debug
#
extraEnvVars: []

extraVolumeMounts:
  - name: supergraph-schema
    mountPath: /etc
    readOnly: true
extraVolumeMounts: []
```
2. Mounting a configMap to `/etc` will break your container. I modified your values.yaml  to use a different directory (/data) and that worked fine.

Things should work with those changes in place. One thing to watch out for: the `--hot-reload` flag often won't work in k8s or docker environments and so you may want to remove that from your args list.  You'll see a log error like this:
```
{"timestamp":"2022-11-09T09:15:06.025046Z","level":"ERROR","fields":{"message":"panicked at 'could not create watch on: \"/app/configuration.yaml\"', apollo-router/src/files.rs:50:29"},"target":"apollo_router::executable"}
```
if you have hit the --hot-reload problem.

**Comment by sgsharma** [comment]
Thanks @garypen - that unblocked me from the supergraph issue; however, I'm now seeing this in the startup logs for the router pod:

```
│ {"timestamp":"2022-11-09T21:11:50.058350Z","level":"ERROR","fields":{"message":"panicked at 'could not create watch on: \"/app/configuration.yaml\"', apollo-router/src/files.rs:50:29"},"target":"apollo_router::executable"}                    ││ Stream closed EOF for default/router-test-754fcc6857-ntmvn (router)                                                                                                                                                                               │
```

If it helps - here's the updated values.yaml file:
```
# Default values for router.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# -- See https://www.apollographql.com/docs/router/configuration/overview#configuration-file for yaml structure
router:
  configuration:
    supergraph:
      listen: 0.0.0.0:4000
      preview_defer_support: false
      introspection: true
    health-check:
      listen: 0.0.0.0:8088
    telemetry:
      tracing:
        trace_config:
          service_name: "router"
          service_namespace: "apollo"
          sampler: 1
        otlp:
          endpoint: 0.0.0.0:4317
          # Optional protocol (Defaults to grpc)
          protocol: grpc
      metrics:
        prometheus:
          enabled: true
          listen: 0.0.0.0:9090
          path: "/metrics"

  # args:
  # - --hot-reload

managedFederation:
  # -- If using managed federation, the graph API key to identify router to Studio
  apiKey:
  # -- If using managed federation, use existing Secret which stores the graph API key instead of creating a new one.
  # If set along `managedFederation.apiKey`, a secret with the graph API key will be created using this parameter as name 
  existingSecret:
  # -- If using managed federation, the variant of which graph to use
  graphRef: ""

# An array of extra environmental variables
# Example:
extraEnvVars:
  - name: APOLLO_ROUTER_SUPERGRAPH_PATH
    value: /data/supergraph-schema.graphql
  - name: APOLLO_ROUTER_LOG
    value: debug
#
# extraEnvVars: []
extraEnvVarsCM: ''
extraEnvVarsSecret: ''

# An array of extra VolumeMounts
# Example:
extraVolumeMounts:
  - name: supergraph-schema
    mountPath: /data
    readOnly: true
# extraVolumeMounts: []

# An array of extra Volumes
# Example:
extraVolumes:
  - name: supergraph-schema
    configMap:
      name: apollo-router-supergraph
      items:
        - key: supergraph-schema.graphql
          path: supergraph-schema.graphql
# extraVolumes: []

image:
  repository: ghcr.io/apollographql/router
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPorts:
  # -- If you override the port in `router.configuration.server.listen` then make sure to match the listen port here
  http: 80
  # -- For exposing the metrics port when running a serviceMonitor for example
  metrics: 9090
  # -- For exposing the healthcheck endpoint
  health: 8088

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  annotations: {}

serviceMonitor:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# set to true to enable istio's virtualservice
virtualservice:
  enabled: false
  # namespace: ""
  # gatewayName: ""
  # http:
  #   main:
  #     # set enabled to true to add
  #     # the default matcher of `exact: "/" or prefix: "/graphql"`
  #     # with the <$fullName>.<.Release.Namespace>.svc.cluster.local destination
  #     enabled: true
  #   # use additionals to provide your custom virtualservice rules
  #   additionals: []
  #   - name: "default-nginx-routes"
  #       match:
  #         - uri:
  #             prefix: "/foo"
  #       rewrite:
  #         uri: /
  #       route:
  #         - destination:
  #             host: my.custom.backend.svc.cluster.local
  #             port:
  #               number: 80

# set to true and provide configuration details if you want to make external https calls through istio's virtualservice
serviceentry:
  enabled: false
  # hosts:
  # a list of external hosts you want to be able to make https calls to
  #   - api.example.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
```
