### ISSUE TITLE
configuration for external caching

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2075]
#2024 introduces a two level cache (in memory then redis) to cache query plans, introspection responses and APQ. It only adds one configuration option for a URL list to the redis cluster.
We should have more granular options to:
- activate or deactivate the redis cache for each of those
- put individual limits for the in memory cache (number/size)

how can we add those options, but marking them as experimental for the time being?

**Comment by BrynCooke** [comment]
Here's a suggestion for discussion:
```yaml
apq:
  cache:
    redis:
      url:  ...  
query_planning:
  cache:
    redis: 
      url: ...
  
supergraph:
  introspection: 
    enabled:
    cache:
      redis:
        url: ...
```
  
This will give us the option to supply different cache backends later, and also add things like auth to the redis connection etc.
