### ISSUE TITLE
Rename `telemetry.metrics.common.attributes.router` field to `telemetry.metrics.common.attributes.supergraph`

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#2076]
In order to be consistent we should rename the way we are configuring the custom attributes on metrics.
It's a breaking change (we can also accept both).

example:

```yaml
telemetry:
  metrics:
    common:
      attributes:
        supergraph: # <<<<<
          static:
            - name: "version"
              value: "v1.0.0"
          request:
            header:
              - named: "x-custom-header-to-add"
```

instead of

``` yaml
telemetry:
  metrics:
    common:
      attributes:
        router:
          static:
            - name: "version"
              value: "v1.0.0"
          request:
            header:
              - named: "x-custom-header-to-add"
```
