### ISSUE TITLE
Add configuration for `trace_id` 

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#2080]
By default we decided to disable the export of `trace_id` in response headers for several reasons.
The goal of this issue is to find what we need to configure the behavior of `trace_id`.

Here are 3 different features I detected:
+ Expose or not the `trace_id` in response headers
+ Specify the header name if we want to expose it and modify the default one (default: `apollo-trace-id`)
+ Specify a custom propagator to indicate what's the header name to set the `trace_id`

Configuration example:

```yaml
telemetry:
  tracing:
    experimental_expose_trace_id:
      enabled: true # default: false
      header_name: "my-trace-id" # default: "apollo-trace-id"
    propagation:
      custom_header: "x-request-id"
      jaeger: true
```
