### ISSUE TITLE
No traces published using OTLP exporter

### ISSUE THREAD

**Issue by psyho** [apollographql/router#2171]
**Describe the bug**

We are running apollo router version 1.4.0 and have it configured to push traces to an Open Telemetry Collector instance. We have a nearly identical setup for local development and in our staging environment, except that locally, we run the router and collector in docker-compose and in staging using k8s. In k8s no traces are published to the collector, and no errors are logged.

Below is the exact configuration of the router we are running:

```yaml
health-check:
  listen: 0.0.0.0:8080
supergraph:
  listen: 0.0.0.0:8080
  path: /graphql
  introspection: true
homepage:
  enabled: false
include_subgraph_errors:
  all: true # Propagate errors from all subraphs
cors:
  allow_credentials: true
  origins:
    - https://studio.apollographql.com
  match_origins:
    - "http://[a-z0-9-_]+[.]renofi[.]local"
    - "https://[a-z0-9-_]+[.]renofistaging[.]com"
    - "https://[a-z0-9-_]+--renofi[a-z0-9-_]*.netlify.app"
telemetry:
  tracing:
    propagation:
      zipkin: true
      trace_context: true
    otlp:
      endpoint: "web.otel-collector:4317"
    trace_config:
      sampler: always_on
      service_name: "api-gateway"
      service_namespace: "renofi"
      attributes:
        service_name: "api-gateway"
headers:
  all:
    request:
      - propagate:
          named: authorization
      - propagate:
          named: x-service-account-id
      - propagate:
          named: x-service-token
      - propagate:
          named: x-request-id
      - propagate:
          named: x-b3-traceid
      - propagate:
          named: origin
      - propagate:
          named: x-forwarded-for
      - propagate:
          named: x-forwarded-host
```

ENV variables:

```
  OTEL_LOG_LEVEL: debug
  OTEL_BSP_SCHEDULE_DELAY: '1000'
  OTEL_BSP_EXPORT_TIMEOUT: '180000'
  OTEL_BSP_MAX_QUEUE_SIZE: '10000'
  OTEL_BSP_MAX_EXPORT_BATCH_SIZE: '2000'
  OTEL_BLRP_SCHEDULE_DELAY: '1000'
  OTEL_BLRP_EXPORT_TIMEOUT: '180000'
  OTEL_BLRP_MAX_QUEUE_SIZE: '10000'
  OTEL_BLRP_MAX_EXPORT_BATCH_SIZE: '2000'
  OTEL_ATTRIBUTE_COUNT_LIMIT: '256'
  OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT: '256'
  OTEL_SPAN_EVENT_COUNT_LIMIT: '256'
  OTEL_SPAN_LINK_COUNT_LIMIT: '256'
  OTEL_EVENT_ATTRIBUTE_COUNT_LIMIT: '256'
  OTEL_LINK_ATTRIBUTE_COUNT_LIMIT: '256'
  APOLLO_UPLINK_ENDPOINTS: https://uplink.api.apollographql.com/
  APOLLO_ROUTER_LOG: trace
  APOLLO_ROUTER_CONFIG_PATH: "/app/configuration.yaml"
  APOLLO_ROUTER_HOT_RELOAD: 'true'
  APOLLO_GRAPH_REF: # our graph
  APOLLO_KEY: # our key
```

What's very strange is that when I replaced the `telemetry.tracing.oltp.endpoint` with a requestcatcher URL (and protocol with `http`), nothing was published there at all. I tried the same thing in docker-compose, and that works fine. I also noticed that locally, when I input an URL that does not resolve or that can't be connected to, the router logs include some message that shows that it was impossible to connect to that URL. On the other hand, in our k8s setup there is no such message in the logs. Almost as if the router never even attempted to send data to the remote endpoint.

[Here's a link to the logs from the apollo router](https://gist.github.com/psyho/e6df41c7c81b98f235cf7afee3155d2d) - it seems like [this](https://gist.github.com/psyho/e6df41c7c81b98f235cf7afee3155d2d#file-logs-json-L385) shows that the tracing is being configured properly.

Is there anything that would disable tracing in apollo-router that's not in the configuration? Maybe some ENV variable that I should check? Or is there any way to enable more detailed logging out of the tracing plugin?

I realize that without being able to reproduce the issue, there's not much you can do for me to fix it, but I'm reporting this mainly with the hope that you have some pointers on how I can debug the issue.

**To Reproduce**

Unfortunately, this works for me locally, so I don't know how to reproduce it.

**Expected behavior**

Observe that apollo router pushes traces to the collector (or a request catcher enpoint) or at least an error in the logs that indicates what's wrong.

**Desktop (please complete the following information):**

Running the official docker image: `ghcr.io/apollographql/router:v1.4.0` (in k8s on google cloud).

**Comment by BrynCooke** [comment]
This could be a TLS problem.
Can you try specifying http or https on your endpoint?

Another thing to confirm is that another program can send to collector.

**Comment by psyho** [comment]
> This could be a TLS problem. Can you try specifying http or https on your endpoint?

I can try but I thought that open telemetry collector grpc endpoint is no-TLS by default: https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md#server-configuration

> Another thing to confirm is that another program can send to collector.

Yes, I have verified that.

**Comment by psyho** [comment]
Unfortunately, that doesn't appear to change anything.

I tried:

```
telemetry:
  tracing:
    otlp:
      endpoint: "http://web.otel-collector:4317"
```

and

```
telemetry:
  tracing:
    otlp:
      endpoint: "http://web.otel-collector:4318"
      protocol: http
```
and neither seems to work.

FWIW, this is the collector config:

```
 receivers:
      otlp:
        protocols:
          grpc: # on port 4317
          http: # on port 4318
            cors:
              allowed_origins: ["*"]

    processors:
      batch:

    exporters:
      logging:
        verbosity: detailed
        sampling_initial: 1
        sampling_thereafter: 1
      otlphttp:
        endpoint: "https://api.honeycomb.io"
        headers:
          "x-honeycomb-dataset": staging-otel
          "x-honeycomb-team": ${HONEYCOMB_WRITE_KEY}

    service:
      telemetry:
        logs:
          level: "debug"

      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlphttp]
```
