### ISSUE TITLE
Integration tests for the Redis cache

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2174]
the Redis cache (APQ, query plan) is currently not tested properly. We should add an integration test that starts a Redis cluster and a router, does a few queries, then checks that the data appears in Redis

**Comment by Geal** [comment]
as a start, here's a docker-compose to start a cluster:

```yaml
version: '2'
services:
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=router'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
    ports:
      - 6379:6379

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=router'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
    ports:
      - 6380:6379

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=router'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2'
    ports:
      - 6381:6379

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
```
