### ISSUE TITLE
No variables present in the Apollo Studio even with `send_variable_values` set

### ISSUE THREAD

**Issue by radekmie** [apollographql/router#2186]
**Describe the bug**
We've deployed Router 1.3 a couple of days ago and wanted to see how the telemetry works in there (we were at pre-1.0 before). To do that, we added the following configuration:
```yml
telemetry:
    apollo:
        field_level_instrumentation_sampler: 1.0 # Just for tests.
        send_headers: all
        send_variable_values: all
    tracing:
        trace_config:
            sampler: 1.0 # Just for tests.
```

The headers are there (I mean, their values - their names were already there), field level instrumentation also works. However, none of the values is present. We've also tried to list them explicitly:
```yml
telemetry:
    apollo:
        send_variable_values:
            only:
                - input
```

But it didn't change anything. Are we missing something or is it a bug?

**To Reproduce**
1. Setup the Router with any configuration and add the telemetry config I posted above.
2. Execute a couple of GraphQL requests against it.
3. Check the Apollo Studio for traces.

**Expected behavior**
Traces are there, their headers are present, and so are values.

**Output**
Traces are there, their headers are present, but values are not.
