### ISSUE TITLE
Metrics: Add operation name label

### ISSUE THREAD

**Issue by klippx** [apollographql/router#2335]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to OPT IN to injecting operation name as a label to subgraph requests.

**Describe the solution you'd like**
Since Operation Name is something that is coming from the ORIGINAL request to router, it should be possible to do via configuration only. Perhaps something like this:
```
telemetry:
  metrics:
    common:
      attributes:
        subgraph: # Attribute configuration for requests to/responses from subgraphs
          all:
            request:
              operation:
                - named: 'operation_name'
                   rename: 'operation_name' # optional rename
                   missing:
                   - behavior: 'skip' # skip adding this label on missing operation names
                   # - behavior: 'anonymous' # add label "anonymous" on missing operation names
```
This will inject `operation_name=<value>` to each metric, with options on how to handle missing operation_names.

**NOTE 1**: Since the original operation name is "mangled" by router before fed to subgraphs (i.e if the operation name by user is `TechnicalData` then router changes it to `TechnicalData__<subgraph name>__<number>`. Which is NOT what we want! 🤨  We want the _original_ operation name provided by consumer which in this case is `TechnicalData`.

**NOTE 2**: Since a new histogram bucket will be created for EVERY unique operation name, by default, please keep operation OUT of subgraph requests (keep old behaviour). I am a bit reluctant to opt in to this myself at fear of creating way too many data points 😟 

**Describe alternatives you've considered**
To skip monitor subgraphs by operation name, and monitor that on the subgraph side instead. We can still monitor each subgraphs on a "big picture", and see response time trends from router perspective, but might miss and fail to identify individual slow operations by name.

**Additional context**
None.
