### ISSUE TITLE
Tracing sampler of 0 errors in v1.7.0

### ISSUE THREAD

**Issue by InsidersByte** [apollographql/router#2339]
**Describe the bug**
A sampler of 0 (disabled) errors in v1.7.0.

```json
{
  "timestamp": "2023-01-03T12:37:31.075286Z",
  "level": "ERROR",
  "fields": {
    "message": "plugin apollo.telemetry could not be configured: field level instrumentation sampler must sample less frequently than tracing level sampler"
  },
  "target": "apollo_router::router_factory"
}
```

**To Reproduce**
1. Start up using the configuration below
2. Router doesn't start
3. See logs for error

```yaml
# yaml-language-server: $schema=./router-config-schema.json

telemetry:
  tracing:
    trace_config:
      service_name: apollo-router
      service_namespace: apollo
      sampler: 0
```

**Expected behavior**
Application starts up and reporting telemetry is disabled.
