### ISSUE TITLE
experimental.external plugin "Break" message encoded as JSON

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/router#2346]
When using `experimental.external` and the co-processor responds with `control: { Break: "message" }`, the message is encoded as JSON.

- Router Version 1.7.0

**To Reproduce**
Router config:

```yaml
plugins:
  experimental.external:
    url: ${env.ROUTER_STAGE_URL}
    timeout: 2s
    stages:
      router:
        request:
          headers: true
          context: true
```

Co-processor response:

```js
res.json({
  ...req.body,
  control: { Break: "my error message" }
});
```

Response:

```json
{
  "data": {},
  "errors": [
    { "message": "\"my error message\"" }
  ]
}
```

**Expected behavior**
```json
{
  "data": null,
  "errors": [
    { "message": "my error message" }
  ]
}
```
