### ISSUE TITLE
Move variable deduplication to a subgraph level option

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2352]
variable deduplication in traffic shaping is a top level option, along with router and subgraph options. This is the wrong level, because it affects only subgraph requests, and we might want to activate it or not depending on the subgraph.

Example configuration of what we have now:

```yaml
traffic_shaping:
  deduplicate_variables: true # Enable the variable deduplication optimization.
  router: # Rules applied to requests from clients to the router
    global_rate_limit: # Accept a maximum of 10 requests per 5 secs. Excess requests must be rejected.
      capacity: 10
  all:
    deduplicate_query: true # Enable query deduplication for all subgraphs.
    compression: br # Enable brotli compression for all subgraphs.
```

What we should have instead:

```yaml
traffic_shaping:
  router: # Rules applied to requests from clients to the router
    global_rate_limit: # Accept a maximum of 10 requests per 5 secs. Excess requests must be rejected.
      capacity: 10
  all:
    deduplicate_query: true # Enable query deduplication for all subgraphs.
    compression: br # Enable brotli compression for all subgraphs.
    deduplicate_variables: true # Enable the variable deduplication optimization.
```

does this count as a breaking change, or something that could be easily fixed with a migration?
