### ISSUE TITLE
Memory leak in datadog tracing setup

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2359]
**Describe the bug**
There is a pretty severe memory leak in datadog tracing integration.

This is how the memory graph looks over 1 day, at approx ~15r/s:

<img width="1465" alt="Screenshot 2023-01-06 at 15 35 17" src="https://user-images.githubusercontent.com/8524109/211033241-b9e8227c-a7a8-4e39-bc2f-37a20ae2ae6b.png">

Note that they only grow to ~4GB of memory which is a limit at which server gets killed.

This is the relevant telemtry/tracing configuration:

```yaml
telemetry:
  tracing:
    datadog:
      endpoint: "http://${env.DD_AGENT_HOST:-datadog}:8126"
```
