### ISSUE TITLE
Include response body/text on un-sucessful subgraph requests

### ISSUE THREAD

**Issue by Meemaw** [apollographql/router#2375]
**Describe the solution you'd like**
Seeing some logs that looks like this: `Fetch error: HTTP fetch failed from 'main': HTTP fetch failed from 'main': 400: Bad Request`. 

Its very hard to know from these errors what the problem is. 400 could mean a lot of things.

It would be great if those errors (logs) included the actual response of the subgraph.

**Describe alternatives you've considered**
N/A

**Comment by Geal** [comment]
You can try the [experimental logging options](https://github.com/apollographql/router/blob/dev/CHANGELOG.md#add-configuration-for-logging-and-add-more-logs-issue-1998) for that:

```yaml
telemetry:
  experimental_logging:
    format: json # By default it's "pretty" if you are in an interactive shell session
    display_filename: true # Display filename where the log is coming from. Default: true
    display_line_number: false # Display line number in the file where the log is coming from. Default: true
    # If one of these headers matches we will log supergraph and subgraphs requests/responses
    when_header:
      - name: apollo-router-log-request
        value: my_client
        headers: true # default: false
        body: true # default: false
      # log request for all requests/responses headers coming from Iphones
      - name: user-agent
        match: ^Mozilla/5.0 (iPhone*
        headers: true
```

**Comment by Meemaw** [comment]
Hmm, looking at the configuration options I don't see how I would include response bodies for subgraph responses on errors.

**Comment by Geal** [comment]
with something like this, it will display the subgraph request and response bodies:

```yaml
telemetry:
  experimental_logging:
    when_header:
      - name: host
        value: subgraph.example.com
        headers: true
        body: true
```
