### ISSUE TITLE
`experimental_response_trace_id` issues

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/router#2404]
A couple of related issues:

**Number one**
With version 1.8, if I configure the router with:

```yaml
telemetry:
  apollo:
    field_level_instrumentation_sampler: always_on
  tracing:
    experimental_response_trace_id:
      enabled: true
```

The router fails to start with: 

```
ERROR apollo_router::router_factory: plugin apollo.telemetry could not be configured: missing field `header_name`
```

(I was trying to get `apollo-trace-id` to appear in the trace inspector in Studio. If I set a custom header name, it works

**Number two**
If I enable `--dev` mode with the same configuration, using debug logs the resolved configuration has a null `header_name`: 

```
  "tracing": {
    "experimental_response_trace_id": {
      "enabled": true,
      "header_name": null
    }
  },
```

I would expect that `--dev` mode would override `experimental_response_trace_id.enabled` to true, but leave any existing `header_name` alone.
