### ISSUE TITLE
Router hides subgraph errors on required fields that are not part of query

### ISSUE THREAD

**Issue by thrawny** [apollographql/router#2422]
**Describe the bug**
Router hides subgraph errors on required fields that are not part of query. The nodejs gateway exposes these errors.

**To Reproduce**
```graphql
# Subgraph A
type Thing @key (fields: "id") {
  id : ID!
  foo: String!
}

# Subgraph B
type Thing @key (fields: "id") {
  id : ID!
  foo: String! @external
  bar: String! @requires(fields: "foo")
}

```
If a query contains only the `bar` field, and there is an error while resolving `foo` in Subgraph A, that error will not be exposed back to the client.

**Expected behavior**
If subgraph errors are turned on in the router config, I would expect these errors to be exposed as well as normal errors.

**Comment by bnjjj** [comment]
What's the behavior ? You have no errors at all or only one error ?

**Comment by thrawny** [comment]
No errors at all. Copying actual example from slack:
Router
```json
{
  "data": {
    "carByToken": {
      "visualizations": null
    }
  }
}
```

Nodejs gateway:
```
{
  "errors": [
    {
      "message": "bang!",
      "extensions": {
        "serviceName": "product-enrichment-dgs",
        "code": "DOWNSTREAM_SERVICE_ERROR",
        "stacktrace": [
          "GraphQLError: bang!",
          "..."
        ]
      }
    }
  ],
  "data": {
    "carByToken": {
      "visualizations": null
    }
  },
  "extensions": {}
}

```

**Comment by asanovr** [comment]
I have this problem too

router config
```
supergraph:
  introspection: true
  listen: 0.0.0.0:4000
  path: /graphql

cors:
  allow_any_origin: true

headers:
  all:
    request:
      - propagate:
          matching: ".*"

homepage:
  enabled: false

sandbox:
  enabled: true

include_subgraph_errors:
  all: true

traffic_shaping:
  all:
    deduplicate_query: true
    timeout: 30s
  deduplicate_variables: true
  router:
    timeout: 30s

telemetry:
  experimental_logging:
    format: json
    display_filename: true
    display_line_number: false
```

Response from router
```
{
  "data": {
    "getAdvList": {
      "hasNextPage": false,
      "totalCount": 0,
      "nodes": null
    }
  }
}
```

Response from mercurius gateway
```
{
  "data": {
    "getAdvList": {
      "hasNextPage": false,
      "totalCount": 0,
      "edges": [],
      "nodes": null
    }
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field AdvModel.favoritesCount.",
      "locations": [
        {
          "line": 47,
          "column": 7
        }
      ],
      "path": [
        "getAdvList",
        "nodes",
        "0",
        "favoritesCount"
      ]
    }
  ]
}
```
