### ISSUE TITLE
Azure Appinsights and New Relic Integration for traccing and logs

### ISSUE THREAD

**Issue by VBPanchal** [apollographql/router#2433]
We are using Azure app insignts and new relic for the logging performace evalution, in other our previous federation  gateway we are using this. 

As we have already options for the jaeger and oltp, we can also provide azure appinsights and new relic for logging purpose

Please provide idea to integrate with custom plugin or other resources

**Comment by VBPanchal** [comment]
Hello @Geal 

Thanks for you soulutions, As We are not using kubernetes,

So We have to integrate it as custom exporter from the apollo router, If you have any idea about integration with tracing plugin.

Please let me know for this

**Comment by Geal** [comment]
this is not limited to kubernetes, opentelemetry-collector can work in other infrastructures. As an example, ehre's how you would use it with docker-compose:

```yaml
version: "3.9"
services:
  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.69.0
    command: ["--config=/conf/collector-config.yml"]
    volumes:
      - ./opentelemetry/collector-config.yml:/conf/collector-config.yml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
      - "55679:55679"
```

Could you please try to run it? If it works, it will be way easier for you than adding another exporter

**Comment by VBPanchal** [comment]
Hello Geal

As we have checked with the given config, but I am unable to setup due to collector config file.

Will you please guilde me to create collector-config.yml?

**Comment by Geal** [comment]
they provide an example file in the [link](https://docs.dapr.io/operations/monitoring/tracing/otel-collector/open-telemetry-collector-appinsights/#run-opentelemetry-collector-to-push-to-your-application-insights-instance) I posted above, you can extract the collector config from there (I replaced the zipkin receiver with otlp):

```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:12346
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
exporters:
  logging:
    loglevel: debug
  azuremonitor:
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    instrumentation_key: "<INSTRUMENTATION-KEY>"
    # maxbatchsize is the maximum number of items that can be
    # queued before calling to the configured endpoint
    maxbatchsize: 100
    # maxbatchinterval is the maximum time to wait before calling
    # the configured endpoint.
    maxbatchinterval: 10s
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [azuremonitor,logging]
```

replce `<INSTRUMENTATION_KEY>` with your Azure key

You can then configure the router to send traces there via OTLP: https://www.apollographql.com/docs/router/configuration/tracing#opentelemetry-collector-via-otlp
