### ISSUE TITLE
Consolidated error rate metrics by extension field

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/router#2460]
The customer goal is to capture error rates, often categorized by an arbitrary `code` field in the error extensions:

```json
{ "data": null, "errors": [{ "message": "xxx", "extensions": { "code": "MY_CODE" } }] }
```

There are two ways to convert `errors.*.extensions.code` into a metric attribute:

1. On non-20x responses, use `telemetry.metrics.common.attributes.{supergraph,subgraph}.errors`.
2. On 20x responses, use `telemetry.metrics.common.attributes.{supergraph,subgraph}.response.body`.

The latter isn't specific to errors, and the JSON path feature does not handle arrays, so you have to pick a single error per attribute:

```yaml
telemetry:
  metrics:
    common:
      attributes:
        supergraph: # Attribute configuration for requests to/responses from the router
          response:
            body:
              # Apply the value of the provided path of the router's response body as an attribute
              - path: .errors[0].extensions.status
                name: error_from_body
```

The combination of these conditions makes it difficult to create a single metric that counts the occurrence of a type of error that I can use to build alerts.

**Describe the solution you'd like**
I think my ideal solution is that `telemetry.metrics.common.attributes.{supergraph,subgraph}.errors` works with 20x responses. Maybe there's an optional configuration property to opt-in to this behavior.

```yaml
telemetry:
  metrics:
    common:
      attributes:
        supergraph: 
            errors:
              include_20x_responses: true # NEW
              include_messages: false
              extensions:
                - name: subgraph_error_extended_type 
                  path: .code 
```

**Describe alternatives you've considered**
Alternatively, we could add an `errors` property next to `body` for generating attributes from the response. 

```yaml
telemetry:
  metrics:
    common:
      attributes:
        supergraph: 
          response:
            errors:
              include_messages: false
              extensions:
                - name: subgraph_error_extended_type 
                  path: .code 
```

This will result in one metric for 20x responses and one for non-20x responses but at least we'd be able to capture _all_ the errors in a 20x response.

**Additional context**
Subgraphs that conform to the draft "GraphQL over HTTP" spec should use `200 OK` for responses that include top-level errors: https://graphql.github.io/graphql-over-http/draft/#sec-application-json. We want the ability to capture top-level error rates in these situations.
