### ISSUE TITLE
`propagation.baggage` has no effect

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/router#2473]
**Describe the bug**
I can't get any `baggage` headers to propagate to subgraphs using `tracing.propgation.baggage`.

Header propagation works great so I wonder if we should just remove this configuration option?

```yaml
headers:
  all:
    request:
      - propagate:
          named: baggage
```

**To Reproduce**

1. Client request:
    ```
    curl --request POST \
    --header 'content-type: application/json' \
    --header 'apollographql-client-name: MyClient' \
    --header 'apollographql-client-version: 1.0' \
    --header 'baggage: key1=value1' \
    --url http://localhost:4000/ \
    --data '{"query":"query Query {\n  viewer {\n    id\n    firstName\n    lastName\n    createdAt\n    profile {\n      id\n      profile1\n      paymentMethods {\n        id\n        kind\n        number\n      }\n    }\n  }\n}"}'
    ```
2. Router config:
    ```yaml
    telemetry:
      tracing:
        trace_config:
          service_name: router
          service_namespace: router
        propagation:
          baggage: true
        otlp:
          endpoint: otel-collector:4317
          protocol: grpc
    ```

**Expected behavior**
The subgraph should receive headers like this:
```json
{
  'baggage': 'key1=value1',
  'content-type': 'application/json',
  'accept': 'application/json, application/graphql-response+json',
  'traceparent': '00-8fadbf24f4e7c108dbfb8cd5587caabe-242649777ba02ea9-01',
  'tracestate': '',
  'accept-encoding': 'gzip,deflate,br',
  'host': 'localhost:4002',
  'content-length': '166'
}
```

But I'm not seeing the `baggage` header unless I also set up header propagation using the workaround described above.

**Desktop (please complete the following information):**
 - OS: mac os ventura
 - Version: 1.9.0

**Additional context**
I found this while creating some documentation, I don't know if anyone has encountered it in the wild.
