### ISSUE TITLE
bug: Variable Expansion on booleans

### ISSUE THREAD

**Issue by sMorm** [apollographql/router#2510]
## Overview
When passing in a boolean value as a static metric, router fails to parse the boolean value as a string.

## Reproduce

Using the router config `router.yaml` :
```yaml router.yaml
telemetry:
  metrics:
    common:
      attributes:
        supergraph:
          static:
            - name: "my_boolean"
              value: '${env.MY_BOOLEAN:-false}'
```

For the schema, I used the sample schema from
`curl -L https://supergraph.demo.starstuff.dev/`

Running Router with command:
`./router --dev --supergraph starstuff.graphql -c router.yaml`

Produces the error
```
ERROR configuration had errors:
1. at line 8

        attributes:
          supergraph:
            static:
              - name: "my_boolean"
                value: '${env.MY_BOOLEAN:-false}'
                       ^----- "${env.MY_BOOLEAN:-false}" is not of type "string"
```

It seems like static metrics expect a string as a value, but is being parsed as a boolean since `false` `true` `0` and `1` are all considered invalid values.

Our work around right now is to temporarily use `FALSE` and `TRUE`. Wrapping the fallback value with quotes like this:

`value: '${env.MY_BOOLEAN:-"false"}'`

works but doesn't work when MY_BOOLEAN is actually set in the environment.
