### ISSUE TITLE
Router propagates headers to subgraph but does not emit metrics with the correct labels

### ISSUE THREAD

**Issue by akhilesh-godi** [apollographql/router#2559]
**Describe the bug**
The router allows for adding metric labels to include request headers. However, despite adding the right configuration to show header in the metrics and forwards headers to subgraphs appropriately, the metrics emitted do not have the header.

**To Reproduce**
Set up router with a config synonymous to the following:

```
supergraph:
  path: /graphql
  listen: 0.0.0.0:4000
  introspection: true
sandbox:
  enabled: true
homepage:
  enabled: false
health-check:
  listen: 0.0.0.0:8088
  enabled: true
include_subgraph_errors:
  all: true

headers:
  # Header rules for all subgraphs
  all:
    request:
      - propagate:
          matching: (?i)(x-custom-platform)

telemetry:
  metrics:
    prometheus:
      enabled: true
      listen: 0.0.0.0:4000
      path: /metrics
    common:
      attributes:
        subgraph:
          all:
            errors:
              extensions: # Include extensions data
                - name: subgraph_call_error_extensions_code # Name of the attribute
                  path: .code # JSON query path to fetch data from extensions
            request:
              header:
                - named: "x-custom-platform"
                  rename: "platform"
                  default: "IDK"
        supergraph:
          request:
            header:
              - named: "x-custom-platform"
                rename: "platform"
                default: "IDK"


traffic_shaping:
  all:
    timeout: 500ms
  subgraphs:
    all:
      timeout: 300ms
```

Router version: v1.8.0:
```APOLLO_ROUTER_CONFIG_PATH=config.yaml cargo run --release -- --supergraph examples/graphql/supergraph.graphql```

Try running a curl 
```
curl -v --location --request POST 'http://localhost:4000/graphql' \ 
--header 'content-type: application/json' --header 'x-custom-platform: android' \
--data-raw '{"query":"query { me { id name }}"}'
```

**Expected behavior**
Should be able to see:
```
# HELP apollo_router_http_requests_total Total number of HTTP requests made.
# TYPE apollo_router_http_requests_total counter
apollo_router_http_requests_total{platform="android",service_name="apollo-router",status="200"} 1
apollo_router_http_requests_total{platform="android",service_name="apollo-router",status="200",subgraph="accounts"} 1
```

**Output**
Instead see:
```
# HELP apollo_router_http_requests_total Total number of HTTP requests made.
# TYPE apollo_router_http_requests_total counter
apollo_router_http_requests_total{platform="android",service_name="apollo-router",status="200"} 1
apollo_router_http_requests_total{platform="IDK",service_name="apollo-router",status="200",subgraph="accounts"} 1
```

This shows that the metrics plugin is not receiving the appropriate headers in `subgraph_request` as it appears that the headers are populated elsewhere and this doesn't flow through correctly.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] N/A
 - Version [e.g. 22]: N/A
