### ISSUE TITLE
We are unable to disable hot reload functionality in Apollo Router

### ISSUE THREAD

**Issue by marc-barry** [apollographql/router#2674]
**Describe the bug**

We have deployed Apollo Router on our Kubernetes cluster, serving a significant amount of traffic. We are using Apollo Router with managed federation and thus according to https://www.apollographql.com/docs/router/configuration/overview#environment-variables we have specified the following:
* https://www.apollographql.com/docs/router/configuration/overview#apollo_graph_ref
* https://www.apollographql.com/docs/router/configuration/overview#apollo_key

As part of our backend service deployment, we have a need to control when Apollo Router loads the new schema from managed federation. It is our experience that there is no way to disable the hot reload functionality in router even though we don't specify the https://www.apollographql.com/docs/router/configuration/overview#--hr----hot-reload argument and we even set `APOLLO_ROUTER_HOT_RELOAD=false`.

**To Reproduce**
1. Use https://github.com/apollographql/router/tree/dev/helm/chart/router to deploy the router to a Kubernetes cluster.
2. Ensure that in the `values.yaml` you provide to the Helm chart install you specify `args: []` so that the default args, which includes `--hot-reload` isn't provided to the deployment: https://github.com/apollographql/router/blob/dev/helm/chart/router/values.yaml#LL22C5-L22C17.
3. Set `APOLLO_ROUTER_HOT_RELOAD=true`. **Note, this is optional as we removed the command line argument from above and so this shouldn't be necessary but we do it anyhow as want to ensure it is disabled.**
4. Make sure to setup managed federation in values: https://github.com/apollographql/router/blob/dev/helm/chart/router/values.yaml#L24-L31
5. Start Apollo Router and it will pull the supergraph and it will be able to route.
6. Publish a subgraph schema update via https://www.apollographql.com/docs/federation/managed-federation/overview/.
7. In the logs of the router you will see logs which state `reloading` and `reload complete` which are reported as an `INFO` log.

**Expected behavior**

The hot reload functionality should be disabled and it shouldn't hot reload when it isn't enabled and/or it is explicitly disabled. There appears to be no way to disable it and one is opted into regardless not specifying `--hot-reload`.

**Output**

You get info log messages which say `reloading` and `reload complete`. We see a significant increase in CPU usage and request latency during hot reloading at our scale. We can see this happen when the hot reload occurs. We accept that hot reload behaves this way but we don't want it to happen at all.

**Desktop (please complete the following information):**
 - OS: Linux/Kubernetes
 - Version 1.11.0

**Additional context**

We have also set `APOLLO_TELEMETRY_DISABLED=true` to see if that has any impact. It didn't appear to do so.

Below is an example of our configuration file (with some small things redacted):
```
cors:
  allow_credentials: true
  origins:
  - http://localhost:4000
headers:
  all:
    request:
    - propagate:
        matching: .*
health_check:
  listen: 0.0.0.0:8088
include_subgraph_errors:
  all: true
rhai:
  main: main.rhai
  scripts: /dist/rhai
supergraph:
  listen: 0.0.0.0:80
  path: /graphql
telemetry:
  metrics:
    common:
      resources:
        service.name: apollo-router
    prometheus:
      enabled: true
      listen: 0.0.0.0:9090
      path: /metrics
  tracing:
    otlp:
      batch_processor:
        max_concurrent_exports: 1000
        max_export_batch_size: 10000
        max_export_timeout: 100s
        max_queue_size: 10000
        scheduled_delay: 100ms
      endpoint: chronocollector-traces.chronosphere.svc.cluster.local:4317
      protocol: grpc
    propagation:
      trace_context: true
    trace_config:
      service_name: apollo-router
traffic_shaping:
  all:
    compression: gzip
    deduplicate_query: false
    timeout: 95s
  deduplicate_variables: false
  router:
    timeout: 95s
````
