### ISSUE TITLE
Suspect a memory leak in Apollo Router

### ISSUE THREAD

**Issue by marc-barry** [apollographql/router#2690]
**Describe the bug**

We see Apollo Router grow in memory usage over a few days until it finally gets OOM killed. The memory keeps increasing over time little by little.

**To Reproduce**

We are running Apollo Router with the following configuration:

```
cors:
  allow_credentials: true
  origins:
  - http://localhost
headers:
  all:
    request:
    - propagate:
        matching: .*
health_check:
  listen: 0.0.0.0:8088
include_subgraph_errors:
  all: true
rhai:
  main: main.rhai
  scripts: /dist/rhai
supergraph:
  listen: 0.0.0.0:80
  path: /graphql
telemetry:
  metrics:
    common:
      resources:
        service.name: apollo-router
    prometheus:
      enabled: true
      listen: 0.0.0.0:9090
      path: /metrics
traffic_shaping:
  all:
    compression: gzip
    deduplicate_query: false
    timeout: 95s
  deduplicate_variables: false
  router:
    timeout: 95s
```
Note that the `origins` for CORS have been adjusted to remove our domains.

We restarted all pods this morning as they were close to being OOM killed but this is what a 6 our window of memory usage looks like:

![image](https://user-images.githubusercontent.com/4965634/221298891-9f287241-6984-4660-b8ab-f45f61f42116.png)

**The memory will continue to grow until it hits the 1.5GiB limit and is finally killed by the underlying system.**

**Expected behavior**

We expect Apollo Router to hit a steady state of memory usage but instead, it increases linearly until it runs out of memory.

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version v1.11.0 (https://github.com/apollographql/router/releases/tag/v1.11.0)

**Additional context**

We are running this on Kubernetes and we currently have `20` pods serving traffic. The CPU in the time window looks like the following:

![image](https://user-images.githubusercontent.com/4965634/221299363-92bb691f-5bb3-4647-b7ea-59e0ba72895d.png)

The spikes are due to the managed federation updates when we update the subgraphs in Apollo Studio's system. Hot reload is disabled.

**Comment by marc-barry** [comment]
We are tracking the memory usage over the weekend (which is low-traffic time). Here are point-in-time `top pods`:

```
kubectl top pods -n apollo-router
NAME                             CPU(cores)   MEMORY(bytes)
apollo-router-7fd44dcc9b-27zcg   11m          711Mi
apollo-router-7fd44dcc9b-2fxkc   16m          740Mi
apollo-router-7fd44dcc9b-4tgp5   12m          789Mi
apollo-router-7fd44dcc9b-6xbbd   14m          793Mi
apollo-router-7fd44dcc9b-757nf   17m          762Mi
apollo-router-7fd44dcc9b-7x55r   15m          465Mi
apollo-router-7fd44dcc9b-8q8bd   12m          510Mi
apollo-router-7fd44dcc9b-96whd   12m          284Mi
apollo-router-7fd44dcc9b-99krm   12m          346Mi
apollo-router-7fd44dcc9b-btchx   14m          464Mi
apollo-router-7fd44dcc9b-fvmr6   18m          693Mi
apollo-router-7fd44dcc9b-gf8qv   13m          463Mi
apollo-router-7fd44dcc9b-gj55t   17m          396Mi
apollo-router-7fd44dcc9b-jps72   11m          745Mi
apollo-router-7fd44dcc9b-kjqg8   13m          733Mi
apollo-router-7fd44dcc9b-kvjfr   14m          681Mi
apollo-router-7fd44dcc9b-l9dxb   14m          356Mi
apollo-router-7fd44dcc9b-mqxtp   12m          773Mi
apollo-router-7fd44dcc9b-mwx5m   14m          640Mi
apollo-router-7fd44dcc9b-ncmcl   14m          781Mi
apollo-router-7fd44dcc9b-nj5l7   13m          546Mi
apollo-router-7fd44dcc9b-pchls   10m          669Mi
apollo-router-7fd44dcc9b-pmzs5   15m          473Mi
apollo-router-7fd44dcc9b-pqsxx   14m          520Mi
apollo-router-7fd44dcc9b-t5nhd   15m          803Mi
apollo-router-7fd44dcc9b-vkrlv   17m          747Mi
apollo-router-7fd44dcc9b-vpkhq   13m          776Mi
apollo-router-7fd44dcc9b-vxj46   14m          754Mi
apollo-router-7fd44dcc9b-wg6cz   13m          689Mi
apollo-router-7fd44dcc9b-z7rfj   13m          604Mi
```

I think it is useful to see the scale of memory we are seeing. Our resources limits are:
```
resources:
  limits:
    cpu: 1000m
    memory: 1500Mi
  requests:
    cpu: 100m
    memory: 350Mi
```

We do get `OOMKilled` reasons for pods which means they did climb to greater than `1500Mi`.
