### ISSUE TITLE
configuration consistency around subgraph

### ISSUE THREAD

**Issue by garypen** [apollographql/router#2743]
Should we use:
 - subgraph
 - subgraphs
 - OR just remove the element completely

?

Example so we remember what this is about:

```
telemetry:
  metrics:
    common:
      attributes:
        supergraph: # Attribute configuration for requests to/responses from the router
          static:
            - name: "version"
              value: "v1.0.0"
          request:
            header:
              - named: "content-type"
                rename: "payload_type"
                default: "application/json"
              - named: "x-custom-header-to-add"
          response:
            body:
              # Apply the value of the provided path of the router's response body as an attribute
              - path: .errors[0].extensions.status
                name: error_from_body
          context:
            # Apply the indicated element from the plugin chain's context as an attribute
            - named: my_key
        subgraph: # Attribute configuration for requests to/responses from subgraphs
          all:
            static:
              # Always apply this attribute to all metrics for all subgraphs
              - name: kind
                value: subgraph_request
            errors: # Only work if it's a valid GraphQL error (for example if the subgraph returns an http error or if the router can't reach the subgraph)
              include_messages: true # Will include the error message in a message attribute
              extensions: # Include extensions data
                - name: subgraph_error_extended_type # Name of the attribute
                  path: .type # JSON query path to fetch data from extensions
                - name: message
                  path: .reason
            # Will create this kind of metric for example apollo_router_http_requests_error_total{message="cannot contact the subgraph",service_name="apollo-router",subgraph="my_subgraph_name",subgraph_error_extended_type="SubrequestHttpError"}
          subgraphs:
            my_subgraph_name: # Apply these rules only for the subgraph named `my_subgraph_name`
              request:
                header:
                  - named: "x-custom-header"
                body:
                  # Apply the value of the provided path of the router's request body as an attribute (here it's the query)
                  - path: .query
                    name: query
                    default: UNKNOWN
```
