### ISSUE TITLE
Better performance debugging experience

### ISSUE THREAD

**Issue by radekmie** [apollographql/router#2748]
**Describe the solution you'd like**
The traces sent to Apollo Studio could include more context. I'm not sure if Apollo Studio supports that, but maybe the "waiting on server" should be used here?

**Describe alternatives you've considered**
We didn't look into the Open Telemetry logs, but I assume these should be on-par.

**Additional context**
Here are two sample traces we see in our Apollo Studio:
| Sample A | Sample B |
|:-:|:-:|
| <img width="690" alt="image" src="https://user-images.githubusercontent.com/1379064/224475974-c6645ee1-4dfd-43bb-88a1-a2a22c82c9b6.png"> | <img width="690" alt="image" src="https://user-images.githubusercontent.com/1379064/224476000-4abae57f-0c57-4610-9012-a3e1a971da45.png"> |

_(First three lines are from Subgraph A, next two from Subgraph B.)_

Both are 99.99+ percentile and we wanted to optimize our "long tails" of API response times. However, based on this information, we have little to no context what's the problem here:
1. Is it Subgraph A? _(Deployed to N containers; responds fast to own queries.)_
2. Is it Subgraph B? _(Deployed to AWS lambda; responds fast to own queries; cold starts are confirmed not to happen for these two traces.)_
3. Is it Apollo Router? _(Deployed to 1 container; responds fast to single-subgraph queries.)_
4. Is it network? _(All subgraphs and Apollo Router are in the same subnet in the same AWS region.)_
5. Anything else?

<details>
<summary>We use Apollo Router v1.9.0 with the following config:</summary>

```yml
supergraph:
  listen: 0.0.0.0:4000
  path: /
  introspection: true
  apq:
    subgraph:
      all:
        enabled: true
cors:
  allow_any_origin: true
  allow_headers: []
homepage:
  enabled: false
headers:
  all:
    request:
      - propagate:
          matching: .*
traffic_shaping:
  deduplicate_variables: true
  router:
    timeout: 90s
  all:
    deduplicate_query: true
    compression: gzip
    timeout: 90s
include_subgraph_errors:
  all: true
telemetry:
  apollo:
    field_level_instrumentation_sampler: 1.0
    send_headers: all
    send_variable_values: all
  tracing:
    trace_config:
      sampler: 1.0
```

</details>
