### ISSUE TITLE
Adding custom field / value on tracing span

### ISSUE THREAD

**Issue by yanns** [apollographql/router#2765]
**Is your feature request related to a problem? Please describe.**
In plugins, we extract some information from the http request:
- some information from the path
We extract the `project_key`.
```
supergraph:
  listen: "${env.ROUTER_LISTEN_ADDRESS:-0.0.0.0:4000}"
  path: /:project_key/*
```
- some information from http headers. We use a `correlation_id` header, a bit similar to the [`trace_id`](https://www.apollographql.com/docs/router/configuration/tracing#trace-id).  If this header is not present, we build the value ourselves.

We would like to add those information into the tracing span, like:
```rust
let span = Span::current();
span.record("correlation_id", &correlation_id);
```
so that we can have those information in all log events.

This cannot work, as it's only possible to set value to fields that are declared when the span is created.
Those are the fields currently declared: https://github.com/apollographql/router/blob/f21b6fc4c4b5976e19cb94ecd279a0a304134ccc/apollo-router/src/plugins/telemetry/mod.rs#L248-L260

If I use one of them, then it's working:
```rust
span.record("apollo_private.http.response_headers", &correlation_id);
```

**Describe the solution you'd like**

It'd be great if we can declare field names that are initialized with `field::Empty` so that we can set the values from the plugins.
```
telemetry:
  tracing:
    additional_fields: ["correlation_id", "project_key"]
```

**Describe alternatives you've considered**

Other alternatives:
- through configuration, letting the existing telemetry plugin extracting values from the HTTP request to put them into custom values. This would work if we don't need any special treatment, like creating the value if it does not exist.
- for `correlation_id`, using https://www.apollographql.com/docs/router/configuration/tracing#trace-id and transforming the json entities emitted by the log to rename `trace-id` into `correlation_id`.
When I tried that approach:
```
telemetry:
  tracing:
    propagation:
      request:
        header_name: "x-correlation-id"
    experimental_response_trace_id:
      enabled: true
      header_name: "x-correlation-id"
```
I got some errors as the value we are using cannot be used for `trace-id`:
```
"cannot generate custom trace_id: invalid digit found in string"
```
And I'd still need to create our customized value if the request does not contain this header.
- another alternative is to configure new fields with values populated automatically from the context:
If we insert from values in the context:
```rust
request
  .context
  .insert("correlation_id", correlation_id)
  .expect("cannot insert correlation ID into context");
```
then we could configure the telemetry plugin to use those values:
```
telemetry:
  tracing:
    additional_fields:
      - name: "correlation_id"
         value_from_context: "correlation_id"
      - name: "project_key"
         value_from_context: "project_key"
```
This alternative is maybe not easy to implement as plugins can put values into the context at any point.

**Additional context**
This might be related to https://github.com/apollographql/router/issues/398
Also related to https://github.com/apollographql/router/issues/1651 to that we can define our own `Subscriber` that would use those custom values.
