### ISSUE TITLE
Allow propagating the Accept header unchanged in the config YAML

### ISSUE THREAD

**Issue by markandrus** [apollographql/router#2774]
**Is your feature request related to a problem? Please describe.**

We are integrating Apollo Router. Some of our requests through Apollo Router are signed. The signing scheme canonicalizes each request, generates a signature, and adds the signature to the request. Signed headers may not be modified in transit; otherwise, the request can no longer be authenticated.

The Accept header is one of our signed headers. Part of our system issues requests with `Accept: */*`. Apollo Router translates this to `Accept: application/json, application/graphql-response+json`. This breaks our request signature.

We see that

```yaml
headers:
  all:
    request:
      - propagate:
          matching: .*
```

results in the Accept header being transformed. We also tried

```yaml
headers:
  all:
    request:
      - remove:
          named: "accept"
      - insert:
          name: "accept"
          value: "*/*"
```

but this does not change the Accept header.

**Describe the solution you'd like**

Apollo Router provides a way to propagate the Accept header unchanged in the config YAML.

**Describe alternatives you've considered**

- Change our internal requests to include and sign `Accept: application/json, application/graphql-response+json` by default.
- Bypass Apollo Router for internal requests.

**Additional context**

The Host header is also important for us, but we see that we can rewrite it using the config YAML.
