### ISSUE TITLE
Add configuration for what graphql elements are included in span attributes

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#2820]
In particular graphql.document can be very large and also leak information. We need to have a way of disabling this.

When tackling this we need to take a look at how this is configured between metrics and tracing so that we have a common structure.

**Comment by goto-bus-stop** [comment]
Can be done with:
```yaml
telemetry:
  instrumentation:
    spans:
      supergraph:
        attributes:
          graphql.document: false
```
