### ISSUE TITLE
ERROR plugin apollo.telemetry could not be configured: invalid type: string "...", expected a sequence

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/router#2831]
**Describe the bug**
The [docs](https://www.apollographql.com/docs/router/configuration/tracing#opentelemetry-collector-via-otlp) and the JSON schema suggest 

```yaml
telemetry:
  tracing:
    otlp:
      grpc:
        metadata:
          foo: bar
```

But this produces an error. Adding values to an array works:

```yaml
telemetry:
  tracing:
    otlp:
      grpc:
        metadata:
          foo: 
            - bar
```

- Version 1.12.1
