### ISSUE TITLE
Coprocessor: subgraph stage: document the need for an `all` key

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#2860]
[The Coprocessor subgraph stage documentation is off](https://www.apollographql.com/docs/router/customizations/coprocessor/#typical-configuration), the subgraph request and response stage keys differ from the router stage's, and it needs to be under the `all` key. eg:

```yaml
coprocessor:
  subgraph:
    request:
      headers: true
      body: true
    response:
      headers: true
      body: true
```

needs to be

```yaml
coprocessor:
  subgraph:
    all:
      request:
        headers: true
        body: true
      response:
        headers: true
        body: true
```

The available parameters at the Subgraph stage also differ from the Router, which doesn't seem to be covered. It is however shown in the coprocessor property reference.
