### ISSUE TITLE
Add an option to require authentication

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2866]
Right now, rejecting unauthenticated requests requires a rhai script: https://github.com/apollographql/router/blob/dev/docs/source/configuration/authn-jwt.mdx#example-rejecting-unauthenticated-requests

To simplify usage, wee should have a yaml option:

```yaml
authentication:
 jwt:
   jwks: # This key is required.
     - url: https://dev-zzp5enui.us.auth0.com/.well-known/jwks.json
       issuer: <optional name of issuer>

authorization:
  require_authentication: true
```
