### ISSUE TITLE
YAML options for JWT claims validation

### ISSUE THREAD

**Issue by Geal** [apollographql/router#2867]
validating claims requires a rhai script: https://github.com/apollographql/router/blob/dev/docs/source/configuration/authn-jwt.mdx#example-throwing-errors-for-invalid-claims

We should have YAML options to validate them. Example for restricting the list of allowed audiences:

```yaml
authentication:
  jwt:
    jwks: # This key is required.
      - url: https://dev-zzp5enui.us.auth0.com/.well-known/jwks.json
        issuer: <optional name of issuer>
    claims:
      - aud: ["subgraphA", "subgraphB"]
```

which other types of validations should we have? Do we support some kind of predicate? Where is the limit between what we want in yaml, and what should be done in rhai?

**Comment by prasek** [comment]
@garypen audience is in the list of standard claims: https://auth0.com/docs/secure/tokens/json-web-tokens/json-web-token-claims

**Comment by Geal** [comment]
I though about this a bit more, and I think we need:
- both global and per issuer. Example: the `aud` claim could be the same across providers, but `iss` would be different for each IdP (we already have an option to check the issuer though)
- global and per issuer has the same override behaviour we have with global/per subgraph configuration
- require the presence of a claim, without more validation
- exact match for the claim's value
- the claim's value is in a set of accepted values
- the claims value matches a regex

so that would ressemble what we have with header propagation:

```yaml
authentication:
  jwt:
    claims:
      - aud:
        in: ["subgraphA", "subgraphB"]
    jwks: # This key is required.
      - url: https://dev-zzp5enui.us.auth0.com/.well-known/jwks.json
        issuer: <optional name of issuer>
        claims:
          - email:
            matching: "*@example.com"
          - aud:
            is: "subgraphA"
```

We can add more ways to validate claims later, especially for claims like `act` which are not just strings: https://www.rfc-editor.org/rfc/rfc8693.html#name-act-actor-claim
