### ISSUE TITLE
Feature Request: AuthN plugin doesn't support empty prefixes

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#2909]
**Is your feature request related to a problem? Please describe.**

The current AuthN plugin doesn't allow for empty prefixes (e.g. `Authorization: <JWT>`), even when using an empty prefix such as: 

```
authentication:
  jwt:
    jwks:
    - url: file://${env.PWD}/jwks.json
    header_value_prefix: ""
```

It is common to pass tokens without a prefix, and we should ideally support this via an empty prefix value in the configuration. 

**Describe the solution you'd like**

The above YAML snippet should validate the header without a prefix. 

**Describe alternatives you've considered**

No other alternatives exist without a coprocessor.
