### ISSUE TITLE
Why is header propagation in Rhai faster than via the config?

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#3068]
**Describe the solution you'd like**

I'm working on load testing the various extensibility options available, and noticing an odd discrepancy when comparing a relatively simple config vs. Rhai: Rhai is actually better performance-wise when setting a static header to subgraphs. 

Config for reference: 

```yml
supergraph:
  listen: 0.0.0.0:4040
  path: /
  introspection: true
headers:
  all:
    request:
      - insert:
          name: "source"
          value: "config"
```

And the Rhai script: 

```rhai
fn subgraph_service(service,subgraph){
    service.map_request(|request|{
        request.subgraph.headers["source"] = "rhai";
    });
}
```

Data using 1 min load test with 150 rps; order is `[min, mean, 50, 90, 95, 99, max]`

No customizations (e.g. a baseline):
`1.187ms, 4.296ms, 3.615ms, 6.616ms, 7.924ms, 14.763ms, 124.662ms`

Config:
`1.291ms, 6.471ms, 4.036ms, 10.814ms, 12.345ms, 26.019ms, 513.332ms`

Rhai:
`1.191ms, 5.026ms, 3.805ms, 8.685ms, 10.404ms, 16.506ms, 223.113ms`

As you can see - Rhai is about 2ms faster for p95s than the config. 

**Describe alternatives you've considered**

Config is preferably more performant than Rhai, or at least understood why this is the case. 

**Additional context**

Working to get profiler in place for this, however wanted to file this ticket for tracking purposes.
