### ISSUE TITLE
OTEL_SERVICE_NAME not taking effect

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3215]
The env variable `OTEL_SERVICE_NAME` should set the otel service name, however it doesn't.
It looks like we are overriding this here: https://github.com/apollographql/router/blob/dev/apollo-router/src/plugins/telemetry/tracing/datadog.rs#L80

For now users must override the service name in the config via:

```
telemetry:
  tracing:
    trace_config:
      service_name: "${env.OTEL_SERVICE_NAME}"
```

We need to check all exporters when fixing.
