### ISSUE TITLE
Example of JWT forwarding of claims is not secure

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3224]
The example in our documentation for forwarding of claims via header is not secure:
https://www.apollographql.com/docs/router/configuration/authn-jwt#example-forwarding-claims-to-subgraphs

It suggests copying claims into headers that are then sent to subgraphs.
If a user has configured their router to forward all headers to subgraphs then a malicious user could send a header for a claim that they do not have.

A better approach would be to store the claims in graphql extensions.

We should:
- [x] Update the docs to give a secure example using extensions rather than headers.
- [ ] Consider adding the above as an optional default implementation.

```yaml
authorization:
  require_authentication: true
  require_claims: true # Fail the request if there were no claims
  propagate_claims: true #  Propagate claims via extensions
```

By providing a default implementation we can steer users towards something that is secure by default.
