### ISSUE TITLE
Improve / formalize configuration of telemetry / logging / observability / metrics / tracing

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3226]
Currently we have an `experimental_logging` section that we should bring out of experimental and in addition support json formatting options. There have also been several other users asking for much more control over what is output in both spans and logs, so it's maybe time to take a more holistic look.

The things that users have asked us for are:

* Secrets redaction
* The ability to exclude spans from logging output
* The ability to disable attributes on spans
* The ability to only have attributes on spans if headers are present on the root request.
* Optional log events for when there are http or graphql errors
* Optionally set the supergraph span to error if there were graphql errors in the response
* `supergraph` span is wrapped in an `operation` span that follows [semantic conventions](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/instrumentation/graphql/). Existing attributes on supergraph that are from semantic conventions are moved onto the new span.
~~* Log levels are made easier to use. (see below yaml)~~

## Config

Suggest the following format:
```yaml
telemetry:

  tracing:
    common: # Renamed from trace_config
      max_attributes_per_event: 128
      max_attributes_per_span: 128
      max_attributes_per_link: 128
      max_events_per_span: 128
      max_links_per_span: 128
      parent_based_sampler: true
      sampler: always_on
      service_name: router
      service_namespace: "default"
      resource:
        d: e

      # Resources are otel config not represented in the yaml config


    propagation:
      baggage: false
      jaeger: false
      datadog: false
      request:
        header_name: "X-REQUEST-ID"
      trace_context: false
      zipkin: false

    otlp:
      enabled: true
      endpoint: "http://localhost:4317/v1/traces"




  metrics:
    common:
      service_namespace: "default"
      service_name: router
      buckets:
        - 0.1

      resource:
        test: foo
    prometheus:
      enabled: true
      path: /metrics
    otlp:
      enabled: true


  instruments:
    default_attribute_requirement_level: required
    router:
      http.server.active_requests: true
      my_instrument:
        value: unit
        type: counter
        unit: kb
        description: "my description"
        event: on_error
        attributes:

          http.response.status_code: false
          "my_attribute":
            response_header: "X-MY-HEADER"
            default: "unknown"
            redact: "foo"

    supergraph:
      my_instrument:
        value: unit
        event: on_error
        type: counter
        unit: kb
        description: "my description"
    subgraph:
      my_instrument:
        value: unit
        event: on_error
        type: counter
        unit: kb
        description: "my description"


  events:
    router:
      request: true
      response: false
      error: false
      test:
        message: "foo"
        level: info
        attributes:
          http.response.body.size: false


  spans:
    default_attribute_requirement_level: required
    legacy_request_span: true
    # The request span will be disappearing
    # router is the new root span
    router:
      attributes:
        dd.trace_id: false
        http.request.body.size: false
        http.response.body.size: false
        http.request.method: false
        http.request.method.original: false
        http.response.status_code: false
        network.protocol.name: false
        network.protocol.version: false
        network.transport: false
        error.type: false
        network.type: false
        trace_id: false
        user_agent.original: false
        client.address: false
        client.port: false
        http.route: false
        network.local.address: false
        network.local.port: false
        network.peer.address: false
        network.peer.port: false
        server.address: false
        server.port: false
        url.path: false
        url.query: false
        url.scheme: false
        "x-custom1":
          trace_id: datadog
        "x-custom2":

          response_header: "X-CUSTOM2"

          default: "unknown"
        "x-custom3":
          request_header: "X-CUSTOM3"
        "x-custom5":
          response_context: "X-CUSTOM3"
        "x-custom8":
          env: "ENV_VAR"

      #etc...
    supergraph:
      attributes:
        graphql.document: false
        graphql.operation.name: true
        graphql.operation.type: true

        "x-custom":
          query_variable: "arg1"
          default: "unknown"
          redact: ""
        "x-custom2":
          response_body: "arg2"
        "x-custom4":
          request_context: "X-CUSTOM3"
        "x-custom5":
          response_context: "X-CUSTOM3"
        "x-custom6":
          operation_name: string
        "x-custom7":
          operation_name: hash
        "x-custom8":
          env: "ENV_VAR"
      #etc...
    subgraph:

      attributes:

        graphql.federation.subgraph.name: false
        graphql.operation.name: false
        graphql.operation.type: true
        "x-custom":
          subgraph_operation_name: string
          default: "unknown"
        "x-custom2":
          subgraph_response_body: "arg2"
        "x-custom4":
          request_context: "X-CUSTOM3"
        "x-custom5":
          response_context: "X-CUSTOM3"


```

Related is: https://github.com/apollographql/router/issues/1840 which also has some good ideas that have been folded into the above.

## Path forward
This is a fairly large set of changes and will need to be split into several tickets. Let's get agreements that this is the way forward and try and schedule it in as it is a blocker for some users to adoption and could have some major performance improvement ramifications due to reduced logging requriements.

##  Related issues
* #1840 
* #1646 
* #3211 
* #3218 
* https://github.com/apollographql/router/issues/1651
* https://github.com/apollographql/router/issues/3612
* https://github.com/apollographql/router/issues/3208

## Implementation plan
There are a large number of items that need to be tackled. Once the new config structure has been implemented then we can start farming the tasks out to separate people.

### Clean up existing config 
- [x] Clean up endpoint processing. https://github.com/apollographql/router/pull/3950
- [x] Make all exporters have a enabled field rather than using endpoint to activate. https://github.com/apollographql/router/pull/3952
- [x] Deprecate Jaeger (https://github.com/open-telemetry/opentelemetry-rust/issues/995) https://github.com/apollographql/router/pull/3962
- [x] Remove use of Option in telemetry config https://github.com/apollographql/router/pull/3968
- [x] Unify resource handling https://github.com/apollographql/router/pull/4034
- [x] #4043

### New config structure
- [x] Add new Config with fields skipped for schema generation and serialization.
- [x] Create documentation for new tracing functionality.

### Spans
- [x] See if late binding can affect log message attributes (Jeremy)
  - It does not, only log messages that are after the field has been set will be affected.
  - Spans and events are affected.
- [x] #4086
- [x] #4096
- [x] #4081
- [x] #4082
  - [ ] RouterService
  - [ ] SupergraphService
  - [ ] SubgraphService * maybe descope
- [ ] #4083
- [x] #4084
- [x] #4085

### Tracing
- [x] Add stdout exporter
  
### Testing
- [x] #4216
- [x] #4217
 
  
### Logging
- [x] Implement stdout logger
  - [ ] Implement OTEL format
  - [x] Implement JSON format
  - [x] Implement text format
  
### Instruments
- [x] #4319

### Events
- [x] #4320

**Comment by bnjjj** [comment]
I suggest to use `format` in that way:

```yaml
format:
    json:
      location: true | false
      filename: true | false
      line_number: true | false
      spans: true | false
    # text:
    #   location: true | false
    #   filename: true | false
    #   line_number: true | false
    #   spans: true | false
```

it's also related to the discussion https://github.com/apollographql/router/discussions/1961
