### ISSUE TITLE
Support passing Apollo Key/GraphRef via Config File

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#3264]
**Is your feature request related to a problem? Please describe.**

The router currently requires that I pass an APOLLO_KEY and APOLLO_GRAPH_REF environment variable to start, however in some situations I would like to pass it as a static value within a configuration or another environment variable name, or as passing from a file's contents. Currently this isn't supported, however. 

The YAML implementation supports both passing values by environment variable and passing file contents directly, which would address my concerns. 

**Describe the solution you'd like**

A new configuration option to pass the APOLLO_KEY/GRAPH_REF, such as: 

```yml
supergraph:
  apollo_key: 1234
  apollo_graph_ref: my-supergraph@prod
```

Which would default to: 
```yml
supergraph:
  apollo_key: ${env.APOLLO_KEY}
  apollo_graph_ref: ${env.APOLLO_GRAPH_REF}
```

To make it a non-breaking change. 

**Describe alternatives you've considered**

* Using the existing environment variables and populating them via a prelaunch script (e.g. sourcing a .env file) 

**Additional context**

While this feature would be relatively uncommon, it would be helpful for some organizations.
