### ISSUE TITLE
Header propagation not reflecting

### ISSUE THREAD

**Issue by darmie** [apollographql/router#3325]
**Describe the bug**
I have set an header to be propagated in the router config, but my graphql service is not capturing it. 

**To Reproduce**
1. Create yaml file with the config below 
```yml
headers:
  all:
    request:
      - propagate:
          named: "Authorization"

subgraphs:
  accounts:
    routing_url: http://localhost:3000/query
    schema:
      subgraph_url: http://localhost:3000/query
  payments:
    routing_url: http://localhost:3001/query
    schema:
      subgraph_url: http://localhost:3001/query
```
2. Run `./router --dev --supergraph supergraph.graphql --log debug` in terminal
3. My `account` service (written in golang) could only capture the headers below:
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
