### ISSUE TITLE
Consider adding jwt validation config

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3329]
Follow up to #3224 
Consider adding the following functionality to JWTs so that users don't have to write a rhai script.
```
authentication:
  jwt:
    require_authentication: true
    require_claims: # Fail the request if claims were missing
      - a
      - b 
    propagate_claims: http_headers | graphql_extension # Propagate the claims as http headers or graphql extensions.
```
This needs design though.
