### ISSUE TITLE
AWS X-Ray traceId handling in router

### ISSUE THREAD

**Issue by laszlorostas** [apollographql/router#3445]
We want to examine the router as a trace in aws x-ray. Currently, only one format of traceid is possible for the router.

 It would be nice if, say, a custom traceid solution could be brought via a rhai script

**Comment by bnjjj** [comment]
Have you ever try to use `request` propagation mentioned [here](https://www.apollographql.com/docs/router/configuration/tracing#propagation) ?

**Comment by laszlorostas** [comment]
I know it, but as far as I know, the traceid format that the router generates for them is the same. But a completely unique traceId format, such as UUID or X-ray format, is discarded by the router.

**Comment by abernix** [comment]
I'm curious if @bnjjj was referring to the section of the documentation that suggests using a custom header, which exists on that page (link to [highlighted part](https://www.apollographql.com/docs/router/configuration/tracing/#propagation:~:text=%23%20If%20you%20have,trace%2Did)):

```yaml
      # If you have your own way to generate a trace id and you want to pass it via a custom request header
      request:
        header_name: my-trace-id
```

For example, what if you did:

```yaml
      # If you have your own way to generate a trace id and you want to pass it via a custom request header
      request:
        header_name: X-Amzn-Trace-Id
```

Is that sufficient?
