### ISSUE TITLE
Restructure limits config

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3519]
Current limits config could be simplified. It's also not clear to users that `warn_only` only applies to operation limits.
```yaml
limits:
  max_depth: 1
  experimental_http_max_request_bytes: 2000000
  warn_only: true
  max_root_fields: 1
  parser_max_tokens: 15000
  parser_max_recursion: 4096
  max_height: 2
  max_aliases: 2
```

Suggest:
```yaml
limits:
  request:
    max_size: 2000000
  operation:
    warn_only: true
    max_depth: 1
    max_root_fields: 1
    max_height: 2
    max_aliases: 2
  parser:
    max_tokens: 15000
    max_recursion: 4096
```
