### ISSUE TITLE
Add datadog format to request header propagation

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3538]
```
telemetry:
  tracing:
    propagation:
      request: 
        header_name: 'my_header'
        format: datadog
```
