### ISSUE TITLE
JWT authentication configuration example is incorrect

### ISSUE THREAD

**Issue by garypen** [apollographql/router#3571]
https://www.apollographql.com/docs/router/configuration/authn-jwt/#configuration-options

```
authentication:
  jwt:
    jwks: # This key is required.
      - url: https://dev-zzp5enui.us.auth0.com/.well-known/jwks.json
      issuer: <optional name of issuer>

   # These keys are optional. Default values are shown.
   header_name: Authorization
   header_value_prefix: Bearer
```

should be:
```
authentication:
  router:
    jwt:
      jwks:
        - url: https://dev-zzp5enui.us.auth0.com/.well-known/jwks.json
        issuer: <optional name of issuer>

      # These keys are optional. Default values are shown.
      header_name: Authorization
      header_value_prefix: Bearer
```
