### ISSUE TITLE
Proposal: Built-In Required HTTP Headers Plugin

### ISSUE THREAD

**Issue by oliverjumpertz** [apollographql/router#3616]
**Is your feature request related to a problem? Please describe.**

There have been a few requests for a built-in way to check for required HTTP headers in Router in the past. Next to that, offering a built-in way to do so would also reduce the need for people to build custom binaries of Router because they have to implement such logic themselves.

**Describe the solution you'd like**

A plugin could be added that allows users to specify required headers within their Router config. Such a plugin could support multiple ways of validation, though, which is why I, at the moment, see two ways to implement such a plugin:

**Option 1 (Basic version):**

A basic version would do nothing else than verify the presence of a configured header but not validate its contents in any way. Imho, it makes sense to include a new parent section, "validation", for clarity and possible future ways to configure validation within Router.

As for the validation, the easiest way to do this would probably be to just let users pass in the exact headers they want and test, on each request, whether these headers are present. Below is a possible way to configure such a basic version of the plugin:

```yaml
validation:
  http:
    required_headers:
      - header-one
      - header-two
      - etc...
```

The implementation of such a plugin would be relatively straightforward.

**Option 2 (Advanced):**

A second way to implement such a plugin would be to allow for more granular control over header validation. Instead of only defining required headers, users could be enabled to also test any header for specific values.

One example of where header value validation could be useful is client identification headers that follow a particular scheme (like requiring a URI and not a random string to be passed). In this hypothetical case, a combination like `Client-Name: foobar` would be insufficient while `Client-Name: cid:web:ssr` would be valid.

An example config could look like this:

```yaml
validation:
  http:
    headers:
      # The required section tests for both the presence of the header and validates its value if a pattern is set
      required:
        # Tests for presence and validates the value
        - name: client-name
          pattern: cid:([a-zA-Z]+[a-zA-Z1-9]*):([a-zA-Z]+[a-zA-Z1-9]*)
        # Only tests for presence
        - name: client-version
        # Tests for presence and for a constant value
        - name: random-header
          value: foobar
      # The optional section only validates a header's value if that header is present within a request
      optional:
        # Only validates the header's value if present
        - name: optional-header
          pattern: ([a-zA-Z]+[a-zA-Z1-9]*)
        - name: another-optional-header
          value: bar      
```

This version is a little more difficult to implement. While testing for presence is straightforward, working with regular expressions, which can potentially lead to long-running code requires more care to implement. It has to be discussed whether a regular expression is really the right tool or whether there should be an allowed limit of complexity for patterns to prevent Router performance from radically degrading when complex patterns are configured by users.

**Describe alternatives you've considered**

./.

**Additional context**

./.

**Comment by o0Ignition0o** [comment]
I really like approach #2!

We could also start only with 

```
validation:
  http:
    required:
      - name: header-name
```

and iterate on validation afterwards!

Does a `validation` key at the root look good to you? or would you suggest this key ends somewhere else in the router configuration ?

**Comment by oliverjumpertz** [comment]
I had another thought about this, and I came up with a probably nicer configuration approach, as follows:

```yaml
validation:
  http:
    headers:
      # Tests for presence and validates the value
      - name: client-name
        required: true
        pattern: cid:([a-zA-Z]+[a-zA-Z1-9]*):([a-zA-Z]+[a-zA-Z1-9]*)
      # Only tests for presence
      - name: client-version
        required: true
      # Tests for presence and for a constant value
      - name: random-header
        required: true
        value: foobar
      # Only validates the header's value if present
      # absence of the required attribute makes these attributes optional by default
      - name: optional-header
        pattern: ([a-zA-Z]+[a-zA-Z1-9]*)
      - name: another-optional-header
        value: bar      
```

It saves a whole level of indentation, which is probably a little more pleasing to the eyes.

And yes, a first version could only test for the presence of a header. Adding a pattern validator afterward seems like a great second iteration to me. :)

**Comment by oliverjumpertz** [comment]
I'd love to extend the proposal a little and add a severity level to the config.

This severity could have one of two values:
1. WARN
2. ERROR (default)

The operation limits also allow for a grace period (while migrating), where actual errors are only recorded as warnings, such that the operators of the Router get a chance to set a timespan where clients get the chance to take appropriate actions.

In this case, we could do the same thing, such that clients get a chance to implement the required headers or change their values.

I'd propose the default severity to be ERROR. If someone explicitly marks a validation as WARN, Router won't reject a request but issue a warn log/span in this case.

This should make migrations much easier for users and leave client teams a little air to breathe.

The config would look like this, in this case:

```yaml
validation:
  http:
    headers:
      # The required section tests for both the presence of the header and validates its value if a pattern is set
      required:
        # Tests for presence and validates the value
        - name: client-name
          pattern: cid:([a-zA-Z]+[a-zA-Z1-9]*):([a-zA-Z]+[a-zA-Z1-9]*)
          # doesn't reject the request but issues a warning instead
          severity: WARN
        # Only tests for presence. Default severity is ERROR.
        - name: client-version
        # Tests for presence and for a constant value
        - name: random-header
          value: foobar
      # The optional section only validates a header's value if that header is present within a request
      optional:
        # Only validates the header's value if present
        - name: optional-header
          pattern: ([a-zA-Z]+[a-zA-Z1-9]*)
          # IF the header is present, and IF the pattern does NOT match, issues a warning
          severity: WARN
        - name: another-optional-header
          value: bar      
```
