### ISSUE TITLE
Need the ability to serve on multiple paths

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3631]
Some users have clients that are using combinations of `/` and `/graphql`.
Changing these clients isn't an option, so it'd be helpful you could specify multiple paths to listen on.

Suggest that we pull this stuff out of supergraph into a server section:

```yaml
server:
  listen:
  paths:
    - /
    - /graphql
```
