### ISSUE TITLE
Experimental Redis query plan cache slows query planning after being up for days

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3639]
A router with redis query planning enabled is taking a long time to plan queries. As much as 10s.

```
      query_planning:
        experimental_cache:
          in_memory:
            limit: 512
          redis:
            urls:
            - ${env.REDIS_URL}
        warmed_up_queries: 100
```

Restarting the router seems to fix the issue for a while.

In addition, disabling Redis seems to fix the issue.

Affects 1.26.0
