### ISSUE TITLE
`rover dev` ignores `federation_version` value in `--supergraph-config`

### ISSUE THREAD

**Issue by parkerholladay** [apollographql/router#3714]
When using the following config:

```yaml
# supergraph.yaml
federation_version: =2.3.4

subgraphs:
  subgraph-a:
    ...
  subgraph-b:
    ...
```

and running `rover dev --supgraph-config ./supergraph.yaml ...`, the local graph always gets composed with the latest version of federation (currently `2.5.1`).

**Expected behavior**
It should use federation `2.3.4` as specified.

**Output**
> ⚠️  Do not run this command in production! ⚠️  It is intended for local development.
👀 watching ./router.yaml for changes
🛫 starting a session with the 'subgraph-b' subgraph
🛫 starting a session with the 'subgraph-a' subgraph
🎶 composing supergraph with Federation v2.5.1
🚀 your supergraph is running! head to http://localhost:4000/graphql to query your supergraph
🎶 composing supergraph with Federation v2.5.1
✅ successfully composed after adding the 'subgraph-a' subgraph

**Desktop**
 - OS: MacOS, Windows, Linux
