### ISSUE TITLE
Improve error handling for JWKS with missing alg

### ISSUE THREAD

**Issue by andyvajda** [apollographql/router#3853]
**Describe the bug**
When a JWKS url is used in the router authentication config that includes keys without an "alg" field, none of the keys will be imported.  Instead one, or both of the following errors will be thrown:
```
ERROR: could not get url
ERROR: could not create JWKS from url content
```

**To Reproduce**
Configure router with JWKS

**Expected behavior**
Error response indicates why JWKS was unable to load.  
Possibly skip loading the offending keys while loading the others.

@flyboarder

**Comment by garypen** [comment]
I don't think the problem is because an `alg` field is missing from the JWKS entries, but cause an `alg` field is specified which isn't supported by our underlying `jsonwebtoken` crate. For example: `ES512`

I've gone with an approach, #3922, which leverages our existing support for specifying a list of algorithms to use via configuration for each JWKS url. I chose this approach because it naturally aligns with the existing functionality and avoids any requirement to create extra configuration.

Here's an example
```
authentication:
  router:
    jwt:
      jwks: # This key is required.
        - url: https://my-jwks-url
          algorithms: [ "HS256", "HS384", "HS512", "ES256", "ES384", "RS256", "RS384", "RS512", "PS256", "PS384", "PS512", "EdDSA"]
```

In this case, I'm telling the router to support all the algorithms supported by our underlying `jsonwebtoken` crate. This list is now used to specify a retention list from the JWKS retrieved from the specified url. This means that if the source JWKS contains an algorithm not in the `algorithms` list, it will be ignored at download time as well as during execution time.
