### ISSUE TITLE
Open Telemetry spans not reporting Errors to Datadog

### ISSUE THREAD

**Issue by sbehrends** [apollographql/router#3872]
**The bug**

We are running `apollographql` self-hosted to route our supergraph.

We started using `v1.26.0` and setup our monitoring based on the telemetry, traces, and spans being **reporting by the Router to Datadog**.

Recently we **upgraded to `v1.30.0`** and we discovered that some spans are reporting different content, **specially around error tagging**.

We are mostly interested in being able to measure errors on subgraphs responses. For such, we are monitoring the trace called `apollo_router subgraph` that contains useful infromation like the query, operation, and subgraph name that failed.

I checked how the router was reporting this errors for each version since `v1.26.0`, and looks like this behavior changed with the last release on `v1.30.0`.

**To Reproduce**
1. Run `apollographql` with `datadog` telemetry on.

```
telemetry:
  tracing:
    datadog:
      endpoint: ${env.DD_AGENT_HOST}:8126
```

2. Run queries against a Subgraph that would return an error.
3. Check reported Spans in Datadog

**Expected behavior**
`apollo_router subgraph` to report errors when a subgraph request fails. Like it was happening on `v1.29.0`

**Output**
Below you will find Router configuration, and screenshots of `v1.29.0` vs `v1.30.0`.

![Screenshot 2023-09-21 at 18 19 46](https://github.com/apollographql/router/assets/327827/b2aab909-ddd7-4265-adc7-b0f9e9e12604)

**Additional context**

The Subgraph returning the errors on my example is an adoption of `pandas` service from this [example](https://github.com/apollographql/supergraph-demo-fed2/tree/main/subgraphs/pandas). It returns either an invalida schema response or just `throw GraphQLError`.

For reference, here is the router full configuration

```
supergraph:
  listen: 0.0.0.0:3000
  introspection: true
  path: /graphql

health_check:
  listen: 0.0.0.0:8088
  enabled: true

sandbox:
  enabled: true

homepage:
  enabled: false

include_subgraph_errors:
  all: true

plugins:
  experimental.expose_query_plan: true

cors:
  allow_any_origin: true

headers:
  all: # Header rules for all subgraphs
    request:
      - propagate:
          matching: .*

telemetry:
  tracing:
    datadog:
      endpoint: ${env.DD_AGENT_HOST}:8126

```
