### ISSUE TITLE
Document how to specify ws(s):// protocol with Subscription Endpoint 

### ISSUE THREAD

**Issue by bneigher** [apollographql/router#3875]
**Describe the solution you'd like**
I'm not having any success in finding the router config needed to set the Subscription Endpoint when running the router locally

<img width="555" alt="image" src="https://github.com/apollographql/router/assets/4627728/93bb6b4f-86cd-4aef-984c-a4a0d792f3fd">

**Additional context**

```yml
health_check:
  listen: 0.0.0.0:8088
  enabled: true

# https://www.apollographql.com/docs/router/configuration/subgraph-error-inclusion/
include_subgraph_errors:
  all: true

subscription:
  enabled: true
  
 sandbox:
  enabled: true

supergraph:
  introspection: true
  listen: 0.0.0.0:80
  
 homepage:
  enabled: false 
  
```

Generally, this config is not letting me edit through the sandbox, so I would assume a setting on the yml is needed... desired value is something like:  `ws://0.0.0.0:80`
