### ISSUE TITLE
Add support for compression for otlp exporter

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#3916]
Since otel 0.20 the otlp exporter supports compression. Let's add a config option for this.

```yaml
  tracing: 
    otlp: 
      compresson: gzip
```
