### ISSUE TITLE
ERROR could not create router: schema error: GraphQL parser error - native Rust plugin

### ISSUE THREAD

**Issue by sheikhahmed1309** [apollographql/router#4147]
i'm using the Apollo Router version 1.30.0 to create plugin, but i got error when run it with 
`cargo run -- -s ./supergraph.graphql -c ./router.yaml`
the error
`2023-11-05T13:09:05.381526Z  ERROR could not create router: schema error: GraphQL parser error: at index 112280: parser recursion limit reached
Error: could not create router: schema error: GraphQL parser error: at index 112280: parser recursion limit reached`

when i using the binary router it's work

also router v1.33.2 throw the same error on both sides (binary and rust app)

macOS 13.5.2

router.yaml file

```

supergraph:
  listen: 0.0.0.0:4000
  introspection: true

sandbox:
  enabled: true

homepage:
  enabled: false


plugins:
  example.hello_world:
    name: asd
```
