### ISSUE TITLE
bug: multiple header propagation rules cause duplicate header values

### ISSUE THREAD

**Issue by nmoutschen** [apollographql/router#4312]
**Describe the bug**

When using a router configuration that matches more than one on a header name for propagation (e.g. named and matching), the Router will duplicate those headers as many times as there are matching rules.

**To Reproduce**
1. Run a router with the following config:

```
headers:
  all:
    request:
    - propagate:
        named: x-my-header
    - propagate:
        matching: ".*"
telemetry:
  experimental_logging:
    when_header:
      - name: x-my-header
        match: .*
        headers: true
```

3. Send a request that contains one `x-my-header` value
4. See that the subgraph receives two `x-my-header` entries with the same value.

**Expected behavior**

The Router should not duplicate header values, but should conserve multi-value headers when configured to propagate them to a subgraph, no matter if a header name matches mutliple entries.

**Output**

N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.34.1

**Additional context**

The [current logic](https://github.com/apollographql/router/blob/dev/apollo-router/src/plugins/headers.rs#L296) goes through all header propagation first, then scan all headers in a request, which causes the duplication.

While this applies for propagation, we would need to decide on a strategy for prioritising propagation vs insertion vs removal.
