### ISSUE TITLE
callback: allow specifying separate URLs

### ISSUE THREAD

**Issue by nmoutschen** [apollographql/router#4318]
**Is your feature request related to a problem? Please describe.**

I'd like to provide a different URL for subscription callback URLs compared to the actual port **and** path used to listen for callbacks.

**Describe the solution you'd like**

Add the ability to specify a different path for the router.

Right now, you can set a custom `public_url` for a subscription, but not the path. As a result, the Router would listen to the same path as the one provided.

**Describe alternatives you've considered**

Create a custom plugin that would listen on the specific path and redirect internally.

**Additional context**

**Comment by bnjjj** [comment]
```yaml
subscription:
  enabled: true
  mode:
    preview_callback:
      public_url: https://example.com:4000 # The router's public URL, the one on which your subgraphs can have access to the Router
      listen: 127.0.0.1:4000 # The IP address and port the router will listen on for subscription callbacks, for security reasons it might be better to expose on another port that is only available from your internal network
      public_path: /callback # The public path of the router's callback endpoint (if you're doing some redirections)
      listen_path: /callback # The path of the router's callback endpoint
      heartbeat_interval: 5s # Optional (default: 5secs)
      subgraphs: # The list of subgraphs that use the HTTP callback protocol
        - accounts
 ```

Something like this @nmoutschen ? Do you have better suggestions ? cc @BrynCooke

**Comment by nmoutschen** [comment]
> Something like this @nmoutschen ?

Oh yes! I think something like just allowing paths in the `public_url` would be a good alternative too

**Comment by bnjjj** [comment]
@nmoutschen I would like to keep the `listen` and `public_path` separated because we have that kind of patterns like everywhere in the router config, for example for `supergraph` config

**Comment by bnjjj** [comment]
Ok I think I misread the configuration, what's currently a pattern in the router configuration is combination of `listen` + `path`. But `public_url` is different and is an url so I think you're right, it might be better to put the path directly in public_url.

```yaml
subscription:
  enabled: true
  mode:
    preview_callback:
      public_url: https://example.com:4000/callback # The router's public URL, the one on which your subgraphs can have access to the Router
      listen: 127.0.0.1:4000 # The IP address and port the router will listen on for subscription callbacks, for security reasons it might be better to expose on another port that is only available from your internal network
      path: /callback # The path of the router's callback endpoint
      heartbeat_interval: 5s # Optional (default: 5secs)
      subgraphs: # The list of subgraphs that use the HTTP callback protocol
        - accounts
``` 

And then it will become mandatory to specify the path on the public_url
