### ISSUE TITLE
NewRelic error trace and spans dashboard support

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#4336]
**Is your feature request related to a problem? Please describe.**
NewRelic uses a non-standard format for tracking error dashboards on traces. It requires that you set a span attribute of `otel.status_code` which it uses to track error counts

https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/view-your-data/opentelemetry-errors-page/

**Describe the solution you'd like**
Add the ability to configure this property to be set or include it in all spans on either HTTP or GraphQL errors

**Describe alternatives you've considered**
We could customize an Otel collector between the Router and New Relic, however directly configuring Router to send info directly to NR does work minus this one feature:  https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app/#review-settings

**Comment by bnjjj** [comment]
I think having that kind of configuration:

```yaml
telemetry:
  instrumentation:
    spans:
      supergraph:
        attributes:
          "span.kind": "server"
          "otel.status_code":
            condition:
              - exists:
                  response_body: ".errors[0].message"
            value: "ERROR"
```

woud make sense
