### ISSUE TITLE
document when_experimental_header for logging

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#4342]
Related to https://github.com/apollographql/router/discussions/1961#discussioncomment-7768433

The previous configuration has been moved to another section in configuration. It's not documented we should document it.

```yaml
telemetry:
  exporters:
    logging:
      experimental_when_header:
        - name: "content-type"
          match: ".*"
          headers: true
          body: true
```
