### ISSUE TITLE
Ability to automatically switch the logging format depending on the terminal

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#4369]
It would be great to have the ability to configure both formats:

```yaml
stdout:
        enabled: true
        format:
          text:
            display_span_list: true
            display_target: false
            display_resource: false
          json:
            display_span_list: true
            display_target: false
            display_resource: false
```

and automatically switch to json if it's a non interactive terminal

**Comment by BrynCooke** [comment]
We need to consider that there will be other formats in future not just json/text.

Suggest that we add an adjacent `tty_format` configuration key that uses the same datastructure as the existing `format` key.


```yaml
telemetry:
  exporters:
    logging:
      stdout:
        enabled: true
        format: 
          json:
            ...
        tty_format: 
          text:
            ...
```
