### ISSUE TITLE
Add support for graphql custom attributes on router span

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#4404]
We would like to also provide `graphql` attributes at the router level like we did for supergraph level [here](https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/standard-attributes#supergraph). Main difference, there are all disabled by default
```yaml
telemetry:
    spans:
      router:
      supergraph:
        attributes:
          graphql.document: true # default: false
```
