### ISSUE TITLE
Inserted headers from the router should not be included in the access-control-allow-headers OPTIONS response.

### ISSUE THREAD

**Issue by Xavius1** [apollographql/router#4420]
**Describe the bug**
Hello,

To prevent someone from calling my subgraphs directly, I use a header that I inject from the router, and I control its existence and value when creating the context in my subgraphs. This is obviously not the only security measure, but it seems important to me.

It works very well, except that I realized that on OPTIONS requests, the name of this header appears in the `access-control-allow-headers` part among all the other header names that I transmit from the router to the subgraphs.

I searched in the documentation, but I couldn't find my answer. I think there is a bug because the router should not return the names of headers that it injects itself and that are not managed by the client.

**To Reproduce**
Router config :
```
headers:
  all:
    request:
      - propagate:
          named: 'x-app-name'
      - propagate:
          named: 'x-app-version'
      - propagate:
          named: 'x-app-token'
      - propagate:
          named: 'x-act-as-user'
      - propagate:
          named: 'authorization'
      - propagate:
          named: 'user-agent'
      - propagate:
          named: 'accept-language'
      - insert:
          name: 'hidden-header'
          value: 'router'
```

Run the router :
```
./router --config router.yaml --supergraph supergraph.gql
```

OPTIONS response from the browser :
```
HTTP/1.1 200 OK
access-control-allow-origin: https://studio.apollographql.com
access-control-allow-methods: GET,POST,OPTIONS
access-control-allow-headers: authorization,content-type,hidden-header,x-app-name,x-app-version
allow: GET,HEAD,POST
```

**Expected behavior**
It should returns without `hidden-header` :
```
access-control-allow-headers: authorization,content-type,x-app-name,x-app-version
```

Tested today on the latest version of the router.
