### ISSUE TITLE
Add all baggage items as span tags

### ISSUE THREAD

**Issue by danpayne17** [apollographql/router#4425]
**Is your feature request related to a problem? Please describe.**
You can specify baggage item(s) to be added as span tags in router yaml config, but this requires us to release a new router anytime the FE adds a new baggage item.

**Describe the solution you'd like**
We want to be able to support arbitrary baggage items so that the FE is free to add any baggage item they want in a request to the graph and the baggage item will automatically be added as a span tag without requiring a new router release. An approach that would work for us is router config with a new router baggage selector (as opposed to the existing baggage standard attribute):
```
telemetry:
  instrumentation:
    spans:
      router:
        attributes:
          baggage: true
```
If true, ALL baggage items would be added as span tags

**Describe alternatives you've considered**
We are manually adding baggage items to router yaml config as standard attributes but this requires a new router release every time the FE adds a new baggage item and we want to decouple:
```
telemetry:
  instrumentation:
    spans:
      router:
        attributes:
          client-visit-id:
            baggage: client-visit-id
```

**Additional context**
N/A
