### ISSUE TITLE
fix hpa targets ordering

### ISSUE THREAD

**Issue by cyberhck** [apollographql/router#4435]
**Describe the solution you'd like**
When adding a HPA, with memory and cpu limits, then argoCD application appears OutOfSync.

This is because of not consequent sorting the live manifest and the desired manifest.

![image](https://github.com/apollographql/router/assets/3640284/575b8cc4-0ad5-42e0-b5ac-ef0005c9bd29)

**Additional context**
in theory, this is actually a k8s issue: https://github.com/kubernetes/kubernetes/issues/74099 but for this to get solved and get pached to everyone will take forever, so we could just sort it ourselves in this chart right here.

**Comment by garypen** [comment]
Interesting bug. The k8s issue that you reference implies this is not a problem with HPA v2. Our chart tries to use v2 if available. Could you please let us know what version of k8s you are encountering this problem with?

**Comment by jmateusppay** [comment]
We are having this problem in version 1.25 (EKS environment)

**Comment by cyberhck** [comment]
we're using v1.24.17-gke.2347000 version of k8s

**Comment by cyberhck** [comment]
@garypen , we're using: v1.24.17-gke.2347000 gke K8S,

I can see the version of chart we're using is old, but it's hpa's choice is exactly the same:

current main branch:
```
{{- if .Values.autoscaling.enabled }}
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion -}}
```

my version:
```
{{- if .Values.autoscaling.enabled }}
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion -}}
```

**Comment by cyberhck** [comment]
On the server side however, I do see hpa uses the following configuration:
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  ...
  name: apollo-router
spec:
  maxReplicas: 15
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apollo-router
```
