### ISSUE TITLE
Otlp traces not send if APOLLO_ROUTER_LOG = warn | error

### ISSUE THREAD

**Issue by marcantoine-bibeau** [apollographql/router#4461]
**Describe the bug**
Otlp traces not send if APOLLO_ROUTER_LOG = warn | error

**To Reproduce**
1. Set Environment variable APOLLO_ROUTER_LOG to `warn` or `error`
2. Submit request 
3. No traces/spans sent to collector

1. Set Environment variable APOLLO_ROUTER_LOG to `info` or `debug`
2. Submit request 
3. Traces/spans sent to collector

**Expected behavior**
Traces/spans should always be sent to collector

**Desktop (please complete the following information):**
 - OS: Kubernetes
 - Version: 1.37.0

**Additional context**
```
      telemetry:
        exporters:
          tracing:
            common:
              resource:
                service.name: gqlfed-router
            otlp:
              enabled: true
              endpoint: grpc://my-collector-service:4317
            propagation:
              baggage: true
              datadog: true
```
