### ISSUE TITLE
Unable to include trace_id in logs.

### ISSUE THREAD

**Issue by darrelldraney** [apollographql/router#4482]
Using router version 1.37.0 with the below configuration to include trace_id in logs for correlation with traces returns an error.

```
telemetry:
  exporters:
    logging:
      stdout:
        enabled: true
  instrumentation:
    spans:
      default_attribute_requirement_level: recommended
      mode: spec_compliant
      router:
        attributes:
          trace_id: true
```

Error on start up is:

```
{
    "timestamp": "2024-01-15T23:25:35.295622820Z",
    "level": "ERROR",
    "message": "Not connected to GraphOS. In order to enable these features for a self-hosted instance of Apollo Router, the Router must be connected to a graph in GraphOS (using APOLLO_KEY and APOLLO_GRAPH_REF) that provides a license for the following features:\n\nConfiguration yaml:\n* Advanced telemetry\n  .telemetry..spans.router\n\nSee https://go.apollo.dev/o/elp for more information.",
    "target": "apollo_router::state_machine",
    "resource":   {}
}

```

This seems to indicate that including the trace_id in logs requires a license. The documentation seems to indicate custom attributes requires a license:
 
>Custom attributes for spans via selector is an Enterprise Feature that requires a [GraphOS Enterprise plan](https://www.apollographql.com/docs/graphos/enterprise/).

Is this a bug, or Is trace_id considered a custom attribute, and there is no way to correlate logs with traces without a license?
