### ISSUE TITLE
Provide router config to disable http GET altogether for graphql requests

### ISSUE THREAD

**Issue by theJC** [apollographql/router#4492]
**Describe the solution you'd like**
Provide router config to disable http GET for graphql requests, we only support POST GraphQL requests.

**Describe alternatives you've considered**
Adding prevention from the various network ingresses to our router executable.  There are various ways traffic flows, so this is more complicated and not the same for various ingress pathways, much simpler if it can be wholesale disabled right at Router.

**Additional context**
Would still also want to support CORS OPTION requests to be served as well.

example configuration proposal:

```
supergraph:
  # The path for GraphQL execution
  # (Defaults to /)
  path: /graphql
  methods: GET  # default GET,POST
```
