### ISSUE TITLE
baggage item selector doesn't work if more than one item in bag

### ISSUE THREAD

**Issue by danpayne17** [apollographql/router#4538]
**Describe the bug**
When there is more than one baggage item in a baggage header, the baggage selector is unable to select it

**To Reproduce**
1. Configure router with a router attribute that selects a baggage item:
```
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant
      router:
        attributes:
          client-visit-variantuuids:
            baggage: client-visit-variantuuids
```
2. Submit request with the following baggage header with two baggage items:
```
baggage: client-key1=value1,client-visit-variantuuids=foo|bar
```
3. Observe that no `client-visit-variantuuids` tag is applied to span
4. Rerun the request but with only the following baggage header:
```
baggage: client-visit-variantuuids=foo|bar
```
5. Observe that the tag is applied to span as expected

**Expected behavior**
According to baggage specification (https://w3c.github.io/baggage/) a baggage header may contain more than one baggage item and therefore I would expect the baggage selector to work regardless of number of items in baggage header

**Output**
If applicable, add output to help explain your problem.

**Desktop (please complete the following information):**
 - OS: MacOS 13.6.3
 - Router Version: 1.37.0

**Additional context**
We are using DataDog

**Comment by bnjjj** [comment]
@danpayne17 I wasn't able to reproduce locally. Do you also send traceparent header with a trace context and the sampling flag set to 1 ?

**Comment by danpayne17** [comment]
@bnjjj no, we don't send the traceparent header. I just confirmed that we're still seeing this issue BUT I've noticed that the order of the baggage items is significant. If there are two items, and only the second item is configured to be used as a span tag attribute, then it doesn't work. If there are two items where only the first item is configured to be used as a span tag attribute, then it DOES work. So it seems that it only breaks when the desired baggage item is preceded by one not configured to be used as a span tag attribute.

Given this config:
```
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant
      router:
        attributes:
          client-visit-variantuuids:
            baggage: client-visit-variantuuids
```

This DOES work:
```
curl -X "POST" "https://<router>/graph" \
     -H 'baggage: client-visit-variantuuids=12345|78966,client-key4=value4' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{"query": "query myqyery{viewer{id}}"}'
```

And this does NOT work:
```
curl -X "POST" "https://<router>/graph" \
     -H 'baggage: client-key4=value4,client-visit-variantuuids=12345|78966' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{"query": "query myqyery{viewer{id}}"}'
```
