### ISSUE TITLE
Add ability in `telemetry.instrumentation.spans` to add static attribute on a specific span

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#4561]
Something like

```yaml
telemetry:
  instrumentation:
    spans:
      router:
        attributes:
          "my_attribute": "constant_value"
```
