### ISSUE TITLE
Configure global auth checks for all operations

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#4562]
## **Is your feature request related to a problem? Please describe.**
We are using the new [Router JWT auth feature](https://www.apollographql.com/docs/router/configuration/authorization#requiresscopes) to validate scopes on each operation incoming to the supergraph. If we want EVERY operation to have at least the scope `WEB` we need to annotate and update all the subgraphs in the supergraph to include the `@requiresScopes` directive, make sure they have configured it properly, and make sure all future additions also have this directive, or use a coprocessor, or Rhai script

When you have possibly 100+ subgraphs with 20+ teams this doesn't scale as easily and a coprocessor or Rhai requires some extra setup for things already included in other traffic gateways as built-in features like [Istio with custom rules](https://istio.io/latest/docs/tasks/security/authorization/authz-jwt/)

## **Describe the solution you'd like**
Add a new YAML config to apply some global scope check to all operations. We should reuse the same and/or logic of the directive for flexibility

```yaml
authorization:
  directives:
    enabled: true
    global_checks:
      scopes:
          # This would be [(WEB) OR (APP && CUSTOMER_SERVICE)]
          - "WEB"
          - "APP CUSTOMER_SERVICE" 
```

If this is updated the `global_checks` could also contain global `@policy` rules

This is basically what the `reject_unauthorized` already does with a different syntax:

```yaml
authorization:
  directives:
    enabled: true
    global_checks:
      authenticated: true
```

So a full pontential option could be

```yaml
authorization:
  directives:
    enabled: true
    global_checks:
      authenticated: true
      scopes:
        - "WEB"
        - "APP CUSTOMER_SERVICE"
      policy:
        - "roles:support"
```

## **Describe alternatives you've considered**
We could use coprocessors or Rhai scripts to achieve this but the Router is already doing so much of the processing including an option to make sure all requests have a token, this could be a small ease-of-use feature
