### ISSUE TITLE
After update to newest version of Apollo otlp tracing export timeouts

### ISSUE THREAD

**Issue by voslartomas** [apollographql/router#4564]
**Describe the bug**

We used to have this configuration

```yaml
telemetry:
  tracing:
    trace_config:
      service_name: "..."
      service_namespace: "..."
      parent_based_sampler: true
    propagation:
      baggage: true
    otlp:
      endpoint: https://api.honeycomb.io
      grpc:
        metadata:
          x-honeycomb-team:
            - ${env.apiKey}
          x-honeycomb-dataset:
            - ${env.HONEYCOMB_DATASET}
      protocol: grpc
```

No had to switch to this after recent update.

```yaml
telemetry:
  exporters:
    tracing:
      common:
        service_name: "..."
        service_namespace: "..."
        parent_based_sampler: true
      propagation:
        baggage: true
      otlp:
        enabled: true
        endpoint: api.honeycomb.io
        protocol: grpc
        grpc:
          metadata:
            x-honeycomb-team:
              - ${env.apiKey}
            x-honeycomb-dataset:
              - ${env.HONEYCOMB_DATASET}
      experimental_response_trace_id:
        enabled: true # default: false
        header_name: "trace-id"
```

But having this error in logs, does not say much though. Tried different options with endpoint like, api.honeycomb.io:443 etc, but nothing works.

```
{"timestamp":"2024-01-30T12:22:05.254400512Z","level":"ERROR","message":"OpenTelemetry trace error occurred: Exporting timed out after 30 seconds","target":"apollo_router::plugins::telemetry","resource":{"service.name":"unknown_service:router","process.executable.name":"router","service.version":"1.38.0"}}
```
