### ISSUE TITLE
Error when adding standard attributes to spans

### ISSUE THREAD

**Issue by annedroiid** [apollographql/router#4565]
**Describe the bug**
When we try to add standard attributes to spans we are getting the error stating that this falls under advanced telemetry and we need a subscription to use this. However looking at the [docs](https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/spans/) it only says that custom attributes are an Enterprise feature, not standard attributes.

Is adding standard attributes to your span meant to be an Enterprise only feature? Or is this a bug?

**To Reproduce**
Here is our telemetry configuration

```
telemetry:
  exporters:
    tracing:
      common:
        service_name: <service-name>
        sampler: always_on
        parent_based_sampler: false
      experimental_response_trace_id:
        enabled: true
        header_name: x-request-id
      propagation:
        trace_context: true
        request:
          header_name: x-request-id
      datadog:
        enabled: true
        endpoint: "http://${env.DD_AGENT_HOST}:${env.DATADOG_TRACE_AGENT_PORT}"
        enable_span_mapping: true
  instrumentation:
    spans:
      supergraph:
        attributes:
          graphql.document: false
          graphql.operation.name: true
          graphql.operation.type: true
      subgraph:
        attributes:
          subgraph.graphql.document: false
          subgraph.graphql.operation.name: true
          subgraph.graphql.operation.type: true
```

We're running the router via docker
```
docker run -p 4000:4000 -d \
    --env environment="dev" \
    --env DD_AGENT_HOST="" \
    --env DATADOG_TRACE_AGENT_PORT="" \
    --mount "type=bind,source=$(pwd)/schema.graphql,target=/dist/schema/local.graphql" \
    --mount "type=bind,source=$(pwd)/router.yaml,target=/dist/config/router.yaml" \
    ghcr.io/apollographql/router:v1.38.0 -c config/router.yaml -s schema/local.graphql
```

**Expected behavior**
The router should run with the given config.

**Output**
We get the following error message and the docker container stops

```
Not connected to GraphOS. In order to enable these features for a self-hosted instance of Apollo Router, the Router must be connected to a graph in GraphOS (using APOLLO_KEY and APOLLO_GRAPH_REF) that provides a license for the following features:\n\nConfiguration yaml:\n* Advanced telemetry\n .telemetry..spans.supergraph\n\n* Advanced telemetry\n .telemetry..spans.subgraph\n\nSee https://go.apollo.dev/o/elp for more information.
```

**Additional context**
The graphql document contains all of the input values, which can included sensitive fields like usernames and passwords so we don't want it added to the spans. Without being able to disable this we're going to need to create our own copy of the telemetry plugin as we cannot have PII in datadog.
