### ISSUE TITLE
Disable coprocessor for certain operations

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#4606]
**Is your feature request related to a problem? Please describe.**
I want to keep introspection on in my lower environments but also enable the `RouterRequest` and `RouterResponse` stage in my coprocessor for non-introspection operations. If I then open up Apollo Explorer, my coprocessor is flooded with a bunch of requests that I just ignore. It would be ideal if the Router did not call out to the coprocessor at all for these operations and waste the HTTP call and processing time.

**Describe the solution you'd like**
A configurable option in the Router coprocessor stage to disable using it for IntrospectionQueries OR a way using Rhai to disable CP calls for certain types of requests that I figure out myself

```yaml
coprocessor:
  url: http://localhost:3000
  router:
    use_on_introspection: false
    request:
      body: true
    response:
      body: true
```

OR

Another option could be to allow Rhai script to control when a coprocessor is called or not with some metadata in the context and let users figure it out

* Rhai sets a context value `custom::tag::use_cp: true`

Then in YAML

```yaml
coprocessor:
  url: http://127.0.0.1:3000
  router:
    request:
      condition:
        eq:
          - true
          - context: custom::tag::use_cp
      body: true
      headers: true
```

**Describe alternatives you've considered**
I could not use the `Router` stage as other stages like `Supergraph` are not invoked for Introspection operations, but I want to operate at the very front of the request cycle.

**Additional context**
How we for sure know that it is an introspection query will have to be validated. We don't want to allow malicious actors to be able to get around a coprocessor by just naming their operation `IntrospectionQuery` or including some hidden fields like `__schema` along side real data fields

https://github.com/apollographql/router/issues/4871
