### ISSUE TITLE
Ability to provide custom request headers to JWKS configuration

### ISSUE THREAD

**Issue by abernix** [apollographql/router#4651]
Some IdP providers necessitate certain headers on the HTTP requests that are being made to their JWKS endpoints, for any number of reasons, including identifying themselves or providing IDs that assist with tracing and debugging.  

Today,  the Router offers the the ability to provide a set of JWKS URLs, but doesn't seem to offer the ability to provide additional HTTP-level properties to be sent with each of those URLs (i.e., `Authorization`):

### Possible Today

```yaml
authentication:
  router:
    jwt:
      jwks:
        - url: https://reg1-zzp5enui.us.auth0.com/.well-known/jwks.json
        - url: https://reg2-zzp5enui.us.auth0.com/.well-known/jwks.json
        - url: https://reg3-zzp5enui.us.auth0.com/.well-known/jwks.json
```

### Desired

> [!NOTE]  
> Actual specific semantics are certainly debatable!

```yaml
authentication:
  router:
    jwt:
      jwks:
        - url: https://reg1-zzp5enui.us.auth0.com/.well-known/jwks.json
          headers:
            - name: Authorization
              value: ${env.SECRET1}
        - url: https://reg2-zzp5enui.us.auth0.com/.well-known/jwks.json
        - url: https://reg3-zzp5enui.us.auth0.com/.well-known/jwks.json
          headers:
            - name: Authorization
              value: ${env.SECRET3}
```

Also, just to avoid confusion, I am not asking for anything related to the `header_name` and `header_value_prefix`. 😄
