### ISSUE TITLE
High Latency of Query planning in v1.35.0 w/ high load when OTLP tracing is enabled

### ISSUE THREAD

**Issue by Saurabh-Dream11** [apollographql/router#4669]
Hello Team Apollo Router,
We are in the process of upgrading our apollo router version from v1.11.0 to v1.35.0. We also have added tracing capability through OTLP in our router.yaml which uses gRPC protocol to send out traces to the Datadog-agent configured with trace_buffer value 3000.
We have observed that while the application metrics work smoothly for <130k req/min, on increasing the load to 140k req/min on a single AWS EC2 instance, the p99 latency for Query planning takes a hit and the number of errors also shoot up.

Query planning numbers
130k req/min - 12.6ms
140k req/min - 7.8s

This happens when there is no considerable increase in CPU usage, while we have observed that the memory usage increased considerably in case of higher load.

![image](https://github.com/apollographql/router/assets/122825862/7e270c80-8001-475d-97b6-6acc92bc52df)

Error in case of 140k req/min

<img width="534" alt="image" src="https://github.com/apollographql/router/assets/122825862/815671d0-3bcc-4ce7-98d7-196740ab54bb">
memory for 140k req/min

<img width="533" alt="image" src="https://github.com/apollographql/router/assets/122825862/91a222ad-9b2e-4cca-8943-39c6956abfd7">
memory for 130k req/min

<img width="531" alt="image" src="https://github.com/apollographql/router/assets/122825862/c6c33738-b2d3-449a-8125-d2883de37b69">
CPU for 130k req/min

<img width="517" alt="image" src="https://github.com/apollographql/router/assets/122825862/953dc453-ccd7-42f4-a8bb-92a31d654f18">
CPU for 140k req/min

1. Apollo router v1.35.0
2. router.yaml config

```
telemetry:
  instrumentation:
    spans:
      default_attribute_requirement_level: required
  exporters:
    tracing:
      common:
        resource:
          "service.name": "gql-router"
      otlp:
        enabled: true
        endpoint: 0.0.0.0:4317
        protocol: grpc
        batch_processor:
          scheduled_delay: 10s
          max_concurrent_exports: 300
          max_export_batch_size: 3000
          max_export_timeout: 30s
          max_queue_size: 2000000
      propagation:
        datadog: true
    logging:
      common:
        service_name: "gql-router"
      stdout:
        enabled: true
        format:
          # text:
          #   ansi_escape_codes: false
          #   display_filename: false
          #   display_level: true
          #   display_line_number: false
          #   display_target: false
          #   display_thread_id: false
          #   display_thread_name: false
          #   display_timestamp: true
          #   display_resource: true
          #   display_span_list: false
          #   display_current_span: false
          #   display_service_name: true
          #   display_service_namespace: true
          json:
            display_filename: false
            display_level: true
            display_line_number: false
            display_target: false
            display_thread_id: false
            display_thread_name: false
            display_timestamp: true
            display_current_span: true
            display_span_list: false
            display_resource: true
      experimental_when_header:
        - name: debug
          value: 'true'
          headers: true # default: false
          body: true
```

3. Hit load of 130k req/min and then 140k req/min (Numbers might vary for your application)
4. Look at query planning latency, memory and CPU usage

**Expected behavior**
The query planning process must not show spikes in latency numbers over a period of time. 

**Desktop (please complete the following information):**
 - AWS EC2 instance 
 - 16 Gb RAM
 - 8 vCPUs

**Comment by garypen** [comment]
Hi @Saurabh-Dream11 . It's possible that in the transition from 130k -> 140k req/min that you have exceeded the size of the qp cache and that is causing more planning to occur. The amount of additional cpu consumed might not be enough to detect on the monitoring, but would directly impact latency.

We can test this theory by examining the following metrics: `apollo_router_query_planning_time`

**Comment by Saurabh-Dream11** [comment]
Thanks @garypen for the above solution.

We are currently on router v1.35.0 so we tried using `experimental_cache`.
Increasing the value of `experimental_cache.in_memory.limit` to 10000, didn't help.

Although increasing the `warmed_up_queries` config to 100, helped. The service was able to sustain 140k req/min, but as we scaled it to 150k req/min, the issues occurred again.

Also we are seeing a dip in the `apollo_router_cache_hit_count` value as soon as the load starts to increase beyond the 140k req/min limit.

<img width="838" alt="image" src="https://github.com/apollographql/router/assets/122825862/3fff745b-bb80-429b-a405-cfae88e425d5">

**Comment by garypen** [comment]
Hi @Saurabh-Dream11 

I wouldn't expect setting `warmed_up_queries` would make any difference in your situation unless the schema is changing frequently at the same time as the router is executing. Reason: warm up helps when a router is starting or a schema is changing and queries need to be planned or re-planned.

I would have expected increasing the QP limit to have some effect though, so maybe the root cause is something different.

If you remove the OTLP tracing, does that impact the error rate or the performance of the router?

**Comment by Saurabh-Dream11** [comment]
Yes, If we move back to native Datadog tracing config, we don't encounter such errors.

**Comment by Saurabh-Dream11** [comment]
@garypen Configuring the batch-processor doesn't have any effect on the query planning time in case of our high load setup. From what we see, the query-planning time is the only bottleneck here. It's exceeding the timeout of 8s set for the requests in the ``traffic-shaping`` configuration.
Also, we are hitting only 8 queries in our load setup, so increasing the limit in cache also causes no significant change. Correct me if I missed something.

**Comment by Saurabh-Dream11** [comment]
@garypen When we use the native Datadog config (without OTLP) for v1.0.35 for tracing in the router.yaml, we experience a similar behaviour in QP latency but at 165k req/min. The CPU max usage was <60%.

![image](https://github.com/apollographql/router/assets/122825862/66881876-e4f9-4fd4-a2fa-a9760a04db57)

![image](https://github.com/apollographql/router/assets/122825862/1a097ad2-df1f-4e15-9c07-5950fa59a87d)

![image](https://github.com/apollographql/router/assets/122825862/2a717c34-6c99-4489-9483-5a1048a526c5)

router.yaml
```
rhai:
  scripts: "./rhai_scripts"
  main: "header.rhai"
plugins:
  graphql_router.super_graph:
    message: "starting supergraph plugin"
supergraph:
  listen: 0.0.0.0:7777
  path: "/*"
  introspection: ${env.IS_LOWER_ENV}
sandbox:
  enabled: ${env.IS_LOWER_ENV}
homepage:
  enabled: false
health_check:
  listen: 0.0.0.0:7777
  enabled: true
include_subgraph_errors:
  all: true # Propagate errors from all subraphs
headers:
  all:
    request:
      - propagate:
          matching: .*
telemetry:
  exporters:
    tracing:
      common:
        resource:
          "service.name": "gql-router"
      # Optional. Either a float between 0 and 1 or 'always_on' or 'always_off'
        sampler: ${env.TRACING_SAMPLING_RATE}
      # Optional. Use a parent based sampler. This enables remote spans help make a decision on if a span is sampeld or not.
      # https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#parentbased
        parent_based_sampler: false
      # Optional limits
      # max_attributes_per_event: 10
      # max_attributes_per_link: 10
      # max_attributes_per_span: 10
      # max_events_per_span: 10
      # max_links_per_span: 10
      # Attributes particular to an exporter that have not
      # been explicitly handled in Router configuration.
      #attributes:
      #  some.config.attribute: "config value"
      propagation:
        # https://www.w3.org/TR/baggage/
        baggage: false
        # https://www.datadoghq.com/
        datadog: true
        # https://www.jaegertracing.io/ (compliant with opentracing)
        jaeger: false
        # https://www.w3.org/TR/trace-context/
        trace_context: false
        # https://zipkin.io/ (compliant with opentracing)
        zipkin: false
        # If you have your own way to generate a trace id and you want to pass it via a custom request header
        #request:
        #  header_name: my-trace-id
      datadog:
        endpoint: default
        enabled: true
        batch_processor:
          scheduled_delay: 10s
          max_concurrent_exports: 300
          max_export_batch_size: 10000
          max_export_timeout: 30s
          max_queue_size: 2000000

traffic_shaping:
  deduplicate_variables: true # Enable the variable deduplication optimization.
  router: # Rules applied to requests from clients to the router
    # global_rate_limit: # Accept a maximum of 10 requests per 5 secs. Excess requests must be rejected.
    #   capacity: 10
    #   interval: 5s # Must not be greater than 18_446_744_073_709_551_615 milliseconds and not less than 0 milliseconds
    timeout: 8s # If a request to the router takes more than 8secs then cancel the request (30 sec by default)
  all:
    deduplicate_query: true # Enable query deduplication for all subgraphs.
    timeout: 7s
    # compression: gzip # Enable brotli compression for all subgraphs.
  # subgraphs: # Rules applied to requests from the router to individual subgraphs
  #   products:
  #     deduplicate_query: false # Disable query deduplication for the products subgraph.
  #     compression: gzip # Enable gzip compression only for the products subgraph.
  #     global_rate_limit: # Accept a maximum of 10 requests per 5 secs from the router. Excess requests must be rejected.
  #       capacity: 10
  #       interval: 5s # Must not be greater than 18_446_744_073_709_551_615 milliseconds and not less than 0 milliseconds
  #     timeout: 50s # If a request to the subgraph 'products' takes more than 50secs then cancel the request (30 sec by default)
  # ...

```

**Comment by Saurabh-Dream11** [comment]
Hi Team,
We used the following config for router.yaml (without any tracing configuration), yet we observed a similar behaviour, where, the latency is spiking at a threshold of 160k RPM. Attached is the screen-grab for load and latency on a C5-2x Large EC2 instance.

```
rhai:
  scripts: "./rhai_scripts"
  main: "header.rhai"
plugins:
  graphql_router.super_graph:
    message: "starting supergraph plugin"
supergraph:
  query_planning:
    warmed_up_queries: 1000
    experimental_cache:
      in_memory:
        limit: 100000
  listen: 0.0.0.0:7777
  path: "/*"
  introspection: ${env.IS_LOWER_ENV}
sandbox:
  enabled: ${env.IS_LOWER_ENV}
homepage:
  enabled: false
health_check:
  listen: 0.0.0.0:7777
  enabled: true
include_subgraph_errors:
  all: true # Propagate errors from all subraphs
headers:
  all:
    request:
      - propagate:
          matching: .*
 
traffic_shaping:
  deduplicate_variables: true # Enable the variable deduplication optimization.
  router: # Rules applied to requests from clients to the router
    # global_rate_limit: # Accept a maximum of 10 requests per 5 secs. Excess requests must be rejected.
    #   capacity: 10
    #   interval: 5s # Must not be greater than 18_446_744_073_709_551_615 milliseconds and not less than 0 milliseconds
    timeout: 8s # If a request to the router takes more than 8secs then cancel the request (30 sec by default)
  all:
    deduplicate_query: true # Enable query deduplication for all subgraphs.
    timeout: 7s
    # compression: gzip # Enable brotli compression for all subgraphs.
  # subgraphs: # Rules applied to requests from the router to individual subgraphs
  #   products:
  #     deduplicate_query: false # Disable query deduplication for the products subgraph.
  #     compression: gzip # Enable gzip compression only for the products subgraph.
  #     global_rate_limit: # Accept a maximum of 10 requests per 5 secs from the router. Excess requests must be rejected.
  #       capacity: 10
  #       interval: 5s # Must not be greater than 18_446_744_073_709_551_615 milliseconds and not less than 0 milliseconds
  #     timeout: 50s # If a request to the subgraph 'products' takes more than 50secs then cancel the request (30 sec by default)
```

![image](https://github.com/apollographql/router/assets/122825862/5d2ad2c9-1102-4334-a1fa-5011a7bb8336)
p99 Latency for 160k RPM


![image](https://github.com/apollographql/router/assets/122825862/abac872a-8116-4cbb-84b3-695bf3513a81)
160k RPM throughput on ALB

![image](https://github.com/apollographql/router/assets/122825862/0afb4d70-5d24-40c4-94d9-c30a2b2fe97a)
Max CPU usage
