### ISSUE TITLE
Telemetry configuration unknown key "exporters"

### ISSUE THREAD

**Issue by awdng** [apollographql/router#4679]
https://github.com/apollographql/router/blame/9c24132fe9b775ec40781545dc8e3468c3c8915e/docs/source/configuration/telemetry/exporters/metrics/prometheus.mdx#L17

I am getting an error on router startup about unknown key "exporters" as described in the documentation, however this works fine when omitting the "exporters" key:

```yaml
telemetry:
  metrics:
    prometheus:
      enabled: true
      listen: 127.0.0.1:9090
```
