### ISSUE TITLE
`experimental_response_trace_id` does not send to Studio without an explicit header value set 

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#4699]
**Describe the bug**

When using:

```yml
telemetry:
  exporters:
    tracing:
      experimental_response_trace_id:
        enabled: true
```

The response header is not sent to studio when the trace is sampled. Explicitly setting the header such as:

```yml
telemetry:
  exporters:
    tracing:
      experimental_response_trace_id:
        enabled: true
        header_name: 'apollo-trace-id'
```

Will resolve the issue. 

**To Reproduce**
See above.

**Expected behavior**

Using the default header name to work when sending to Studio. 

**Desktop (please complete the following information):**
 - OS: macOS aarch64

**Additional context**
Workaround above.
