### ISSUE TITLE
configuration migration of telemetry configuration loses service_name

### ISSUE THREAD

**Issue by garypen** [apollographql/router#4717]
If an older router configuration looks like this (in a file `router.yaml`:
```yaml
telemetry:
  tracing:
    common:
      service_name: router
    trace_config:
      attributes:
        env: dev
```
executing: `cargo run  -- config upgrade router.yaml` to update the configuration will yield:
```yaml
telemetry:
  exporters:
    tracing:
      common:
        resource:
          env: dev
```
Note: `service_name` is lost.

We believe that: "the move of trace_config to common is zapping the existing common content.".
