### ISSUE TITLE
Allow setting metric attributes from a context sub key

### ISSUE THREAD

**Issue by Geal** [apollographql/router#4750]
metric attributes can be set from a context key: https://www.apollographql.com/docs/router/configuration/telemetry/exporters/metrics/overview/#attributes

But it only supports the key to a top level object. It would be useful to get data from sub keys from an object like:

```yaml
telemetry:
  exporters:
    metrics:
      common:
        attributes:
          supergraph:
            context:
              - named: toplevelobject.sub_key
```
