### ISSUE TITLE
tracing otlp exporter endpoint configuration for http doesn't append the right path

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#4798]
In our [documentation](https://www.apollographql.com/docs/router/configuration/telemetry/exporters/tracing/otlp/#endpoint) when configuration http endpoint for tracing otlp exporter we say that users should only include the base address of the otlp endpoint.

So for example you'll have to specify the right path for http:

```yaml
telemetry:
  exporters:
    tracing:
      otlp:
        enabled: true
        endpoint: "http://localhost:4318/v1/traces"
        protocol: http
```

but not for GRPC:

```yaml
telemetry:
  exporters:
    tracing:
      otlp:
        enabled: true
        endpoint: "http://localhost:4317"
        protocol: grpc
```

This inconsistency is due to a bug in `opentelemetry-otlp` crate, I raised an issue [here](https://github.com/open-telemetry/opentelemetry-rust/issues/1618)
