### ISSUE TITLE
Tracing service name reported as `unknown_service`

### ISSUE THREAD

**Issue by nathanmarcos** [apollographql/router#4807]
**Describe the bug**
We have tracing set up with zipkin exporter and the `service.name` field from router has the value `unknown_service` despite the name being configured on `router.yaml`.

Root list:
![image](https://github.com/apollographql/router/assets/2166279/af7bcfbf-c8d2-48cd-b601-428e85566462)

Trace:
![image](https://github.com/apollographql/router/assets/2166279/6a6ceae5-f0ca-47a4-9451-94dbfea4c76f)

**To Reproduce**
1. Start zipkin: 
	- `docker run --rm -d -p 9411:9411 openzipkin/zipkin-slim`
2. Start a stock router version `1.42.0` with the following `router.yaml` config:
	- `cargo run -- --supergraph testing_schema.graphql --config router.yaml --dev`
```
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant
  exporters:
    tracing:
      common:
        sampler: 1
        service_name: foo
        service_namespace: bar
        resource:
          "service.name": "foo"
      zipkin:
        enabled: true
        endpoint: "http://localhost:9411/api/v2/spans"
```
3. Shoot some query to the server: 
	- [Example](http://localhost:4000/?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABALIEDyADvgIYoCWESRwAOs0QPqcoHVI1E7AL7sQwoA)
4. Check the logs on zipkin:
	- http://localhost:9411/zipkin

**Expected behavior**
The `service.name` field to be carrying the value defined on `router.yaml`.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version: 14.2.1

**Additional context**
- Router version: 1.42.0
