### ISSUE TITLE
Coprocessor health check as part of overall router health

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#4874]
**Is your feature request related to a problem? Please describe.**

The router currently fails closed if the coprocessor is unavailable/erroring/etc, which leads to situations where a router may be marked as healthy by it's own health check, but not by clients. 

**Describe the solution you'd like**

Ideally coprocessors, when enabled, are used when calculating the overall health of the router. As an example shape of a possible config: 

```yml
coprocessor:
  url: http://localhost:3000/
  healthcheck:
    enabled: true
    endpoint: "/health"
```

Which would use a user-defined health endpoint for the coprocessor. 

**Describe alternatives you've considered**

Moving all health checks into the coprocessor instead, when running in a sidecar model (i.e. router and coprocessor exist in the same Kubernetes pod).
