### ISSUE TITLE
Warm up 100% of operations for query planning

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#4884]
## Is your feature request related to a problem? Please describe.
Today I can pre-warm the cache with operations, but I need to set a fixed number ie "load the most recent 100 ops". If I want to load all my operations I have to set to a really large number, like 1,000,000. It would just be a nice to have for an option to load 100% regardless of what number that is.

## Describe the solution you'd like

Add a new option that loads all operations we have seen. The caveat is that the Router might not have ALL operations, so we can load what we have.

```yaml
supergraph:
  query_planning:
    warmed_up_queries: all_operations
    time_frame: 24h # Maybe needed? Not sure how Router saves these operations to load
```

## Describe alternatives you've considered
Using persisted queries loads the full list of those operations, but I may not be using that feature
