### ISSUE TITLE
Header added to request in rhai does not propagated into logs trace_id field

### ISSUE THREAD

**Issue by kindermax** [apollographql/router#4892]
**Describe the bug**

Router version: v1.43.1

I use rhai to insert a `x-trace-id` header into request. Then I expect value of this header to be a `trace_id` in logs.

**To Reproduce**

Here I use `x-trace-id` to propagate header value to logs.
If `x-trace-id` present in headers from browser request - it works fine. But if I add `x-trace-id` header in rhai script - value does not propagated.

```
telemetry:
  exporters:
    tracing:
      propagation:
        request:
          header_name: x-trace-id
    logging:
      stdout:
        enabled: true
        format:
           json:
             display_level: true
             display_timestamp: true
             display_trace_id: true
             display_span_id: true
```

rhai script

```
fn supergraph_service(service) {
    let adapt_request_id = |request| {
        if request.headers.contains("x-request-id") {
            // x_request_id is a uuid4
            let x_request_id = request.headers["x-request-id"];
            x_request_id.replace("-", "");
            print(`x-request-id: ${x_request_id}`);
           // x-trace-id is just a copy of x-request-id without dashes
           // so router can parse it properly
           // we then restore it to uuid format in the logs processor
           request.headers["x-trace-id"] = x_request_id;
       }
    };

    service.map_request(adapt_request_id);
}
```

**Expected behavior**

I expect that rhai-created header propagated to `trace_id` field in logs.
