### ISSUE TITLE
Global rate limiting error messages being incorrectly returned

### ISSUE THREAD

**Issue by lleadbet** [apollographql/router#4943]
**Describe the bug**

When using the `global_rate_limit` feature under `router` (see example config), the router returns: 

```json
{
  "error": {
    "message": "Unexpected token 'y', \"your reque\"... is not valid JSON",
    "stack": "SyntaxError: Unexpected token 'y', \"your reque\"... is not valid JSON"
  }
}
```

**To Reproduce**

With config having: 

```yml
traffic_shaping:
  router:
    global_rate_limit:
      capacity: 1
      interval: 1s
```

And sending a number of requests in a row, you'll see the above issue. 

**Expected behavior**

The error to be correctly shown. 

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version v1.43.2
