### ISSUE TITLE
Introspection query doesn't return latest schema changes when query plan is being persisted on Redis

### ISSUE THREAD

**Issue by nathanmarcos** [apollographql/router#5006]
**Describe the bug**
Starting from version `1.44.0`, up to latest `1.45.0`, the introspection query is not returning new parts of the schema when persisting the query plan on Redis and router is using a supergraph from a file.

**To Reproduce**
1. Start redis:
	- `docker run --rm -d -p 6379:6379 redis`
2. Start stock router version `1.44.0` or `1.45.0` as following:
	- `APOLLO_KEY="..." APOLLO_GRAPH_REF="..." APOLLO_ROUTER_SUPERGRAPH_PATH="examples/graphql/supergraph.graphql" APOLLO_ROUTER_CONFIG_PATH="router.yaml" cargo run -- --dev`

```yaml
# router.yaml
supergraph:
  query_planning:
    cache:
      in_memory:
        limit: 1024
      redis:
        timeout: 10ms
        urls:
          - "redis://127.0.0.1"
```
3. Open sandbox at `http://127.0.0.1:4000/` and make sure schema polling is on
4. Add a new query to `examples/graphql/supergraph.graphql` and save the file
5. Router will hot reload
6. The new query doesn't appear on sandbox

PS: If you manually delete the entry on Redis for the `plan:v2.7.2:06402fd188...` that contains the `{"Ok":{"Response":{"response":{"data":{"__schema":{"queryType":{"name":"Query"},"...`, a new entry will be created and the new schema will immediately be delivered and the new query will be visible on sandbox.

**Expected behavior**
Router should serve via introspection all schema changes after a reload or hot reload even when the query plan is being persisted on Redis.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Version: 14.4.1

**Additional context**
Router version: `1.44.0` or `1.45.0`
