### ISSUE TITLE
Send response errors only to coprocessor

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#5020]
## Is your feature request related to a problem? Please describe.
Today I can configure the Router to send the response, which might have `data` or `errors` or `extensions`, to the coprocessor so that it can perform extra logic. However I can only choose to send the whole response `body`. If I am returning data back this body may be quite large and can cause performance issues or even errors inside my coprocessor trying to serialize large responses.

Instead I would like the ability to decide what parts of the GraphQL response I would like sent to a coprocessor.

Config today
```yaml
coprocessor:
  url: http://127.0.0.1:8081
  supergraph:
    response:
      body: true
```

## Describe the solution you'd like
I would like the ability to decide what parts of the GraphQL response I would like sent to a coprocessor, so I can reduce the payload size.

It probably makes sense for this to be at the `SupergraphResponse` phase since that is where the Request is also in a parsed state vs the `RouterResponse` should be reserved for changing the entire response as it is about to be sent via HTTP back to the client

> Note: We should include support for `data`, `errors`, and `extensions` separately 

Possible new config:
```yaml
coprocessor:
  url: http://127.0.0.1:8081
  supergraph:
    response:
      body_data: false
      body_errors: true
      body_extensions: true

```

## Describe alternatives you've considered
I could use [Rhai scripts](https://www.apollographql.com/docs/router/customizations/rhai-api#responsebodyerrors) to process particular parts of the response

## Additional context
Actually having a large payload can cause the coprocessor to fail which is a separate issue, so this feature request is one way in which we can solve that

**Comment by glasser** [comment]
Maybe:

```
coprocessor:
  url: http://127.0.0.1:8081
  supergraph:
    response:
      body:  # if this is provided as an object, then sub-fields are false by default, eg data
        errors: true
        extensions: true
```
