### ISSUE TITLE
telemetry: add selectors for errors to be able to match on a specific error

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#5027]
Example for use case: if you want to create a counter that count the number of connection timeout error you got and add subgraph as an attribute to know which subgraph encountered a timeout.

example of configuration we would like to have:

```yaml
telemetry:
  instrumentation:
    instruments:
      subgraph:
        requests.timeout:
          value: unit
          type: counter
          unit: request
          description: "subgraph requests containing subgraph timeout"
          attributes:
            subgraph.name: true
          condition:
            eq:
              - "request timed out"
              - error: reason
```
