### ISSUE TITLE
Conditional apply safelisting with operation limits

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#5058]
## Is your feature request related to a problem? Please describe.
I want to enable persisted queries and safelisting for clients that can register their operations, but I also want to keep my graph open for queries from unregistered operations, but with limits on the size of them.

As far as I am aware, I can enabled both of these features today, but then even persisted queries will be checked with my operation limits config.

## Describe the solution you'd like
I would like to allow any query of any size if it is pre-registered, but use operation limit if it is not, and not block the registered operations with the limits.

```yaml
# Any size operation is allowed if it is registered
persisted_queries:
  enabled: true
  safelist:
    enabled: false
apq:
  enabled: false

# Unregistered ops use limits
limits:
  max_depth: 5
  max_height: 25

  # New config needed??
  include_persisted_queries: false
```

## Describe alternatives you've considered
If there was some way I could dynamically decide to run op limits or safelisting checks (Rhai or CP) then we could maybe build this ourselves, but that is not possible today either.

So my options would have to be to build my own coprocessor to check op limits

## Additional context
This will be even more helpful once we get to a more full featured cost limiting calculation. Also it could help if Persisted Queries had a review step so we could apply some limits that at registration time that might be different than runtime, but that is a separate issue
