### ISSUE TITLE
Request/Response body size metric per operation name

### ISSUE THREAD

**Issue by grzn** [apollographql/router#5152]
The metric 'apollo_router_http_request_duration_seconds' is great, exposing the duration for each Gql operation. 
It would even better to have a metric for the request/response body sizes per opeation. 

From what I gather this is not doable with a custom router metric (does not have the operation name selector/attribute) and not with a super graph selector/attribute (does not have the request/body size)

**Comment by bnjjj** [comment]
@grzn It's actually already possible using custom router metric but not really obvious neither well documented. To get the operation name you can have it using `response_context` selector and use the `operation_name` entry. That would result in something like this:

```yaml
telemetry:
  instrumentation:
    instruments:
      router:
        http.server.request.body.size:
          attributes:
            graphql.operation.name:
              response_context: operation_name
        http.server.response.body.size:
          attributes:
            graphql.operation.name:
              response_context: operation_name
```
