### ISSUE TITLE
Configure http header size and limit

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#5277]
## Is your feature request related to a problem? Please describe.
In NodeJS, which also means Apollo Gateway, I can set the max HTTP header size and limit (see [--max-http-header-size](https://nodejs.org/api/cli.html#--max-http-header-sizesize)). Apollo Router under the hood uses [Hyper](https://github.com/hyperium/hyper) which also has some options to configure those limits but I do not have access to them so we are stuck with the defaults.

## Describe the solution you'd like
I would like to be able to configure the max http header size and limits from either the command line or YAML

```yaml
server: # maybe some new top level section for just HTTP server stuff?
  http_header_size: 32kb
  http_header_limit: 250
```

## Describe alternatives you've considered
If I wanted to set the limits to a lower value I could implement a Rhai or Coprocessor to check the HTTP request info but if I wanted to go higher, like `32kb`, then I cannot as the [default is set to 16kb](https://github.com/hyperium/hyper/blob/eade122db25f51619aee5db845de2a61b7ff2f74/src/proto/h2/server.rs#L41).
