### ISSUE TITLE
Consistent trace id 

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#5387]
Users are having trouble correlating their logs due to there being multiple IDs floating around, sampling affecting the presence or not of a trace_id.

The behaviour we would like:

1. Otel Trace ID is exposable on logs. This functionality already exists.
```yaml
telemetry:
  exporters:
    logging:
      stdout:
        format:
          json:
            display_trace_id: true
```
2. Promote attributes from the root span to the json container as a top level attribute. This will allow users to have headers etc that have been attached to the root span be output on logs.
```yaml
telemetry:
  exporters:
    logging:
      stdout:
        format:
          json:
            promote_span_attributes:
              - my.custom.attribute 
```

3. TraceID generated for logs even if the request is not sampled. FIxed in: https://github.com/apollographql/router/pull/5447

4. `experimental_response_trace_id` should use the same logic as in `#3` to enable a consistent trace id to be returned to the client. Fixed in: https://github.com/apollographql/router/pull/5447
