### ISSUE TITLE
New propagation configuration

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#5388]
Currently we have the headers functionality to allow propagation to subrequests. However we need something more general so that users do not have to reach for plugins or rhai.

Suggest using the selector functionality and align on server and client terminology to align with Otel.
This can reuse the selector logic that has been developed for telemetry to get data from somewhere, but also introduce an injector concept for putting data somewhere.

```yaml
propagation:
  server:
    request:
      from:
        header: a         # Selector
      to:
        context:           # Injector
          key: b
          type: string

    response:
      from: 
        context: b
      to:
        response_header: a
  client:
    request:
      from:
        context: b
      to:
        request_header: a

    response:
      from:
        response_header: b
      to:
        context: a
```

[ROUTER-371]: https://apollographql.atlassian.net/browse/ROUTER-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
