### ISSUE TITLE
Give to standard events the ability to be displayed conditionally

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#5475]
Instead of only provide the level I really would like to be able to have conditions on these standard events. Example of configuration:

```yaml
telemetry:
  instrumentation:
    events:
      router:
        request:
          level: info
          condition:
            eq:
            - request_header: x-log-request
            - "enabled"
        response: off
        error: error
```
