### ISSUE TITLE
Configurability of log attributes

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#5540]
Currently when configuring the attributes that are output onto log events we have the following:

```yaml 
telemetry:
  exporters:
    logging: 
      stdout:
        format: 
          json:
            display_span_list: true # Output all attributes from all spans to the root
            display_current_span: true # Output attributes from the current span
```

When following the otel conventions there can be a large number of span attributes, and users need the ability to specify which attributes should be output rather than the all or nothing settings we have already.

Users needs to be able to opt in to attributes so that they can be sure that only the attributes they want are output.

Suggested config:

```yaml
telemetry:
  exporters:
    logging:
      stdout:
        format:
          json:
            attributes:
              - my.custom.attribute1
              - my.custom.attribute2
  instrumentation:
    spans:
      router:
        attributes:
          my.custom.attribute1: "hello"
      subgraph: 
        attributes:
          my.custom.attribute2: "world"
```

 

This will search for the first attribute in the list of span attributes from the root span to the current and attach it to the outmost json object for the log event.

If you set the same attribute on different spans at different level, then the identical attribute from child spans will take precedence over the one found previously in parent spans.
