### ISSUE TITLE
Better error message for regex validation in header logging

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#5548]
## Is your feature request related to a problem? Please describe.
When configuring the regex for conditional header logging I get the following error message if I made a typo

```
ERROR  could not create router: data did not match any variant of untagged enum HeaderLoggingCondition
```

This is not very helpful in telling me where in my router.yaml I made my typo, but it is in line 7 below:

```yaml 
# router.yaml
telemetry:
  exporters:
    logging:
      experimental_when_header:
        - name: user-agent
          match: ^Mozilla/5.0 (iPhone*
          headers: true
```

## Describe the solution you'd like
Improve the error message to reference the YAML path and/or the text that has caused an error

```
ERROR  could not create router: the config value used is not a valid regix value="^Mozilla/5.0 (iPhone*" location= "telemetry.exporters.logging.experimental_when_header[0].match"
```

## Additional context
Logic to parse the error is here: https://github.com/apollographql/router/blob/199b6528dfda88d016e9ff0558a059058ab86974/apollo-router/src/plugins/telemetry/config_new/experimental_when_header.rs#L12
