### ISSUE TITLE
Improving caching on CircleCI

### ISSUE THREAD

**Issue by cecton** [apollographql/router#56]
We should change those (in the 3 platform):
```yaml
            - rust/build:
                # This is prefixed in the orb with 'cargo-'
                cache_version: v2-macos
                crate: --workspace --tests
```
To do:
* `cargo build --workspace --tests --no-default-features --features otlp-tonic`
* `cargo build --workspace --tests --no-default-features --features otlp-tonic,tls`
* `cargo build --workspace --tests --no-default-features --features otlp-grpcio` (not on windows)
* `cargo build --workspace --tests --no-default-features --features otlp-http`
