### ISSUE TITLE
Add a conditional static selector to be able to conditionally set an attribute on instruments

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#5641]
Something that would look like:

```yaml
telemetry:
  instrumentation:
    instruments:
      cache:
        apollo.router.operations.entity.cache:
          attributes:
            entity.type: true
            subgraph.name:
              subgraph_name: true
            supergraph.operation.name:
              supergraph_operation_name: string
            cache_hit: # Here is the interesting bits
              conditional_static: # The selector
                if: # The condition
                  gt:
                  - cache: hit
                  - 0
                then: true # Value set to true if the condition is true
                else: false # Value set to false if the condition is false
```
