### ISSUE TITLE
OTLP exporter port default does not match tonic vs http

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#5717]
It looks like Otel does not switch the exdpoint based on if tonic or http builders are used. Instead it is statically determined by feature gate.

This means that anyone who doesn't explicitly specify the endpoint is going to run into trouble.

Worse still, the defaults don't work.
So whereas users should just be able to set:

```
    metrics:
      otlp:
        temporality: delta
        enabled: true
```
It will actually choose the wrong default port of 3218 which is for use with grpc.

To fix we need to explicitly default the endpoints of otlp rather than relying on otel to do this defaulting.
