### ISSUE TITLE
Add ability to alias the name of a standard attribute in custom telemetry

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#5930]
For example using this configuration:

```yaml
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant # Docs state this significantly improves performance: https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/spans#spec_compliant
    instruments:
      cache: # Cache instruments configuration
        apollo.router.operations.entity.cache: # A counter which counts the number of cache hit and miss for subgraph requests
          attributes:
            entity.type: true # Include the entity type name. default: false
            subgraph.name: # Custom attributes to include the subgraph name in the metric
              subgraph_name: true
            supergraph.operation.name: # Add custom attribute to display the supergraph operation name
              supergraph_operation_name: string
            subgraph.response.cache-control: # Include the cache-control header in the metric
              subgraph_response_header: "cache-control"
```
will be an issue because on new relic entity.type is a reserved attribute name and so it won’t work properly. cf [Learn about New Relic entities](https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/core-concepts/what-entity-new-relic/#reserved-attributes) 

In order to make it work and that could also answer other use cases that would be great if we could alias the name of a standard attribute like this:

```yaml
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant # Docs state this significantly improves performance: https://www.apollographql.com/docs/router/configuration/telemetry/instrumentation/spans#spec_compliant
    instruments:
      cache: # Cache instruments configuration
        apollo.router.operations.entity.cache: # A counter which counts the number of cache hit and miss for subgraph requests
          attributes:
            entity.type:
              alias: entity_type # ENABLED and aliased to entity_type
            subgraph.name: # Custom attributes to include the subgraph name in the metric
              subgraph_name: true
            supergraph.operation.name: # Add custom attribute to display the supergraph operation name
              supergraph_operation_name: string
            subgraph.response.cache-control: # Include the cache-control header in the metric
              subgraph_response_header: "cache-control"
```
