### ISSUE TITLE
Add configurable limit for query batching

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/router#6134]
## Describe the solution you'd like
Support a limit on the number of requests in a batch, effectively enforcing the [client-side setting](https://www.apollographql.com/docs/react/api/link/apollo-link-batch-http#batchmax). For example:

```yaml
batching:
  enabled: true
  mode: batch_http_link
  max_requests: 10
```

## Describe alternatives you've considered
AFAIK it's not possible to use Rhai/coprocessors to enforce this because the parsed batch body is not available within extensions points.

## Additional context
Raised on behalf of a customer
