### ISSUE TITLE
could not create the HTTP server: Permission denied (os error 13) when migrating apollo router v1.34 to v1.56

### ISSUE THREAD

**Issue by nico-iaco** [apollographql/router#6152]
## Describe the bug
From apollo router v1.39 when I deploy into a k8s cluster it doesn't start with this error: could not create the HTTP server: Permission denied (os error 13)

## To Reproduce
If I apply this k8s manifest
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: apollo-router
  name: apollo-router
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apollo-router
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app.kubernetes.io/name: apollo-router
    spec:
      containers:
      - args:
        - --hot-reload
        - --config
        - /app/configuration.yaml
        - --supergraph
        - /data/supergraph.graphql
        - --dev
        env:
        - name: APOLLO_GRAPH_REF
          value: REDACTED
        image: ghcr.io/apollographql/router:v1.56.0
        imagePullPolicy: IfNotPresent
        lifecycle: {}
        livenessProbe:
          httpGet:
            path: /health?live
            port: 8088
          initialDelaySeconds: 10
        name: router
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 8088
          name: health
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health?ready
            port: 8088
          initialDelaySeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 500Mi
        securityContext: {}
        volumeMounts:
        - mountPath: /app/
          name: router-configuration
          readOnly: false
        - mountPath: /data/
          name: supergraph-volume
          readOnly: false
      securityContext: {}
      serviceAccountName: router-test
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: apollo-router-config-t597dcbf52
        name: router-configuration
      - csi:
          driver: gcsfuse.csi.storage.gke.io
          readOnly: true
          volumeAttributes:
            bucketName: apollo-router-svil-bucket
        name: supergraph-volume
``` 
with this router-configuration:
```yaml
cors:
  allow_any_origin: true
supergraph:
  # The socket address and port to listen on
  listen: 0.0.0.0:80
  introspection: true
health_check:
  listen: 0.0.0.0:8088
  enabled: true
include_subgraph_errors:   
  all: true
headers:
  all: # Header rules for all subgraphs
    request:
      - propagate:
          matching: ^.*
sandbox:
  enabled: true
homepage:
  enabled: false
plugins:
  # Enable with the header, Apollo-Expose-Query-Plan: true
  experimental.expose_query_plan: true
``` 
what I get is this:
<img width="1365" alt="image" src="https://github.com/user-attachments/assets/ac6293a9-16a4-42e9-b78c-fbe4075a0f47">

## Expected behavior
What I've seen is that I can run every version until v1.38 normally but from the v1.39 and above they all me return this permission denied error, I'm expecting that it should works without modification to my configuration file

## Desktop (please complete the following information):
 - OS: K8S
 - Version 1.28.13-gke.1049000
