### ISSUE TITLE
Ability to redact header values in JWT authentication info log

### ISSUE THREAD

**Issue by dupham-indeed** [apollographql/router#6200]
## Is your feature request related to a problem? Please describe.
Currently, once JWT is configured and the router spin up, the following info log will be printed out at startup:
```
2024-10-28T15:12:08.984490Z INFO  JWT authentication using JWKSets from jwks=[JwksConf { url: "<jwk_url>", poll_interval: 60s, issuer: Some("<issuer_url>"), algorithms: Some([ES256]), headers: [Header { name: "x-client-id", value: "<client_id_value>" }, Header { name: "x-api-key", value: "<api_key_value>" }, Header { name: "x-client-version", value: "<client_version_value>" }] }]
```
For our situation, <api_key_value> is considered a sensitive value and shouldn't be printed out in the logs, which can be viewed in observability tools such as Datadog. We would like to have the ability to have that value redacted for security concerns.

## Describe the solution you'd like
One possibility
```
authentication:
  router:
    jwt:
      jwks:
        - url: <jwk_url>
          headers:
            - name: x-api-key
              value: <api_key_value>
              redacted: true
```
Then the output will look like
```
2024-10-28T15:12:08.984490Z INFO  JWT authentication using JWKSets from jwks=[JwksConf { url: "<jwk_url>", poll_interval: 60s, issuer: Some("<issuer_url>"), algorithms: Some([ES256]), headers: [Header { name: "x-client-id", value: "<client_id_value>" }, Header { name: "x-api-key", value: "redacted" }, Header { name: "x-client-version", value: "<client_version_value>" }] }]
```
