### ISSUE TITLE
apollo.router.graphql_error: Add subgraph name, operation name

### ISSUE THREAD

**Issue by theJC** [apollographql/router#6228]
## Is your feature request related to a problem? Please describe.
We use apollo.router.graphql_error count for SLOs and monitors, but need to filter by subgraph name  and operation name

## Describe the solution you'd like
Add subgraph name and operation name tags to apollo.router.graphql_error

## Describe alternatives you've considered
Building our own separate metric emanated from our coprocessor, but that would be inconsistent/emanated from a different service.

**Comment by bnjjj** [comment]
I would suggest our instrumentation config to achieve it in a better way.
I think you should keep using the provided `http.server.request.duration` and configure it:
```yaml
telemetry:
  instrumentation:
    instruments:
      router:
        http.server.request.duration:
          attributes:
            http.response.status_code: true
            graphql.operation.name: # Will set this attribute with the operation name
              operation_name: string
            graphql.errors: # Will set this attribute to true if it contains graphql error
              on_graphql_error: true
```
