### ISSUE TITLE
Accept header ignored by Router

### ISSUE THREAD

**Issue by michaelcaterisano** [apollographql/router#6501]
## Describe the bug
I'm trying to send an http request to a Router instance to support HTTP Subscriptions. I'm sending `Accept: multipart/mixed;subscriptionSpec=1.0, application/json`. This works fine locally with Rover, but Router is giving me the following error: 

```
the router received a query with a subscription but the client does not accept multipart/mixed HTTP responses. To enable subscription support, add the HTTP header 'Accept: multipart/mixed;subscriptionSpec=1.0
```

I noticed a recent PR that may be related to allowing the Accept header https://github.com/apollographql/router/pull/6496. Is this a known issue that will be fixed in a future version of Router? If so, do you know when this PR will make it into a release?

**Comment by IvanGoncharov** [comment]
@michaelcaterisano #6496 is 100% not related since it doesn't change how INCOMING requests are processed. 
Instead, it allows us to set Accept on OUTGOING requests.

As for your issue, can you please test that some intermediate HTTP proxy/firewall does not reject the request?
Previously, we had similar issues caused by 3rd-party proxies blocking subscription requests.

**Comment by michaelcaterisano** [comment]
Thanks @IvanGoncharov. I'm confident the request is making to router because I've removed other headers, like Content Type, and the error changes to reflect those missing headers. For some reason only the Accept header isn't making it. There's no firewall in place; this http request is being sent from a docker container running my application to a docker container running Router via a github action.

**Comment by michaelcaterisano** [comment]
Yep, it works with `rover dev`. I believe this may be an issue related to the way we have our GHAs set up; suspecting this may be istio related. I'll report back once I find the issue; thanks for taking a look!

**Comment by michaelcaterisano** [comment]
@goto-bus-stop Unfortunately still no luck with this. Istio isn't in the picture, so that's no the issue. I'm now wondering if the github-hosted runner could be modifying the accept header.

I have the router log level set to debug, but am not able to see the headers its receiving. Is there a way to check that?

**Comment by michaelcaterisano** [comment]
@goto-bus-stop @IvanGoncharov I've reproduced the error locally by running an instance of Apollo Router in a docker container per [the docs](https://www.apollographql.com/docs/graphos/routing/self-hosted/containerization/docker). 

I'm sending this (somewhat redacted) request

```
 curl --request POST \
    --header 'content-type: application/json' \
    --header 'Authorization: Bearer [REDACTED]' \
    --header 'accept: multipart/mixed; boundary="graphql"; subscriptionSpec=1.0, application/json' \
    --url 'http://localhost:4000' \
    --data '{"query":"subscription MySubscription { ... my fields and variables here}"}}}}'
```

And I get this error:

```
{"data":null,"errors":[{"message":"HTTP fetch failed from 'massdriver': 406: Not Acceptable","extensions":{"code":"SUBREQUEST_HTTP_ERROR","service":"massdriver","reason":"406: Not Acceptable","http":{"status":406}}},{"message":"the router received a query with a subscription but the client does not accept multipart/mixed HTTP responses. To enable subscription support, add the HTTP header 'Accept: multipart/mixed;subscriptionSpec=1.0'","extensions":{"code":"SUBSCRIPTION_BAD_HEADER","service":"massdriver"}}]}%   
```

Confusingly, the same curl command works against a deployed router instance, so I'm confident that the request is valid. The router config is slightly different between the two instances, but it's not obvious to me what part could be responsible for the different behavior. Notably, the header forwarding portion of the config is the same for both instances. Both instances are using v1.52.1.

Does not work (used locally in a docker container, and in a GHA in a service container): 

```
supergraph:
  introspection: true
  listen: 0.0.0.0:4001
include_subgraph_errors:
  all: true
headers:
  all:
    request:
      - propagate:
          matching: .*
      - insert:
          name: "apollographql-operation-id"
          from_context: "apollo_operation_id"
homepage:
  enabled: false
sandbox:
  enabled: true
cors:
  allow_any_origin: true
telemetry:
  instrumentation:
    spans:
      mode: spec_compliant
rhai:
  scripts: "/dist/scripts"
  main: "main.rhai"
subscription:
  enabled: true
  mode:
    callback:
      public_url: http://localhost:4001/callback
      listen: 0.0.0.0:4001
      path: /callback
      heartbeat_interval: 5s
      subgraphs:
        - massdriver
        - 
```

Does work (deployed, some config relevant to our K8s infra):

```
       supergraph:
            listen: 0.0.0.0:8080
            introspection: true
            path: /graphql
          override_subgraph_url:
            massdriver: [REDACTED]
          include_subgraph_errors:
            all: true
          health_check:
            listen: 0.0.0.0:8080
          headers:
            all:
              request:
                - propagate:
                    matching: .*
                - insert:
                    name: "apollographql-operation-id"
                    from_context: "apollo_operation_id"
          telemetry:
            apollo:
              field_level_instrumentation_sampler: 0.01
              send_variable_values: all
            exporters:
              metrics:
                common:
                  service_name: "apollo-router"
                otlp:
                  enabled: true
                  temporality: delta
                  endpoint: [REDACTED]
          homepage:
            enabled: false
          sandbox:
            enabled: true
          cors:
            allow_any_origin: true
          rhai:
            scripts: "/dist/config"
            main: "main"
```
