### ISSUE TITLE
Send logs to OpenTelemetry exporter

### ISSUE THREAD

**Issue by smyrick** [apollographql/router#6508]
## Is your feature request related to a problem? Please describe.
Today I can configure my log exporter in the Router v1.59.0 with the [following options](https://www.apollographql.com/docs/graphos/reference/router/telemetry/log-exporters/stdout) to STDOUT.

```yaml
telemetry:
  exporters:
    logging:

      common:
         resource:
           "environment.name": "production"
           "environment.namespace": "{env.MY_K8_NAMESPACE_ENV_VARIABLE}"

      stdout:
        enabled: true
        format: text
```

However, my telemetry systems, like [Dynatrace](https://docs.dynatrace.com/docs/discover-dynatrace/references/dynatrace-api/environment-api/opentelemetry/post-logs), support sending logs to an ingest API with OpenTelemetry

## Describe the solution you'd like
I would like to be able to configure an `otlp` block similar to [traces](https://www.apollographql.com/docs/graphos/reference/router/telemetry/trace-exporters/otlp) and [metrics](https://www.apollographql.com/docs/graphos/reference/router/telemetry/metrics-exporters/otlp) exporters in the Router for `logging`

```yaml
telemetry:
  exporters:
    logging:

      otlp:
        enabled: true
        endpoint: ${env.DYNATRACE_URL}
        protocol: http
        http:
          headers:
            "Authorization": "Api-Token ${env.DT_TOKEN}"
```

## Describe alternatives you've considered
There are usually many ways I can get STDOUT logs from my Router runtime to o11y systems. This can include system the run on k8s, my cloud provider, or other tools and services.

- https://docs.dynatrace.com/docs/analyze-explore-automate/logs/lma-log-ingestion/lma-log-ingestion-via-api/lma-fluent-bit-logs-k8s
- https://docs.dynatrace.com/docs/analyze-explore-automate/logs/lma-log-ingestion/lma-log-ingestion-via-api/lma-cloud-provider-log-forwarding
- https://docs.dynatrace.com/docs/analyze-explore-automate/logs/lma-log-ingestion/lma-log-ingestion-via-api/lma-stream-logs-with-logstash

## Additional Context
Otel Logging has become a standard and the spec is 1.0, but this happened in [late 2023](https://www.infoq.com/news/2023/11/otel-logging-stable/#:~:text=%22We're%20announcing%20that%20OpenTelemetry,is%20not%20going%20to%20change.%22)
