### ISSUE TITLE
header propogation for pass through rule not working

### ISSUE THREAD

**Issue by sachet-mittal** [apollographql/router#6575]
## Describe the bug
After upgrading router from 1.4 to 1.59, the headers are not propagating from super-graph to sub-graph

## To Reproduce
1. Update the router binary from `curl -sSL https://router.apollo.dev/download/nix/latest | sh`
2. Update the container image:
```
-FROM --platform=linux/X86_64 ghcr.io/apollographql/router:v1.40.1
+FROM --platform=linux/X86_64 ghcr.io/apollographql/router:v1.59.0
 ```
3. Update the config from `./router config upgrade <path to yaml>`
4. header rules:

```
headers:
  all:
    request:
    # https://deploy-preview-4733--apollo-router-docs.netlify.app/configuration/header-propagation#rule-ordering
    # propagate rest of the headers to subgraph
      - propagate:
          matching: .*
      # rename the headers before propagating to subgraph
      - propagate:
          named: <header 1>
          rename: client-<header 1>
     - propagate:
              named: <header 2>
              rename: client-<header 2>
     - propagate:
              named: <header 3>
              rename: client-<header 3>

```
 I tried to put the pass-through rule both at the top and bottom. But it  the result is same regadless

## Expected behavior
- All the headers should go to sub graphs

## Output
- The apis fail with this error:
```
subgraph response contains invalid 'content-type' header value "null"; expected content-type: application/json or content-type: application/graphql-response+json, Location: undefined, Path:
```
I added logs on both super graph and sub graph. I do see this header in super graph logs but not so in subgraph log.

Am I missing something here?
