### ISSUE TITLE
Header propagation by name only flagged as invalid config

### ISSUE THREAD

**Issue by BrynCooke** [apollographql/router#708]
The following config is flagged as invalid:

```yaml
headers:
  all:
    - propagate:
        named: test
```

This is because the `rename` and `default` keys have not been marked as defaulted in the serde config.
