### ISSUE TITLE
Entity caching subgraph overrides not working

### ISSUE THREAD

**Issue by FahimSiddiquiDev** [apollographql/router#7122]
## Describe the Bug

Entity caching behaves inconsistently when both global TTL and per-subgraph TTLs are defined. Specifically:

- Entity caching works correctly when only global TTL is defined or when only per-subgraph TTL is defined.
- However, when both are configured simultaneously, the global TTL always takes precedence, and subgraph-specific TTL values are ignored.

## Reference

According to the [Apollo documentation](https://www.apollographql.com/docs/graphos/routing/performance/caching/entity#configure-router-for-entity-caching), entity caching should respect subgraph-specific TTL values if provided:

> Configure entity caching per subgraph, with overrides per subgraph for disabling entity caching and TTL.

Router Configuration Example

```yaml
preview_entity_cache:
  enabled: true
  expose_keys_in_context: true
  subgraph:
    all:
      enabled: true
      redis:
        urls: ["redis://host.docker.internal:6379”]
        timeout: 2s
        ttl: 120s
    subgraphs:
      product-service:
        ttl: 60s  # Time-to-live for cached entities from product-service
      inventory-service:
        ttl: 90s  # Time-to-live for cached entities from inventory-service
```
Note: The global TTL can be either higher or lower than the individual subgraph TTLs.

## Steps to Reproduce

1. Configure the router with the above YAML configuration.
2. Trigger caching for entities from product-service and inventory-service.
3. Observe the cache expiration times.

## Expected Behavior

The TTL values for each subgraph should take precedence over the global TTL:

- Entities from product-service should have a 60s TTL.
- Entities from inventory-service should have a 90s TTL.

## Actual Behavior

- All entities are cached for 120s (the global TTL), ignoring the subgraph-specific values.
- Cache respones (checked a few seconds later):
```bash 
127.0.0.1:6379> TTL version:1.0:subgraph:product-service:type:Query:hash:8ab7bc4e9de4c14e35426675620bb984c40a3b992c4395c7815d43816ed23a32:data:faa1c49292e3ee1b183ec6e23ec2340be08d8cbef64cf90f656910a83ecfdbf4
(integer) 117
127.0.0.1:6379> TTL version:1.0:subgraph:inventory-service:type:Variant:entity:a682fab03b350c915afe9382fd96fc8ec1ce1b94ab06e905bbf095d2382ddf08:hash:8f77615571b7de8c090851b9f3abcd3a2d0970e5c1f381643553d1ab138fcf5b:data:d9d84a3c7ffc27b0190a671212f3740e5b8478e84e23825830e97822e25cf05c
(integer) 115
127.0.0.1:6379> 
```
- Graphql query response headers:
```json
{
  "access-control-allow-origin": "*",
  "cache-control": "max-age=120,public",
  "content-encoding": "gzip",
  "content-type": "application/json",
  "date": "Wed, 26 Mar 2025 11:53:17 GMT",
  "transfer-encoding": "chunked",
  "vary": "origin"
}
```

## Desktop (please complete the following information):

- OS: [e.g., macOS Sequoia 15.3.2]

- Apollo Router Version: [e.g., 2.0.0]

## Additional Context:

Please advise if this behavior is expected or if there are additional configuration steps required to ensure subgraph-specific TTLs are respected.)
