### ISSUE TITLE
Telemetry configuration

### ISSUE THREAD

**Issue by o0Ignition0o** [apollographql/router#720]
trace_config resource key and value.

telemetry trace_config key and value overrides need this to work at the moment: 

```yml
        trace_config:
          resource:
            attrs:
              service.name:
                String: router
              service.namespace:
                String: apollo

```

We want to be able to parse a flattened equivalent such as this instead:

```yml
        trace_config:
          resource:
              service.name: router
              service.namespace:  apollo
```
