### ISSUE TITLE
CSRF blocked all internal routes

### ISSUE THREAD

**Issue by Samjin** [apollographql/router#7326]
The router v2 had moved CSRF o early request lifecycle which would block all routes. The current behavior force user with additional routes to turn off CSRF completely. 

E.g. Clients who need to access those endpoints like `/playground` or `/buildinfo` etc can't update headers since they just open browser and go to the urls. Some of the additional routes maybe required by client CICD.  

Proposed config:
```
csrf:
  unsafe_disabled: false // Backward compatible
  exempt_routes: // Allowed routers
    - "/buildinfo"
    - "/playground"
```
