### ISSUE TITLE
Router 2.2.1 version throws this telemetry error which is unknown

### ISSUE THREAD

**Issue by riginoommen** [apollographql/router#7423]
`
2025-05-07T15:12:01.905848Z ERROR resource{service.namespace="rh-graphql",service.version="2.2.1-rc.1",service.name="rhg-router",process.executable.name="router",} tokio-runtime-worker ThreadId(10) apollo_router::plugins::telemetry::error_handler: apollo-router/src/plugins/telemetry/error_handler.rs:92 OpenTelemetry metric error occurred: Metrics exporter otlp failed with the grpc server returns error (Unknown error): , detailed error message: h2 protocol error: http2 error tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: GoAway(b"", FRAME_SIZE_ERROR, Library) }))
`

https://www.apollographql.com/docs/graphos/routing/errors

in the errors FRAME_SIZE_ERROR is not documented.

Router throws this log with 2.0 version for telemetry

**Comment by riginoommen** [comment]
in 1.x version everything works fine

**Comment by abernix** [comment]
what does `OTEL_EXPORTER_OTLP_ENDPOINT` look like?  what's the scheme? (is it specified or is it missing)? what's the port? what's the path? 

can you provide a docker compose with a repo?

**Comment by riginoommen** [comment]
docker-compose file 

```
version: '3.8'

services:
  # Jaeger service for OpenTelemetry tracing
  jaeger:
    image: jaegertracing/all-in-one:1.35
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
      - "5778:5778"    # Configuration API
      - "9411:9411"    # Zipkin compatible endpoint
    networks:
      - apollo-network

  # Apollo Router service
  apollo-router:
    build:
      context: .  # Build the Apollo Router from the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: apollo-router
    ports:
      - "4000:4000"  # Apollo Router default port
    env_file:
      - docker.env
    depends_on:
      - jaeger  # Ensure Jaeger starts before the Apollo Router
    networks:
      - apollo-network

# Define a custom network for communication between services
networks:
  apollo-network:
    driver: bridge

```
