### ISSUE TITLE
helm repo for chart installation

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/router#913]
**Is your feature request related to a problem? Please describe.**
Following on from #786 we now have a chart in git, but it is not published anywhere (that I'm aware of yet). A workflow would be 
```bash
helm repo add apollographql <chart-repo-url>
helm upgrade --install apollographql/router router
```

Opening this issue to track a common repository that chart versions will be published to

**Describe the solution you'd like**
There are many solutions different distributions have come up with, but the current container is hosted with github container registry and reading some articles like https://www.visualstudiogeeks.com/github/publish-helm-3-charts-to-gcr it seems GCR also supports OCI artifacts which helm3 can use. 

**Describe alternatives you've considered**
Some way of using the chart from the repo directly without publishing it

**Comment by garypen** [comment]
As a project team, we don't have a need to run/maintain a helm repo right now.

You can just use the chart directly from the repo without publishing it. Checkout the repo and cd to <repo>/helm/chart. Then run something like this (assuming you have helm3 and kubectl installed/configured). Choose a namespace and name appropriately for your environment.
```
helm install --set managedFederation.apiKey=<your API key> --set managedFederation.graphRef=<your graph ref> --namespace garypen router-test router --values router/values.yaml

% helm -n garypen list
NAME       	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART       	APP VERSION     
router-test	garypen  	1       	2022-04-26 08:27:06.142027 +0100 BST	deployed	router-0.1.0	v0.1.0-preview.2
% kubectl -n garypen get pods
NAME                           READY   STATUS    RESTARTS   AGE
router-test-5fcff6546b-hgmks   0/1     Running   0          9s
% kubectl -n garypen get pods
NAME                           READY   STATUS    RESTARTS   AGE
router-test-5fcff6546b-hgmks   1/1     Running   0          13s
garypen@Garys-MBP chart %
```

**Comment by hobbsh** [comment]
@garypen For a lot of helm implementations, especially controller-based ones like `flux`, I don't think this is an acceptable solution. It's possible to use GitHub Pages as a helm repository to keep overhead low - happy to help/advise if needed.

**Comment by pellizzetti** [comment]
As @hobbsh pointed, in GitOps toolkit controllers, it's recommended to retrieve Helm charts from Helm repositories, as they are lightweight in processing and make it possible to configure a semantic version selector for the chart version that should be released.

---

As for `Flux` specifically, it's possible to add a source as a Git Repository:

```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: apollographql
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/apollographql/router
  ref:
    branch: main
  ignore: |
    /*
    !/helm/chart/
```

And use the source on the Helm Release:

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apollographql-router
spec:
  releaseName: apollographql-router
  chart:
    spec:
      chart: ./helm/chart/router
      version: "0.1.x"
      sourceRef:
        kind: GitRepository
        name: apollographql
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
```
