### ISSUE TITLE
Bad configuration error report

### ISSUE THREAD

**Issue by bnjjj** [apollographql/router#921]
if you try to put this config:

```yaml
server:
  # The socket address and port to listen on
  # Defaults to 127.0.0.1:4000
  listen: 127.0.0.1:4000
  bad:
    value: error
```

you will have this error:

```
2022-04-26T15:48:28.991268Z ERROR apollo_router: configuration had errors:
1. /server

#
server:
  # The socket address and port to listen on
  # Defaults to 127.0.0.1:4000
  listen: 127.0.0.1:4000
        ^----- Additional properties are not allowed ('bad' was unexpected)
```

it could be great to have: 

```
2022-04-26T15:48:28.991268Z ERROR apollo_router: configuration had errors:
1. /server

#
server:
  # The socket address and port to listen on
  # Defaults to 127.0.0.1:4000
  listen: 127.0.0.1:4000
  bad:
  ^----- Additional properties are not allowed ('bad' was unexpected)
```
