### ISSUE TITLE
Datadog integration: trace not reaching backend services, stops at the router

### ISSUE THREAD

**Issue by krisztian-sala** [apollographql/router#932]
I configured the Datadog integration and the spans reach Datadog. But there is no correlation between the router and the other microservices.
   
When using the Apollo federation gateway, I can see from Datadog that the request arrives to the gateway and how it reaches the backend microservices, all the way to the database - so the distributed tracing works.  

With the router, I can only see that the request reaches the router - and nothing else. Like the Span id couldn't be shared with the other services. I experienced the same thing when I tried sending the traces to the OTEL collector and pushing those to Datadog. But I thought the Datadog integration would fix this issue.  

After searching a bit, it might be related [to this](https://docs.datadoghq.com/tracing/connect_logs_and_traces/opentelemetry/).

Example. The same request, first with federation and second with the router:  

<img width="1169" alt="dd_1" src="https://user-images.githubusercontent.com/88720831/165106551-ebd22946-eb68-4649-b7b2-5d332be6f735.png">
<img width="363" alt="dd_2" src="https://user-images.githubusercontent.com/88720831/165106559-16541938-3c84-4142-964a-0d472b5d5088.png">

Version used: `v0.1.0-preview.6`
Configuration:
```
 tracing:
    trace_config:
      service_name: "${DD_SERVICE:apollo-router}"
      service_namespace: "${DD_ENV:none}" # this is not appearing in the trace
      sampler: 1
      attributes:
        datadog.test: test # this is not appearing in the trace
    propagation:
      datadog: true
      trace_context: true
      baggage: true
    datadog:
      endpoint: http://datadog.default:8126
```

_Originally posted by @krisztian-sala in https://github.com/apollographql/router/issues/851#issuecomment-1108630564_
