### ISSUE TITLE
jaeger telemetry not coming through

### ISSUE THREAD

**Issue by damienpontifex** [apollographql/router#941]
**Describe the bug**
Configured the router to use jaeger telemetry via direct jaeger config or otlp setup, but router displays errors

**To Reproduce**
- Router config file used
```yaml
server:
  listen: 0.0.0.0:4000

telemetry:
  tracing:
    trace_config:
      service_name: router
#    otlp: # also tried otlp but same outcome
#      endpoint: http://jaeger
    jaeger:
      agent:
        endpoint: http://jaeger
```
- Docker compose file for creating
```yaml
version: '3'

services:
  router:
    image: ghcr.io/apollographql/router:v0.1.0-preview.6
    environment:
      APOLLO_KEY: <managed-federation-key>
      APOLLO_GRAPH_REF: <managed-federation-ref>
      CONFIGURATION_PATH: /router-config.yaml
      RUST_LOG: debug
    ports:
    - 4000:4000
    volumes:
    - ./router-config.yaml:/router-config.yaml
    depends_on:
    - jaeger
    networks:
      router-jaeger:

  # http://localhost:16686
  # Copied ports from https://www.jaegertracing.io/docs/1.33/getting-started/
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14250:14250
    - 14268:14268
    - 14269:14269
    - 9411:9411
    networks:
      router-jaeger:

  # Used to validate jaeger container is fine
  jaeger-hotrod:
    image:  jaegertracing/example-hotrod:latest
    environment:
      JAEGER_AGENT_HOST: jaeger
    ports:
    - 8080:8080
    networks:
      router-jaeger:

networks:
  router-jaeger:
```

- Noticed logs like `{"message":"creating plugin: 'apollo.telemetry' with configuration:\n{}"}`
- Noticed logs like `WindowUpdate` and `GoAway` logs that I assume are from jaeger

**Expected behavior**
Router to send telemetry to jaeger container for observation

**Output**
- Observe router logs
[router-logs.txt](https://github.com/apollographql/router/files/8601460/router-logs.txt)

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1 running docker desktop 4.6.1

**Additional context**
Either stuck and not able to configure or this is a bug in setting up telemetry configuration with open telemetry. Used the jaeger-hotrod container to validate that telemetry was able to get from one container to another within the compose environment to ensure jaeger was working properly. That worked, but router could never send data

**Comment by damienpontifex** [comment]
Thanks @BrynCooke I didn't read the different of `agent` and `collector` on [tracing docs](https://www.apollographql.com/docs/router/configuration/tracing) page

Although updating to `collector` and still no luck.

Browsing through the source as I was intrigued about this log message `{"message":"creating plugin: 'apollo.telemetry' with configuration:\n{}"}`
https://github.com/apollographql/router/blob/25460f5fc17988b9564084a9eac9f49c6b0db700/apollo-router/src/configuration/mod.rs#L95-L132

And debugging this method with my config, I can see that `plugins` vec has two elements with the `"apollo.telemetry"` tuples first element because of the `is_global_subscriber_set` condition, but is there a chance when it's doing the `final_plugins` map that it's discarding my config and using the empty config for `"apollo.telemetry"` that it got from the first vec push?

I ask particularly because the log message of `{"message":"creating plugin: 'apollo.telemetry' with configuration:\n{}"}` doesn't log my config instead logs empty object

**Comment by damienpontifex** [comment]
Hmm I can also see there are some changes to the above mentioned file that are more recent the preview.6 that I'm running in docker vs the code I'm debugging from main. So two might not be like-for-like representative

**Comment by damienpontifex** [comment]
Got it working running off main with config
```yaml
telemetry:
  tracing:
    trace_config:
      service_name: router
    jaeger:
      collector:
        endpoint: http://localhost:14268/api/traces
```
and jaeger running in docker with
```bash
docker run --rm -p6831:6831/udp -p6832:6832/udp -p16686:16686 -p14268:14268 jaegertracing/all-in-one:latest
```

I think I could contribute some info to the docs to help others (read "me when I try this again" :) )
