### ISSUE TITLE
Add a Kubernetes configuration example

### ISSUE THREAD

**Issue by Geal** [apollographql/router#958]
this should show how to interact with the health and metrics endpoints

**Comment by kmcrawford** [comment]
Something like below would work, this requires you to create a secret containing your `APOLLO_KEY` and a configmap containing your `router.yaml`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      annotations:
        prometheus.io/path: /plugins/apollo.telemetry/prometheus
        prometheus.io/port: "4000"
        prometheus.io/scrape: "true"
      labels:
        app: router
    spec:
      containers:
      - env:
        - name: APOLLO_GRAPH_REF
          value: <mygraph>
        - name: CONFIGURATION_PATH
          value: /config/router.yaml
        envFrom:
        - secretRef:
            name: <secretName with APOLLO_KEY>
        image: ghcr.io/apollographql/router:v0.1.0-preview.7
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/apollo/server-health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: router
        ports:
        - containerPort: 4000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /.well-known/apollo/server-health
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
      volumes:
      - configMap:
          defaultMode: 420
          name: <my-configMap that contains my router.yaml>
        name: config
```        

secret Example:
`kubectl create secret generic router --from-literal=APOLLO_KEY=<your key>`
configMap Example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: router-config
data:
  router.yaml: |
    telemetry:
      metrics:
        prometheus:
          enabled: true
```
